/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mklivre;

import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;
import javax.swing.JOptionPane;

/**
 *
 * @author willi
 */
public class CaminhoDaDeletacao extends javax.swing.JFrame {

    /**
     * Creates new form CaminhoDaDeletacao
     */
    public CaminhoDaDeletacao() {
        initComponents();
        URL caminhoIcone = getClass().getResource("/mklivre/icone/icone2.png");
        Image iconeTitulo = Toolkit.getDefaultToolkit().getImage(caminhoIcone);
        this.setIconImage(iconeTitulo);
        varML1.setVisible(false);
        varML2.setVisible(false);
        varEs1.setVisible(false);
        varEs2.setVisible(false);
    }
    int nivel;
    String acesso="admin",nome;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        varEs2 = new javax.swing.JLabel();
        varEs1 = new javax.swing.JLabel();
        varML2 = new javax.swing.JLabel();
        varML1 = new javax.swing.JLabel();
        apagarML = new javax.swing.JButton();
        apagarEs = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        mostrarNivel = new javax.swing.JLabel();
        acessoUser = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("APAGAR");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(null);

        varEs2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/faixa-cinza-5.png"))); // NOI18N
        getContentPane().add(varEs2);
        varEs2.setBounds(220, 170, 140, 40);

        varEs1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/faixa-cinza-5.png"))); // NOI18N
        getContentPane().add(varEs1);
        varEs1.setBounds(220, 170, 140, 40);

        varML2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/faixa-cinza-5.png"))); // NOI18N
        getContentPane().add(varML2);
        varML2.setBounds(30, 170, 140, 40);

        varML1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/faixa-cinza-5.png"))); // NOI18N
        getContentPane().add(varML1);
        varML1.setBounds(30, 170, 140, 40);

        apagarML.setBackground(new java.awt.Color(0, 0, 0));
        apagarML.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        apagarML.setForeground(new java.awt.Color(255, 255, 255));
        apagarML.setText("ML");
        apagarML.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apagarMLActionPerformed(evt);
            }
        });
        apagarML.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                apagarMLKeyPressed(evt);
            }
        });
        getContentPane().add(apagarML);
        apagarML.setBounds(30, 170, 140, 40);

        apagarEs.setBackground(new java.awt.Color(0, 0, 0));
        apagarEs.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        apagarEs.setForeground(new java.awt.Color(255, 255, 255));
        apagarEs.setText("ESTOQUE");
        apagarEs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apagarEsActionPerformed(evt);
            }
        });
        apagarEs.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                apagarEsKeyPressed(evt);
            }
        });
        getContentPane().add(apagarEs);
        apagarEs.setBounds(220, 170, 140, 40);

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/CAIXAS.png"))); // NOI18N
        getContentPane().add(jLabel17);
        jLabel17.setBounds(250, 130, 250, 80);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 21)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("ESCOLHA UMA OPÇÃO");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(160, 10, 260, 60);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/MERCADO LIVEW.png"))); // NOI18N
        getContentPane().add(jLabel14);
        jLabel14.setBounds(110, 130, 140, 80);

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 21)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("LOCAL DA PEÇA A SER APAGADA");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(20, 90, 360, 60);

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Sem título.png"))); // NOI18N
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 0, 150, 80);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundo preto.png"))); // NOI18N
        jLabel1.setMinimumSize(new java.awt.Dimension(1057, 340));
        jLabel1.setPreferredSize(new java.awt.Dimension(1057, 350));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 4, 450, 77);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/FUNDO AMARELO.jpg"))); // NOI18N
        getContentPane().add(jLabel11);
        jLabel11.setBounds(0, -331, 460, 430);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/RS.png"))); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(280, 50, 570, 530);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/RS.png"))); // NOI18N
        getContentPane().add(jLabel10);
        jLabel10.setBounds(-30, 0, 390, 490);

        mostrarNivel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        mostrarNivel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mostrarNivel.setText("5");
        getContentPane().add(mostrarNivel);
        mostrarNivel.setBounds(520, 130, 50, 70);

        acessoUser.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        acessoUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        acessoUser.setText("ADMIN");
        getContentPane().add(acessoUser);
        acessoUser.setBounds(520, 220, 70, 60);

        setSize(new java.awt.Dimension(439, 281));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void apagarMLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apagarMLActionPerformed
        if(acesso.equals("ES")&&nivel!=5){
            JOptionPane.showMessageDialog(null,"VOCÊ NÃO TEM ACESSO A ESSE MÓDULO!");
        }
        else{
            ApagarItens ml = new ApagarItens();
            ml.setVisible(true);
            ml.mostrarNivel.setText(mostrarNivel.getText());
            ml.acessoUser.setText(acessoUser.getText());
            this.dispose();
        }
    }//GEN-LAST:event_apagarMLActionPerformed

    private void apagarMLKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_apagarMLKeyPressed
        if(evt.getKeyCode() == evt.VK_ENTER){
            if(acesso.equals("ES")&&nivel!=5){
                JOptionPane.showMessageDialog(null,"VOCÊ NÃO TEM ACESSO A ESSE MÓDULO!");
            }
            else{
                ApagarItens ml = new ApagarItens();
                ml.setVisible(true);
                ml.mostrarNivel.setText(mostrarNivel.getText());
                ml.acessoUser.setText(acessoUser.getText());
                this.dispose();
            }
        }
    }//GEN-LAST:event_apagarMLKeyPressed

    private void apagarEsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apagarEsActionPerformed
        if(acesso.equals("ML")&&nivel!=5){
            JOptionPane.showMessageDialog(null,"VOCÊ NÃO TEM ACESSO A ESSE MÓDULO!");
        }
        else{
            ApagarItensEs es = new ApagarItensEs();
            es.setVisible(true);
            es.mostrarNivel.setText(mostrarNivel.getText());
            es.acessoUser.setText(acessoUser.getText());
            this.dispose();
        }
    }//GEN-LAST:event_apagarEsActionPerformed

    private void apagarEsKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_apagarEsKeyPressed
        if(evt.getKeyCode() == evt.VK_ENTER){
            if(acesso.equals("ML")&&nivel!=5){
                JOptionPane.showMessageDialog(null,"VOCÊ NÃO TEM ACESSO A ESSE MÓDULO!");
            }
            else{
                ApagarItensEs es = new ApagarItensEs();
                es.setVisible(true);
                es.mostrarNivel.setText(mostrarNivel.getText());
                es.acessoUser.setText(acessoUser.getText());
                this.dispose();
            }
        }
    }//GEN-LAST:event_apagarEsKeyPressed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        nivel=Integer.parseInt(mostrarNivel.getText());
        acesso=acessoUser.getText();
        if(acesso.equals("ES")&&nivel!=5){
            varML1.setVisible(true);
            varML2.setVisible(true);
        }
        else if(acesso.equals("ML")&&nivel!=5){
            varEs1.setVisible(true);
            varEs2.setVisible(true);
        }
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CaminhoDaDeletacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CaminhoDaDeletacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CaminhoDaDeletacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CaminhoDaDeletacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CaminhoDaDeletacao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel acessoUser;
    private javax.swing.JButton apagarEs;
    private javax.swing.JButton apagarML;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    public static javax.swing.JLabel mostrarNivel;
    public javax.swing.JLabel varEs1;
    public javax.swing.JLabel varEs2;
    public javax.swing.JLabel varML1;
    public javax.swing.JLabel varML2;
    // End of variables declaration//GEN-END:variables
}
