/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mklivre;

import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;
import javax.swing.JOptionPane;
import java.sql.*;
import controle.ModuloConexao;
import java.text.DecimalFormat;
/**
 *
 * @author willi
 */
public class EstoqueCadastroItem extends javax.swing.JFrame {
    Connection conexao = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    /**
     * Creates new form CadastroItem
     */
    public EstoqueCadastroItem() {
        initComponents();
        URL caminhoIcone = getClass().getResource("/mklivre/icone/icone2.png");
        Image iconeTitulo = Toolkit.getDefaultToolkit().getImage(caminhoIcone);
        this.setIconImage(iconeTitulo);
        conexao = ModuloConexao.conector();
    }
    DecimalFormat df =  new DecimalFormat("0.00");
    private void adicionar(){
        String sql = "insert into tb_pecas_es2(NOME,CÓDIGO,CAIXA,LOCALIZAÇÃO,MARCA,QUANTIDADE,CUSTO,PREÇO,OBSERVAÇÕES,REQUISIÇÃO,QUANTIDADE_REQUISITADA,QUANTIDADE_DE_VENDAS,LUCRO) values(?,?,?,?,?,?,?,?,?,?,?,?,?)";
        try {
            pst = conexao.prepareStatement(sql);
            pst.setString(1,cadastroNome.getText());
            pst.setString(2,cadastroCodigo.getText());
            pst.setString(3, cadastroCusto.getText());
            pst.setString(4,cadastroLocalizacao.getText());
            pst.setString(5,cadastroMarca.getText());
            pst.setInt(6,Integer.parseInt(cadastroQuantidadeDisponivel.getText()));
            pst.setString(7, varCusto.getText().replace(",","."));
            pst.setString(8, varVenda.getText().replace(",","."));
            pst.setString(9, cadastroObservacoes.getText());
            pst.setString(10,"NÃO");
            pst.setInt(11,0);
            pst.setInt(12,0);
            float lucro=(Float.parseFloat(varVenda.getText().replace(",","."))-Float.parseFloat(varCusto.getText().replace(",",".")));
            String aux=df.format(lucro);
            pst.setString(13,aux);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null,"ITEM CADASTRADO COM SUCESSO");
            TodosOsItensCadastrados usuario = new TodosOsItensCadastrados();
            usuario.setVisible(true);
            usuario.nomePeca.setText(cadastroNome.getText());
            usuario.codigoCadastrado.setText(cadastroCodigo.getText());
            usuario.marcaCadastrada.setText(cadastroMarca.getText());
            usuario.quantCadastrada.setText(cadastroQuantidadeDisponivel.getText());
            usuario.custoCadastrado.setText(varCusto.getText());
            usuario.precoDeVenda.setText(varVenda.getText());
            usuario.lucroCadastrado.setText(aux);
            usuario.caixaLocalizada.setText(cadastroCusto.getText());
            usuario.localizacaoCadastrada.setText(cadastroLocalizacao.getText());
            usuario.cadastroObservacoes.setText(cadastroObservacoes.getText());
            usuario.mostrarNivel.setText(mostrarNivel.getText());
            usuario.acessoUser.setText(acessoUser.getText());
            this.dispose();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        cadastroCodigo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cadastroMarca = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        cadastroNome = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        cadastroObservacoes = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        cadastroQuantidadeDisponivel = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        cadastroCusto = new javax.swing.JTextField();
        botaoEntrarIniciall2 = new javax.swing.JButton();
        botaoEntrarIniciall3 = new javax.swing.JButton();
        cadastroLocalizacao = new javax.swing.JTextField();
        ssss = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        varCusto = new javax.swing.JTextField();
        varVenda = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        mostrarNivel = new javax.swing.JLabel();
        acessoUser = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(752, 619));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("CÓDIGO");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(310, 110, 100, 17);

        cadastroCodigo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cadastroCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cadastroCodigoKeyPressed(evt);
            }
        });
        getContentPane().add(cadastroCodigo);
        cadastroCodigo.setBounds(310, 140, 150, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("CAIXA");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(520, 110, 130, 17);

        cadastroMarca.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cadastroMarca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cadastroMarcaKeyPressed(evt);
            }
        });
        getContentPane().add(cadastroMarca);
        cadastroMarca.setBounds(310, 230, 150, 30);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 0, 0));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("*");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(140, 180, 20, 60);

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 0, 0));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("*");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(370, 90, 20, 60);

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 0, 0));
        jLabel18.setText("*");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(580, 110, 30, 22);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 0, 0));
        jLabel16.setText("*");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(720, 190, 20, 40);

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("NOME");
        getContentPane().add(jLabel19);
        jLabel19.setBounds(30, 110, 70, 17);

        cadastroNome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cadastroNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cadastroNomeKeyPressed(evt);
            }
        });
        getContentPane().add(cadastroNome);
        cadastroNome.setBounds(30, 140, 200, 30);

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("OBSERVAÇÕES");
        getContentPane().add(jLabel21);
        jLabel21.setBounds(30, 370, 200, 17);

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("QUANTIDADE DISPONÍVEL");
        getContentPane().add(jLabel20);
        jLabel20.setBounds(520, 200, 200, 17);

        cadastroObservacoes.setColumns(20);
        cadastroObservacoes.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        cadastroObservacoes.setRows(5);
        cadastroObservacoes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cadastroObservacoesKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(cadastroObservacoes);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(30, 400, 690, 130);

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Sem título.png"))); // NOI18N
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 0, 150, 80);

        cadastroQuantidadeDisponivel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cadastroQuantidadeDisponivel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cadastroQuantidadeDisponivelKeyPressed(evt);
            }
        });
        getContentPane().add(cadastroQuantidadeDisponivel);
        cadastroQuantidadeDisponivel.setBounds(520, 230, 80, 30);

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 0, 0));
        jLabel26.setText("*");
        getContentPane().add(jLabel26);
        jLabel26.setBounds(80, 100, 20, 40);

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 0, 0));
        jLabel27.setText("*");
        getContentPane().add(jLabel27);
        jLabel27.setBounds(370, 190, 20, 40);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ESTOQUE.png"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(690, 0, 60, 80);

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("MARCA");
        getContentPane().add(jLabel22);
        jLabel22.setBounds(310, 200, 150, 17);

        cadastroCusto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cadastroCusto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cadastroCustoKeyPressed(evt);
            }
        });
        getContentPane().add(cadastroCusto);
        cadastroCusto.setBounds(520, 140, 80, 30);

        botaoEntrarIniciall2.setBackground(new java.awt.Color(0, 0, 0));
        botaoEntrarIniciall2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        botaoEntrarIniciall2.setForeground(new java.awt.Color(255, 255, 255));
        botaoEntrarIniciall2.setText("CADASTRAR");
        botaoEntrarIniciall2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoEntrarIniciall2ActionPerformed(evt);
            }
        });
        botaoEntrarIniciall2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                botaoEntrarIniciall2KeyPressed(evt);
            }
        });
        getContentPane().add(botaoEntrarIniciall2);
        botaoEntrarIniciall2.setBounds(30, 560, 160, 40);

        botaoEntrarIniciall3.setBackground(new java.awt.Color(0, 0, 0));
        botaoEntrarIniciall3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        botaoEntrarIniciall3.setForeground(new java.awt.Color(255, 255, 255));
        botaoEntrarIniciall3.setText("PESQUISAR");
        botaoEntrarIniciall3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoEntrarIniciall3ActionPerformed(evt);
            }
        });
        botaoEntrarIniciall3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                botaoEntrarIniciall3KeyPressed(evt);
            }
        });
        getContentPane().add(botaoEntrarIniciall3);
        botaoEntrarIniciall3.setBounds(290, 560, 160, 40);

        cadastroLocalizacao.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cadastroLocalizacao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cadastroLocalizacaoKeyPressed(evt);
            }
        });
        getContentPane().add(cadastroLocalizacao);
        cadastroLocalizacao.setBounds(30, 230, 200, 30);

        ssss.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ssss.setForeground(new java.awt.Color(255, 255, 255));
        ssss.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ssss.setText("CUSTO");
        ssss.setPreferredSize(null);
        getContentPane().add(ssss);
        ssss.setBounds(20, 290, 70, 17);

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel29.setText("PREÇO DE VENDA");
        getContentPane().add(jLabel29);
        jLabel29.setBounds(310, 290, 130, 17);

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("LOCALIZAÇÃO");
        getContentPane().add(jLabel23);
        jLabel23.setBounds(30, 200, 150, 17);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 21)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("CADASTRO DE NOVOS ITENS");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(230, 10, 320, 60);

        varCusto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        varCusto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                varCustoKeyPressed(evt);
            }
        });
        getContentPane().add(varCusto);
        varCusto.setBounds(30, 320, 110, 30);

        varVenda.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        varVenda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                varVendaKeyPressed(evt);
            }
        });
        getContentPane().add(varVenda);
        varVenda.setBounds(310, 320, 150, 30);

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 0, 0));
        jLabel30.setText("*");
        getContentPane().add(jLabel30);
        jLabel30.setBounds(90, 270, 30, 60);

        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 0, 0));
        jLabel31.setText("*");
        getContentPane().add(jLabel31);
        jLabel31.setBounds(450, 270, 20, 60);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundo preto.png"))); // NOI18N
        jLabel1.setMinimumSize(new java.awt.Dimension(1057, 340));
        jLabel1.setPreferredSize(new java.awt.Dimension(1057, 350));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 4, 750, 77);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/FUNDO AMARELO.jpg"))); // NOI18N
        getContentPane().add(jLabel11);
        jLabel11.setBounds(0, -331, 760, 430);

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/NOVO HEHE.png"))); // NOI18N
        getContentPane().add(jLabel28);
        jLabel28.setBounds(170, 530, 80, 70);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/PROCURA HEHE.png"))); // NOI18N
        getContentPane().add(jLabel13);
        jLabel13.setBounds(430, 530, 80, 70);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/RS.png"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(190, 10, 570, 530);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/RS.png"))); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(320, 340, 570, 530);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/RS.png"))); // NOI18N
        getContentPane().add(jLabel9);
        jLabel9.setBounds(-20, 450, 570, 530);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/RS.png"))); // NOI18N
        getContentPane().add(jLabel10);
        jLabel10.setBounds(0, 0, 570, 530);

        mostrarNivel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        mostrarNivel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mostrarNivel.setText("5");
        getContentPane().add(mostrarNivel);
        mostrarNivel.setBounds(520, 130, 50, 70);

        acessoUser.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        acessoUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        acessoUser.setText("ADMIN");
        getContentPane().add(acessoUser);
        acessoUser.setBounds(520, 220, 70, 60);

        setSize(new java.awt.Dimension(756, 637));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botaoEntrarIniciall2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoEntrarIniciall2ActionPerformed
        if(cadastroNome.getText().equals("")||cadastroCodigo.getText().equals("")||cadastroCusto.getText().equals("")||cadastroLocalizacao.getText().equals("")||cadastroMarca.getText().equals("")||cadastroQuantidadeDisponivel.getText().equals("")||varCusto.getText().equals("")||varVenda.getText().equals("")){
            JOptionPane.showMessageDialog(null,"POR FAVOR PREENCHA TODOS OS CAMPOS OBRIGATÓRIOS");
        }
        else{
            adicionar();
        }
    }//GEN-LAST:event_botaoEntrarIniciall2ActionPerformed

    private void botaoEntrarIniciall3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoEntrarIniciall3ActionPerformed
        LocalizarGlobalPecas verifica = new LocalizarGlobalPecas();
        verifica.setVisible(true);
        verifica.mostrarNivel.setText(mostrarNivel.getText());
        verifica.acessoUser.setText(acessoUser.getText());
    }//GEN-LAST:event_botaoEntrarIniciall3ActionPerformed

    private void cadastroNomeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cadastroNomeKeyPressed
        if(evt.getKeyCode() == evt.VK_ENTER){
            cadastroCodigo.requestFocus();
        }
    }//GEN-LAST:event_cadastroNomeKeyPressed

    private void cadastroCodigoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cadastroCodigoKeyPressed
        if(evt.getKeyCode() == evt.VK_ENTER){
            cadastroCusto.requestFocus();
        }
    }//GEN-LAST:event_cadastroCodigoKeyPressed

    private void cadastroCustoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cadastroCustoKeyPressed
        if(evt.getKeyCode() == evt.VK_ENTER){
            cadastroLocalizacao.requestFocus();
        }
    }//GEN-LAST:event_cadastroCustoKeyPressed

    private void cadastroLocalizacaoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cadastroLocalizacaoKeyPressed
        if(evt.getKeyCode() == evt.VK_ENTER){
            cadastroMarca.requestFocus();
        }
    }//GEN-LAST:event_cadastroLocalizacaoKeyPressed

    private void cadastroMarcaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cadastroMarcaKeyPressed
        if(evt.getKeyCode() == evt.VK_ENTER){
            cadastroQuantidadeDisponivel.requestFocus();
        }
    }//GEN-LAST:event_cadastroMarcaKeyPressed

    private void cadastroQuantidadeDisponivelKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cadastroQuantidadeDisponivelKeyPressed
        if(evt.getKeyCode() == evt.VK_ENTER){
            varCusto.requestFocus();
        }
    }//GEN-LAST:event_cadastroQuantidadeDisponivelKeyPressed

    private void varCustoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_varCustoKeyPressed
        if(evt.getKeyCode() == evt.VK_ENTER){
            varVenda.requestFocus();
        }
    }//GEN-LAST:event_varCustoKeyPressed

    private void varVendaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_varVendaKeyPressed
        if(evt.getKeyCode() == evt.VK_ENTER){
            cadastroObservacoes.requestFocus();
        }
    }//GEN-LAST:event_varVendaKeyPressed

    private void cadastroObservacoesKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cadastroObservacoesKeyPressed
        
    }//GEN-LAST:event_cadastroObservacoesKeyPressed

    private void botaoEntrarIniciall2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_botaoEntrarIniciall2KeyPressed
        if(evt.getKeyCode() == evt.VK_ENTER){
            if(cadastroNome.getText().equals("")||cadastroCodigo.getText().equals("")||cadastroCusto.getText().equals("")||cadastroLocalizacao.getText().equals("")||cadastroMarca.getText().equals("")||cadastroQuantidadeDisponivel.getText().equals("")||varCusto.getText().equals("")||varVenda.getText().equals("")){
                JOptionPane.showMessageDialog(null,"POR FAVOR PREENCHA TODOS OS CAMPOS OBRIGATÓRIOS");
            }
            else{
                adicionar();
            }
        }
    }//GEN-LAST:event_botaoEntrarIniciall2KeyPressed

    private void botaoEntrarIniciall3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_botaoEntrarIniciall3KeyPressed
        if(evt.getKeyCode() == evt.VK_ENTER){
            LocalizarGlobalPecas verifica = new LocalizarGlobalPecas();
            verifica.setVisible(true);
            verifica.mostrarNivel.setText(mostrarNivel.getText());
            verifica.acessoUser.setText(acessoUser.getText());
        }
    }//GEN-LAST:event_botaoEntrarIniciall3KeyPressed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        cadastroObservacoes.setWrapStyleWord(true);
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EstoqueCadastroItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EstoqueCadastroItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EstoqueCadastroItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EstoqueCadastroItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EstoqueCadastroItem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel acessoUser;
    private javax.swing.JButton botaoEntrarIniciall2;
    private javax.swing.JButton botaoEntrarIniciall3;
    private javax.swing.JTextField cadastroCodigo;
    private javax.swing.JTextField cadastroCusto;
    private javax.swing.JTextField cadastroLocalizacao;
    private javax.swing.JTextField cadastroMarca;
    private javax.swing.JTextField cadastroNome;
    public static javax.swing.JTextArea cadastroObservacoes;
    private javax.swing.JTextField cadastroQuantidadeDisponivel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JLabel mostrarNivel;
    private javax.swing.JLabel ssss;
    private javax.swing.JTextField varCusto;
    private javax.swing.JTextField varVenda;
    // End of variables declaration//GEN-END:variables
}
