/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mklivre;

import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;
import javax.swing.JOptionPane;
import java.sql.*;
import controle.ModuloConexao;
import java.text.DecimalFormat;
/**
 *
 * @author willi
 */
public class EstoqueAtualizarItem extends javax.swing.JFrame {
    Connection conexao = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    /**
     * Creates new form AtualizarItem
     */
    public EstoqueAtualizarItem() {
        initComponents();
        URL caminhoIcone = getClass().getResource("/mklivre/icone/icone2.png");
        Image iconeTitulo = Toolkit.getDefaultToolkit().getImage(caminhoIcone);
        this.setIconImage(iconeTitulo);
        varApagar1.setVisible(false);
        varApagar2.setVisible(false);
        conexao = ModuloConexao.conector();
    }
    int nivel;
    String acesso="admin",nome;
    DecimalFormat df =  new DecimalFormat("0.00");
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        varApagar1 = new javax.swing.JLabel();
        varApagar2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        botApagar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        cadastroMarca = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        cadastroNome = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        cadastroObservacoes = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        cadastroQuantidadeDisponivel = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        editarCaixa = new javax.swing.JTextField();
        botAtualizar = new javax.swing.JButton();
        editarLocalizacao = new javax.swing.JTextField();
        cadastroCodigo1 = new javax.swing.JTextField();
        varCusto = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        varVenda = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        mostrarNivel = new javax.swing.JLabel();
        acessoUser = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("ATUALIZAR INFORMAÇÕES");
        setMinimumSize(new java.awt.Dimension(754, 579));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(null);

        varApagar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/faixa-cinza-5.png"))); // NOI18N
        getContentPane().add(varApagar1);
        varApagar1.setBounds(290, 560, 140, 40);

        varApagar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/faixa-cinza-5.png"))); // NOI18N
        getContentPane().add(varApagar2);
        varApagar2.setBounds(290, 560, 140, 40);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("CÓDIGO");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(310, 110, 100, 17);

        botApagar.setBackground(new java.awt.Color(0, 0, 0));
        botApagar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        botApagar.setForeground(new java.awt.Color(255, 255, 255));
        botApagar.setText("APAGAR");
        botApagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botApagarActionPerformed(evt);
            }
        });
        botApagar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                botApagarKeyPressed(evt);
            }
        });
        getContentPane().add(botApagar);
        botApagar.setBounds(290, 560, 140, 40);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("CAIXA");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(520, 110, 130, 17);

        cadastroMarca.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cadastroMarca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cadastroMarcaKeyPressed(evt);
            }
        });
        getContentPane().add(cadastroMarca);
        cadastroMarca.setBounds(310, 230, 160, 30);

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("NOME");
        getContentPane().add(jLabel19);
        jLabel19.setBounds(30, 110, 70, 17);

        cadastroNome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cadastroNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cadastroNomeKeyPressed(evt);
            }
        });
        getContentPane().add(cadastroNome);
        cadastroNome.setBounds(30, 140, 200, 30);

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("OBSERVAÇÕES");
        getContentPane().add(jLabel21);
        jLabel21.setBounds(30, 360, 200, 17);

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("QUANTIDADE DISPONÍVEL");
        getContentPane().add(jLabel20);
        jLabel20.setBounds(520, 200, 200, 17);

        cadastroObservacoes.setColumns(20);
        cadastroObservacoes.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        cadastroObservacoes.setRows(5);
        cadastroObservacoes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cadastroObservacoesKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(cadastroObservacoes);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(30, 390, 690, 130);

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Sem título.png"))); // NOI18N
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 0, 150, 80);

        cadastroQuantidadeDisponivel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cadastroQuantidadeDisponivel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cadastroQuantidadeDisponivelKeyPressed(evt);
            }
        });
        getContentPane().add(cadastroQuantidadeDisponivel);
        cadastroQuantidadeDisponivel.setBounds(520, 230, 80, 30);

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("MARCA");
        getContentPane().add(jLabel22);
        jLabel22.setBounds(310, 200, 150, 17);

        editarCaixa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        editarCaixa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                editarCaixaKeyPressed(evt);
            }
        });
        getContentPane().add(editarCaixa);
        editarCaixa.setBounds(520, 140, 80, 30);

        botAtualizar.setBackground(new java.awt.Color(0, 0, 0));
        botAtualizar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        botAtualizar.setForeground(new java.awt.Color(255, 255, 255));
        botAtualizar.setText("ATUALIZAR");
        botAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botAtualizarActionPerformed(evt);
            }
        });
        botAtualizar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                botAtualizarKeyPressed(evt);
            }
        });
        getContentPane().add(botAtualizar);
        botAtualizar.setBounds(30, 560, 140, 40);

        editarLocalizacao.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        editarLocalizacao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                editarLocalizacaoKeyPressed(evt);
            }
        });
        getContentPane().add(editarLocalizacao);
        editarLocalizacao.setBounds(30, 230, 200, 30);

        cadastroCodigo1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cadastroCodigo1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cadastroCodigo1KeyPressed(evt);
            }
        });
        getContentPane().add(cadastroCodigo1);
        cadastroCodigo1.setBounds(310, 140, 160, 30);

        varCusto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        varCusto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                varCustoKeyPressed(evt);
            }
        });
        getContentPane().add(varCusto);
        varCusto.setBounds(30, 320, 120, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/APAGAR.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(400, 530, 80, 70);

        varVenda.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        varVenda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                varVendaKeyPressed(evt);
            }
        });
        getContentPane().add(varVenda);
        varVenda.setBounds(310, 320, 120, 30);

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("LOCALIZAÇÃO");
        getContentPane().add(jLabel23);
        jLabel23.setBounds(30, 200, 150, 17);

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 0, 0));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("*");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(70, 100, 30, 40);

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 0, 0));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("*");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(370, 100, 30, 40);

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 0, 0));
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setText("*");
        getContentPane().add(jLabel26);
        jLabel26.setBounds(570, 100, 30, 40);

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 0, 0));
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setText("*");
        getContentPane().add(jLabel27);
        jLabel27.setBounds(130, 190, 40, 40);

        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 0, 0));
        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel31.setText("*");
        getContentPane().add(jLabel31);
        jLabel31.setBounds(360, 190, 30, 40);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 0, 0));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("*");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(710, 190, 30, 40);

        jLabel32.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 0, 0));
        jLabel32.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel32.setText("*");
        getContentPane().add(jLabel32);
        jLabel32.setBounds(80, 280, 30, 40);

        jLabel33.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 0, 0));
        jLabel33.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel33.setText("*");
        getContentPane().add(jLabel33);
        jLabel33.setBounds(440, 280, 30, 40);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 21)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("EDITAR INFORMAÇÕES");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(250, 10, 320, 60);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/atua.png"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(140, 530, 80, 70);

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("CUSTO");
        jLabel24.setPreferredSize(null);
        getContentPane().add(jLabel24);
        jLabel24.setBounds(20, 290, 70, 17);

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("PREÇO DE VENDA");
        getContentPane().add(jLabel25);
        jLabel25.setBounds(310, 290, 140, 17);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundo preto.png"))); // NOI18N
        jLabel1.setMinimumSize(new java.awt.Dimension(1057, 340));
        jLabel1.setPreferredSize(new java.awt.Dimension(1057, 350));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 4, 750, 77);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/FUNDO AMARELO.jpg"))); // NOI18N
        getContentPane().add(jLabel11);
        jLabel11.setBounds(0, -331, 760, 430);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/RS.png"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(190, 10, 570, 530);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/RS.png"))); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(320, 340, 570, 530);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/RS.png"))); // NOI18N
        getContentPane().add(jLabel9);
        jLabel9.setBounds(-20, 450, 570, 530);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/RS.png"))); // NOI18N
        getContentPane().add(jLabel10);
        jLabel10.setBounds(0, 0, 570, 530);

        mostrarNivel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        mostrarNivel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mostrarNivel.setText("5");
        getContentPane().add(mostrarNivel);
        mostrarNivel.setBounds(520, 130, 50, 70);

        acessoUser.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        acessoUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        acessoUser.setText("ADMIN");
        getContentPane().add(acessoUser);
        acessoUser.setBounds(520, 220, 70, 60);

        setSize(new java.awt.Dimension(750, 654));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    private void alterarComCodigo(){
        String sql = "update tb_pecas_es2 set NOME=?,CAIXA=?,LOCALIZAÇÃO=?,MARCA=?,QUANTIDADE=?,CUSTO=?,PREÇO=?,OBSERVAÇÕES=?,LUCRO=? where CÓDIGO=?";
        try {
            pst=conexao.prepareStatement(sql);
            pst.setString(1,cadastroNome.getText());
            pst.setString(2,editarCaixa.getText());
            pst.setString(3, editarLocalizacao.getText());
            pst.setString(4,cadastroMarca.getText());
            pst.setInt(5,Integer.parseInt(cadastroQuantidadeDisponivel.getText()));
            pst.setString(6, varCusto.getText().replace(",", "."));
            pst.setString(7, varVenda.getText().replace(",", "."));
            pst.setString(8,cadastroObservacoes.getText());
            float lucro=(Float.parseFloat(varVenda.getText().replace(",","."))-Float.parseFloat(varCusto.getText().replace(",",".")));
            String aux=df.format(lucro);
            pst.setString(9, aux);
            pst.setString(10,cadastroCodigo1.getText());
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null,"ITEM ATUALIZADO COM SUCESSO");
            TodosOsItensCadastrados usuario = new TodosOsItensCadastrados();
            usuario.setVisible(true);
            usuario.nomePeca.setText(cadastroNome.getText());
            usuario.codigoCadastrado.setText(cadastroCodigo1.getText());
            usuario.marcaCadastrada.setText(cadastroMarca.getText());
            usuario.quantCadastrada.setText(cadastroQuantidadeDisponivel.getText());
            usuario.custoCadastrado.setText(varCusto.getText());
            usuario.precoDeVenda.setText(varVenda.getText());
            usuario.lucroCadastrado.setText(aux);
            usuario.caixaLocalizada.setText(editarCaixa.getText());
            usuario.localizacaoCadastrada.setText(editarLocalizacao.getText());
            usuario.cadastroObservacoes.setText(cadastroObservacoes.getText());
            usuario.mostrarNivel.setText(mostrarNivel.getText());
            usuario.acessoUser.setText(acessoUser.getText());
            this.dispose();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }
    }
    private void consultarES(){
        String sqlnome = "select * from tb_pecas_es2 where CÓDIGO=?";
        try {
            pst = conexao.prepareStatement(sqlnome);
            pst.setString(1,cadastroCodigo1.getText());
            rs = pst.executeQuery();
            if (rs.next()) {
                varCusto.setText(rs.getString(7).replace(".",","));
                varVenda.setText(rs.getString(8).replace(".",","));
                cadastroObservacoes.setText(rs.getString(9));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }
    }
    private void remover(){
        int confirma = JOptionPane.showConfirmDialog(null, "TEM CERTEZA QUE DESEJA APAGAR ESSE ITEM?","ATENÇÃO",JOptionPane.YES_NO_OPTION);
        if(confirma==JOptionPane.YES_OPTION){
            String sql = "delete from tb_pecas_es2 where CÓDIGO = ?";
            try {
                pst=conexao.prepareStatement(sql);
                pst.setString(1, cadastroCodigo1.getText());
                int apagado = pst.executeUpdate();
                if(apagado>0){
                    JOptionPane.showMessageDialog(null,"ITEM APAGADO COM SUCESSO");
                    this.dispose();
                }
                else{
                    JOptionPane.showMessageDialog(null,"ITEM NÃO EXISTE NO BANCO DE DADOS");
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }
    private void botAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botAtualizarActionPerformed
        if(cadastroCodigo1.getText().equals("")||cadastroNome.getText().equals("")||varCusto.getText().equals("")||varVenda.getText().equals("")||editarCaixa.getText().equals("")||editarLocalizacao.getText().equals("")||cadastroMarca.getText().equals("")||cadastroQuantidadeDisponivel.getText().equals("")){
            JOptionPane.showMessageDialog(null, "POR FAVOR PREENCHA TODOS OS CAMPOS");
        }
        else{
            alterarComCodigo();
        }
    }//GEN-LAST:event_botAtualizarActionPerformed

    private void botApagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botApagarActionPerformed
        if(nivel==2){
            JOptionPane.showMessageDialog(null, "VOCÊ NÃO TEM ACESSO A ESSE MÓDULO!");
        }
        else{ 
            remover();
        }
    }//GEN-LAST:event_botApagarActionPerformed

    private void cadastroNomeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cadastroNomeKeyPressed
        if(evt.getKeyCode() == evt.VK_ENTER){
            cadastroCodigo1.requestFocus();
        }
    }//GEN-LAST:event_cadastroNomeKeyPressed

    private void cadastroCodigo1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cadastroCodigo1KeyPressed
        if(evt.getKeyCode() == evt.VK_ENTER){
            editarCaixa.requestFocus();
        }
    }//GEN-LAST:event_cadastroCodigo1KeyPressed

    private void editarCaixaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_editarCaixaKeyPressed
        if(evt.getKeyCode() == evt.VK_ENTER){
            editarLocalizacao.requestFocus();
        }
    }//GEN-LAST:event_editarCaixaKeyPressed

    private void editarLocalizacaoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_editarLocalizacaoKeyPressed
        if(evt.getKeyCode() == evt.VK_ENTER){
            cadastroMarca.requestFocus();
        }
    }//GEN-LAST:event_editarLocalizacaoKeyPressed

    private void cadastroMarcaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cadastroMarcaKeyPressed
        if(evt.getKeyCode() == evt.VK_ENTER){
            cadastroQuantidadeDisponivel.requestFocus();
        }
    }//GEN-LAST:event_cadastroMarcaKeyPressed

    private void cadastroQuantidadeDisponivelKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cadastroQuantidadeDisponivelKeyPressed
        if(evt.getKeyCode() == evt.VK_ENTER){
            varCusto.requestFocus();
        }
    }//GEN-LAST:event_cadastroQuantidadeDisponivelKeyPressed

    private void varCustoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_varCustoKeyPressed
        if(evt.getKeyCode() == evt.VK_ENTER){
            varVenda.requestFocus();
        }
    }//GEN-LAST:event_varCustoKeyPressed

    private void varVendaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_varVendaKeyPressed
        if(evt.getKeyCode() == evt.VK_ENTER){
            cadastroObservacoes.requestFocus();
        }
    }//GEN-LAST:event_varVendaKeyPressed

    private void cadastroObservacoesKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cadastroObservacoesKeyPressed
        
    }//GEN-LAST:event_cadastroObservacoesKeyPressed

    private void botAtualizarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_botAtualizarKeyPressed
        if(evt.getKeyCode() == evt.VK_ENTER){
            if(cadastroCodigo1.getText().equals("")||cadastroNome.getText().equals("")||varCusto.getText().equals("")||varVenda.getText().equals("")||editarCaixa.getText().equals("")||editarLocalizacao.getText().equals("")||cadastroMarca.getText().equals("")||cadastroQuantidadeDisponivel.getText().equals("")){
                JOptionPane.showMessageDialog(null, "POR FAVOR PREENCHA TODOS OS CAMPOS");
            }
            else{
                alterarComCodigo();
            }
        }
    }//GEN-LAST:event_botAtualizarKeyPressed

    private void botApagarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_botApagarKeyPressed
        if(nivel==2){
            JOptionPane.showMessageDialog(null, "VOCÊ NÃO TEM ACESSO A ESSE MÓDULO!");
        }
        else if(evt.getKeyCode() == evt.VK_ENTER){
            remover();
        }
    }//GEN-LAST:event_botApagarKeyPressed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        nivel=Integer.parseInt(mostrarNivel.getText());
        if(nivel==2){
            varApagar1.setVisible(true);
            varApagar2.setVisible(true);
        }
        cadastroObservacoes.setWrapStyleWord(true);
        consultarES();
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EstoqueAtualizarItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EstoqueAtualizarItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EstoqueAtualizarItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EstoqueAtualizarItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EstoqueAtualizarItem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel acessoUser;
    private javax.swing.JButton botApagar;
    private javax.swing.JButton botAtualizar;
    public static javax.swing.JTextField cadastroCodigo1;
    public static javax.swing.JTextField cadastroMarca;
    public static javax.swing.JTextField cadastroNome;
    public static javax.swing.JTextArea cadastroObservacoes;
    public static javax.swing.JTextField cadastroQuantidadeDisponivel;
    public static javax.swing.JTextField editarCaixa;
    public static javax.swing.JTextField editarLocalizacao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JLabel mostrarNivel;
    public javax.swing.JLabel varApagar1;
    public javax.swing.JLabel varApagar2;
    public static javax.swing.JTextField varCusto;
    public static javax.swing.JTextField varVenda;
    // End of variables declaration//GEN-END:variables
}
