/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mklivre;

import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;
import javax.swing.JOptionPane;
import java.sql.*;
import controle.ModuloConexao;
/**
 *
 * @author willi
 */
public class EstoqueBaixarDoEstoque extends javax.swing.JFrame {
    Connection conexao = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    /**
     * Creates new form BaixarDoEstoque
     */
    public EstoqueBaixarDoEstoque() {
        initComponents();
        URL caminhoIcone = getClass().getResource("/mklivre/icone/icone2.png");
        Image iconeTitulo = Toolkit.getDefaultToolkit().getImage(caminhoIcone);
        this.setIconImage(iconeTitulo);
        mensagem.setVisible(false);
        conexao = ModuloConexao.conector();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSpinner1 = new javax.swing.JSpinner();
        botaoEntrarIniciall3 = new javax.swing.JButton();
        botaoEntrarIniciall2 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        mensagem = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        mostrarNivel = new javax.swing.JLabel();
        acessoUser = new javax.swing.JLabel();
        codigoCadastrado = new javax.swing.JTextField();
        quantCadastrada = new javax.swing.JLabel();
        quantMinimo = new javax.swing.JLabel();
        quantRecomendada = new javax.swing.JLabel();
        requisicaoAutomatica = new javax.swing.JLabel();
        aguardando = new javax.swing.JLabel();
        qnt_chegou = new javax.swing.JLabel();
        chegar = new javax.swing.JLabel();
        automatico = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("BAIXAR ITEM");
        setMinimumSize(new java.awt.Dimension(447, 338));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(null);

        jSpinner1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jSpinner1.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        jSpinner1.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                jSpinner1CaretPositionChanged(evt);
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        jSpinner1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jSpinner1KeyPressed(evt);
            }
        });
        getContentPane().add(jSpinner1);
        jSpinner1.setBounds(50, 140, 90, 30);

        botaoEntrarIniciall3.setBackground(new java.awt.Color(0, 0, 0));
        botaoEntrarIniciall3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        botaoEntrarIniciall3.setForeground(new java.awt.Color(255, 255, 255));
        botaoEntrarIniciall3.setText("ADICIONAR");
        botaoEntrarIniciall3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoEntrarIniciall3ActionPerformed(evt);
            }
        });
        botaoEntrarIniciall3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                botaoEntrarIniciall3KeyPressed(evt);
            }
        });
        getContentPane().add(botaoEntrarIniciall3);
        botaoEntrarIniciall3.setBounds(50, 270, 160, 40);

        botaoEntrarIniciall2.setBackground(new java.awt.Color(0, 0, 0));
        botaoEntrarIniciall2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        botaoEntrarIniciall2.setForeground(new java.awt.Color(255, 255, 255));
        botaoEntrarIniciall2.setText("BAIXAR");
        botaoEntrarIniciall2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoEntrarIniciall2ActionPerformed(evt);
            }
        });
        botaoEntrarIniciall2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                botaoEntrarIniciall2KeyPressed(evt);
            }
        });
        getContentPane().add(botaoEntrarIniciall2);
        botaoEntrarIniciall2.setBounds(50, 220, 160, 40);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 21)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("BAIXAR ITENS");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(220, 10, 210, 60);

        mensagem.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        mensagem.setForeground(new java.awt.Color(255, 0, 0));
        mensagem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mensagem.setText("O ITEM POSSUI UMA QUANTIDADE ABAIXO DA RECOMENDADA");
        getContentPane().add(mensagem);
        mensagem.setBounds(0, 320, 530, 20);

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Sem título.png"))); // NOI18N
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 0, 150, 80);

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("QUANTIDADE QUE DESEJA");
        getContentPane().add(jLabel20);
        jLabel20.setBounds(50, 110, 400, 20);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundo preto.png"))); // NOI18N
        jLabel1.setMinimumSize(new java.awt.Dimension(1057, 340));
        jLabel1.setPreferredSize(new java.awt.Dimension(1057, 350));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 4, 680, 77);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/FUNDO AMARELO.jpg"))); // NOI18N
        getContentPane().add(jLabel11);
        jLabel11.setBounds(0, -331, 620, 430);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/RS.png"))); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(280, 50, 570, 530);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/RS.png"))); // NOI18N
        getContentPane().add(jLabel10);
        jLabel10.setBounds(-30, 0, 390, 520);

        mostrarNivel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        mostrarNivel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mostrarNivel.setText("5");
        getContentPane().add(mostrarNivel);
        mostrarNivel.setBounds(520, 130, 50, 70);

        acessoUser.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        acessoUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        acessoUser.setText("ADMIN");
        getContentPane().add(acessoUser);
        acessoUser.setBounds(520, 220, 70, 60);

        codigoCadastrado.setEditable(false);
        codigoCadastrado.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        codigoCadastrado.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(codigoCadastrado);
        codigoCadastrado.setBounds(240, 140, 140, 50);

        quantCadastrada.setForeground(new java.awt.Color(255, 255, 255));
        quantCadastrada.setText("jLabel2");
        getContentPane().add(quantCadastrada);
        quantCadastrada.setBounds(390, 140, 34, 14);

        quantMinimo.setText("jLabel2");
        getContentPane().add(quantMinimo);
        quantMinimo.setBounds(380, 210, 34, 14);

        quantRecomendada.setText("jLabel2");
        getContentPane().add(quantRecomendada);
        quantRecomendada.setBounds(440, 180, 34, 14);

        requisicaoAutomatica.setText("jLabel2");
        getContentPane().add(requisicaoAutomatica);
        requisicaoAutomatica.setBounds(440, 150, 34, 14);

        aguardando.setText("jLabel2");
        getContentPane().add(aguardando);
        aguardando.setBounds(420, 160, 34, 14);

        qnt_chegou.setText("jLabel2");
        getContentPane().add(qnt_chegou);
        qnt_chegou.setBounds(420, 100, 34, 14);

        chegar.setText("jLabel2");
        getContentPane().add(chegar);
        chegar.setBounds(290, 130, 34, 14);

        automatico.setText("jLabel2");
        getContentPane().add(automatico);
        automatico.setBounds(370, 190, 34, 14);

        setSize(new java.awt.Dimension(540, 390));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    private void pegar(){
        String sqlnome = "select * from tb_pecas_ml2 where CÓDIGO=?";
        try {
            pst = conexao.prepareStatement(sqlnome);
            pst.setString(1,codigoCadastrado.getText());
            rs = pst.executeQuery();
            if (rs.next()) {
                quantCadastrada.setText(rs.getString(7));
                quantMinimo.setText(rs.getString(8));
                quantRecomendada.setText(rs.getString(9));
                requisicaoAutomatica.setText(rs.getString(17));
                aguardando.setText(rs.getString(19));
                chegar.setText(rs.getString(20));
                int a=Integer.parseInt(quantCadastrada.getText());
                if((a==Integer.parseInt(quantMinimo.getText())||a>Integer.parseInt(quantMinimo.getText()))&&(a==Integer.parseInt(quantRecomendada.getText())||a>Integer.parseInt(quantRecomendada.getText()))){
                    mensagem.setVisible(false);
                }
                else if (a==Integer.parseInt(quantMinimo.getText())||a==Integer.parseInt(quantRecomendada.getText())){
                    
                }
                else if(a<Integer.parseInt(quantMinimo.getText())){
                    mensagem.setVisible(true);
                    mensagem.setText("O ITEM POSSUI UMA QUANTIDADE ABAIXO DA QUANTIDADE MINIMA!");
                }
                else if(a<Integer.parseInt(quantRecomendada.getText())){
                    mensagem.setVisible(true);
                    mensagem.setText("O ITEM POSSUI UMA QUANTIDADE ABAIXO DA RECOMENDADA!");
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }
    }
    private void baixar(){
        String sql = "update tb_pecas_ml2 set QUANTIDADE=? where CÓDIGO=?";
        try {
            pst=conexao.prepareStatement(sql);
            int a=Integer.parseInt(quantCadastrada.getText())-Integer.parseInt(jSpinner1.getValue().toString());
            pst.setInt(1,a);
            pst.setString(2,codigoCadastrado.getText());
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null,"ITEM BAIXADO COM SUCESSO");
            if((a==Integer.parseInt(quantMinimo.getText())||a>Integer.parseInt(quantMinimo.getText()))&&(a==Integer.parseInt(quantRecomendada.getText())||a>Integer.parseInt(quantRecomendada.getText()))){
                mensagem.setVisible(false);
            }
            else if (a==Integer.parseInt(quantMinimo.getText())||a==Integer.parseInt(quantRecomendada.getText())){
                    
            }
            else if(a<Integer.parseInt(quantMinimo.getText())){
                mensagem.setVisible(true);
                mensagem.setText("O ITEM POSSUI UMA QUANTIDADE ABAIXO DA QUANTIDADE MINIMA!");
            }
            else if(a<Integer.parseInt(quantRecomendada.getText())){
                mensagem.setVisible(true);
                mensagem.setText("O ITEM POSSUI UMA QUANTIDADE ABAIXO DA RECOMENDADA!");
                if(requisicaoAutomatica.getText().equals("SIM")){
                    String sql2 = "update tb_pecas_ml2 set STATUS_DA_REQUISIÇÃO=? where CÓDIGO=?";
                    pst=conexao.prepareStatement(sql2);
                    pst.setString(2,codigoCadastrado.getText());
                    pst.setString(1,"SIM");
                    pst.executeUpdate();
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }
    }
    private void adicionar(){
        String sql = "update tb_pecas_ml2 set QUANTIDADE=? where CÓDIGO=?";
        try {
            pst=conexao.prepareStatement(sql);
            int a=Integer.parseInt(quantCadastrada.getText())+Integer.parseInt(jSpinner1.getValue().toString());
            pst.setInt(1,a);
            pst.setString(2,codigoCadastrado.getText());
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null,"ITEM ADICIONADO COM SUCESSO");
            if((a==Integer.parseInt(quantMinimo.getText())||a>Integer.parseInt(quantMinimo.getText()))&&(a==Integer.parseInt(quantRecomendada.getText())||a>Integer.parseInt(quantRecomendada.getText()))){
                mensagem.setVisible(false);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }
    }
    private void botaoEntrarIniciall2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoEntrarIniciall2ActionPerformed
        int confirma = JOptionPane.showConfirmDialog(null, "TEM CERTEZA QUE DESEJA DAR BAIXA NA QUANTIDADE DESSE ITEM?","ATENÇÃO",JOptionPane.YES_NO_OPTION);
        if(confirma==JOptionPane.YES_OPTION){
            pegar();
            baixar();
        }
    }//GEN-LAST:event_botaoEntrarIniciall2ActionPerformed

    private void botaoEntrarIniciall3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoEntrarIniciall3ActionPerformed
        int confirma = JOptionPane.showConfirmDialog(null, "TEM CERTEZA QUE DESEJA ADICIONAR ESSA QUANTIDADE A ESSE ITEM?","ATENÇÃO",JOptionPane.YES_NO_OPTION);
        if(confirma==JOptionPane.YES_OPTION){
            pegar();
            adicionar();
        }
    }//GEN-LAST:event_botaoEntrarIniciall3ActionPerformed

    private void jSpinner1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jSpinner1KeyPressed
        if(evt.getKeyCode() == evt.VK_ENTER){
            int confirma = JOptionPane.showConfirmDialog(null, "TEM CERTEZA QUE DESEJA DAR BAIXA NA QUANTIDADE DESSE ITEM?","ATENÇÃO",JOptionPane.YES_NO_OPTION);
            if(confirma==JOptionPane.YES_OPTION){
                pegar();
                baixar();
            }
        }
    }//GEN-LAST:event_jSpinner1KeyPressed

    private void botaoEntrarIniciall2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_botaoEntrarIniciall2KeyPressed
        if(evt.getKeyCode() == evt.VK_ENTER){
            int confirma = JOptionPane.showConfirmDialog(null, "TEM CERTEZA QUE DESEJA DAR BAIXA NA QUANTIDADE DESSE ITEM?","ATENÇÃO",JOptionPane.YES_NO_OPTION);
            if(confirma==JOptionPane.YES_OPTION){
                pegar();
                baixar();
            }
        }
    }//GEN-LAST:event_botaoEntrarIniciall2KeyPressed

    private void botaoEntrarIniciall3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_botaoEntrarIniciall3KeyPressed
        if(evt.getKeyCode() == evt.VK_ENTER){
            int confirma = JOptionPane.showConfirmDialog(null, "TEM CERTEZA QUE DESEJA ADICIONAR ESSA QUANTIDADE A ESSE ITEM?","ATENÇÃO",JOptionPane.YES_NO_OPTION);
            if(confirma==JOptionPane.YES_OPTION){
                pegar();
                adicionar();
            }
        }
    }//GEN-LAST:event_botaoEntrarIniciall3KeyPressed

    private void jSpinner1CaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jSpinner1CaretPositionChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jSpinner1CaretPositionChanged

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        pegar();
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EstoqueBaixarDoEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EstoqueBaixarDoEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EstoqueBaixarDoEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EstoqueBaixarDoEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EstoqueBaixarDoEstoque().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel acessoUser;
    private javax.swing.JLabel aguardando;
    private javax.swing.JLabel automatico;
    private javax.swing.JButton botaoEntrarIniciall2;
    private javax.swing.JButton botaoEntrarIniciall3;
    private javax.swing.JLabel chegar;
    public static javax.swing.JTextField codigoCadastrado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JLabel mensagem;
    public static javax.swing.JLabel mostrarNivel;
    private javax.swing.JLabel qnt_chegou;
    private javax.swing.JLabel quantCadastrada;
    private javax.swing.JLabel quantMinimo;
    private javax.swing.JLabel quantRecomendada;
    private javax.swing.JLabel requisicaoAutomatica;
    // End of variables declaration//GEN-END:variables
}
