/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mklivre;

import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;
import java.sql.*;
import controle.ModuloConexao;
import javax.swing.JOptionPane;
/**
 *
 * @author willi
 */
public class ExecucoesDosMecanicos extends javax.swing.JFrame {
    Connection conexao = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    /**
     * Creates new form ExecucoesDosMecanicos
     */
    public ExecucoesDosMecanicos() {
        initComponents();
        URL caminhoIcone = getClass().getResource("/mklivre/icone/icone2.png");
        Image iconeTitulo = Toolkit.getDefaultToolkit().getImage(caminhoIcone);
        this.setIconImage(iconeTitulo);
        conexao = ModuloConexao.conector();
        historico.setWrapStyleWord(true);
    }
    int nivel;
    String acesso="admin",nome;
    private void remover(){
        int confirma = JOptionPane.showConfirmDialog(null, "TEM CERTEZA QUE DESEJA APAGAR ESSA EXECUÇÃO?","ATENÇÃO",JOptionPane.YES_NO_OPTION);
        if(confirma==JOptionPane.YES_OPTION){
            String sql = "delete from exec_of2 where os_aux=?";
            try {
                pst=conexao.prepareStatement(sql);
                pst.setString(1, campoOS.getText());
                int apagado = pst.executeUpdate();
                if(apagado>0){
                    JOptionPane.showMessageDialog(null,"EXECUÇÃO APAGADA COM SUCESSO");
                    this.dispose();
                }
                else{
                    JOptionPane.showMessageDialog(null,"A EXECUÇÃO NÃO EXISTE NO BANCO DE DADOS");
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }
    private void historico(){
        String sqlnome = "select * from exec_of2 where os_aux=?";
        try {
            pst = conexao.prepareStatement(sqlnome);
            pst.setString(1,campoOS.getText());
            rs = pst.executeQuery();
            if (rs.next()) {
                historico.setText(rs.getString(17));
                campoObs.setText(rs.getString(6));
                aparelho.setText(rs.getString("APARELHO"));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }
    }
    private void consultar(){
        String sqlnome = "select * from exec_of2 where os_aux=?";
        try {
            pst = conexao.prepareStatement(sqlnome);
            pst.setString(1,campoOS.getText());
            rs = pst.executeQuery();
            if (rs.next()) {
                EditarExecucoes usuario = new EditarExecucoes();
                usuario.setVisible(true);
                usuario.mostrarNivel.setText(mostrarNivel.getText());
                usuario.acessoUser.setText(acessoUser.getText());
                usuario.cadastroOS.setText(campoOS.getText());
                usuario.servicoDaOs.setSelectedItem(rs.getString(2));
                usuario.cadastroObservacoes.setText(rs.getString(6));
                usuario.tipoDaOS.setSelectedItem(rs.getString(7));
                usuario.campoMecanicos.setSelectedItem(rs.getString(8));
                usuario.horaInicial.setValue(Integer.parseInt(rs.getString(10)));
                usuario.minutoInicial.setValue(Integer.parseInt(rs.getString(11)));
                usuario.horaFinal.setValue(Integer.parseInt(rs.getString(12)));
                usuario.minutoFinal.setValue(Integer.parseInt(rs.getString(13)));
                usuario.dataDia.setValue(Integer.parseInt(rs.getString(14)));
                usuario.dataMes.setValue(Integer.parseInt(rs.getString(15)));
                usuario.dataAno.setValue(Integer.parseInt(rs.getString(16)));
                usuario.historico.setText(rs.getString(17));
                this.dispose();
            }
            else{
                JOptionPane.showMessageDialog(null,"EXECUÇÃO NÃO LOCALIZADA NO BANCO DE DADOS!");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        aparelho = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        pesquisar = new javax.swing.JButton();
        novo = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        historico = new javax.swing.JTextArea();
        jLabel23 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        campoHoraInicial = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        campoObs = new javax.swing.JTextArea();
        campoServico = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        apagar = new javax.swing.JButton();
        editar = new javax.swing.JButton();
        jLabel35 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        campoData = new javax.swing.JTextField();
        campoHoraFinal = new javax.swing.JTextField();
        campoOS = new javax.swing.JTextField();
        campoTipoDaOs = new javax.swing.JTextField();
        campoDuracao = new javax.swing.JTextField();
        campoMecanico = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        acessoUser = new javax.swing.JLabel();
        mostrarNivel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("EXECUÇÃO");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(null);

        aparelho.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        aparelho.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        aparelho.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                aparelhoKeyPressed(evt);
            }
        });
        getContentPane().add(aparelho);
        aparelho.setBounds(20, 420, 140, 30);

        jLabel38.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(255, 255, 255));
        jLabel38.setText("APARELHO");
        getContentPane().add(jLabel38);
        jLabel38.setBounds(20, 390, 150, 17);

        pesquisar.setBackground(new java.awt.Color(0, 0, 0));
        pesquisar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        pesquisar.setForeground(new java.awt.Color(255, 255, 255));
        pesquisar.setText("PESQUISAR");
        pesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesquisarActionPerformed(evt);
            }
        });
        pesquisar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pesquisarKeyPressed(evt);
            }
        });
        getContentPane().add(pesquisar);
        pesquisar.setBounds(20, 520, 140, 40);

        novo.setBackground(new java.awt.Color(0, 0, 0));
        novo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        novo.setForeground(new java.awt.Color(255, 255, 255));
        novo.setText("NOVO");
        novo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novoActionPerformed(evt);
            }
        });
        novo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                novoKeyPressed(evt);
            }
        });
        getContentPane().add(novo);
        novo.setBounds(20, 470, 140, 40);

        historico.setEditable(false);
        historico.setColumns(20);
        historico.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        historico.setRows(5);
        historico.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                historicoKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(historico);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(440, 140, 300, 120);

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("HISTÓRICO");
        getContentPane().add(jLabel23);
        jLabel23.setBounds(440, 90, 120, 50);

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("ORDEM DE SERVIÇO");
        getContentPane().add(jLabel19);
        jLabel19.setBounds(20, 110, 160, 17);

        campoHoraInicial.setEditable(false);
        campoHoraInicial.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        campoHoraInicial.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        campoHoraInicial.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                campoHoraInicialKeyPressed(evt);
            }
        });
        getContentPane().add(campoHoraInicial);
        campoHoraInicial.setBounds(20, 210, 140, 30);

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("OBSERVAÇÕES");
        getContentPane().add(jLabel21);
        jLabel21.setBounds(440, 260, 120, 50);

        campoObs.setEditable(false);
        campoObs.setColumns(20);
        campoObs.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        campoObs.setRows(5);
        campoObs.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                campoObsKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(campoObs);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(440, 310, 300, 250);

        campoServico.setEditable(false);
        campoServico.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        campoServico.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        campoServico.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                campoServicoKeyPressed(evt);
            }
        });
        getContentPane().add(campoServico);
        campoServico.setBounds(250, 140, 140, 30);

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Sem título.png"))); // NOI18N
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel6);
        jLabel6.setBounds(-4, 0, 150, 80);

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("HORA FINAL");
        getContentPane().add(jLabel22);
        jLabel22.setBounds(250, 180, 90, 17);

        jLabel36.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(255, 255, 255));
        jLabel36.setText("DURAÇÃO");
        getContentPane().add(jLabel36);
        jLabel36.setBounds(20, 250, 100, 17);

        apagar.setBackground(new java.awt.Color(0, 0, 0));
        apagar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        apagar.setForeground(new java.awt.Color(255, 255, 255));
        apagar.setText("APAGAR");
        apagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apagarActionPerformed(evt);
            }
        });
        apagar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                apagarKeyPressed(evt);
            }
        });
        getContentPane().add(apagar);
        apagar.setBounds(250, 520, 140, 40);

        editar.setBackground(new java.awt.Color(0, 0, 0));
        editar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        editar.setForeground(new java.awt.Color(255, 255, 255));
        editar.setText("EDITAR");
        editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarActionPerformed(evt);
            }
        });
        editar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                editarKeyPressed(evt);
            }
        });
        getContentPane().add(editar);
        editar.setBounds(250, 470, 140, 40);

        jLabel35.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(255, 255, 255));
        jLabel35.setText("TIPO DA OS");
        getContentPane().add(jLabel35);
        jLabel35.setBounds(20, 320, 150, 17);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 21)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("EXECUÇÕES");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(260, 10, 320, 60);

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("SERVIÇO");
        getContentPane().add(jLabel30);
        jLabel30.setBounds(250, 110, 150, 17);

        jLabel34.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setText("DATA");
        getContentPane().add(jLabel34);
        jLabel34.setBounds(250, 250, 150, 17);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundo preto.png"))); // NOI18N
        jLabel12.setMinimumSize(new java.awt.Dimension(1057, 340));
        jLabel12.setPreferredSize(new java.awt.Dimension(1057, 350));
        getContentPane().add(jLabel12);
        jLabel12.setBounds(-80, 4, 760, 77);

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("HORA INICIAL");
        getContentPane().add(jLabel29);
        jLabel29.setBounds(20, 180, 150, 17);

        campoData.setEditable(false);
        campoData.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        campoData.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        campoData.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                campoDataKeyPressed(evt);
            }
        });
        getContentPane().add(campoData);
        campoData.setBounds(250, 280, 140, 30);

        campoHoraFinal.setEditable(false);
        campoHoraFinal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        campoHoraFinal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        campoHoraFinal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                campoHoraFinalKeyPressed(evt);
            }
        });
        getContentPane().add(campoHoraFinal);
        campoHoraFinal.setBounds(250, 210, 140, 30);

        campoOS.setEditable(false);
        campoOS.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        campoOS.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        campoOS.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                campoOSKeyPressed(evt);
            }
        });
        getContentPane().add(campoOS);
        campoOS.setBounds(20, 140, 140, 30);

        campoTipoDaOs.setEditable(false);
        campoTipoDaOs.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        campoTipoDaOs.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        campoTipoDaOs.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                campoTipoDaOsKeyPressed(evt);
            }
        });
        getContentPane().add(campoTipoDaOs);
        campoTipoDaOs.setBounds(20, 350, 140, 30);

        campoDuracao.setEditable(false);
        campoDuracao.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        campoDuracao.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        campoDuracao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                campoDuracaoKeyPressed(evt);
            }
        });
        getContentPane().add(campoDuracao);
        campoDuracao.setBounds(20, 280, 140, 30);

        campoMecanico.setEditable(false);
        campoMecanico.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        campoMecanico.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        campoMecanico.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                campoMecanicoKeyPressed(evt);
            }
        });
        getContentPane().add(campoMecanico);
        campoMecanico.setBounds(250, 350, 140, 30);

        jLabel37.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(255, 255, 255));
        jLabel37.setText("MECÂNICO");
        getContentPane().add(jLabel37);
        jLabel37.setBounds(250, 320, 100, 17);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundo preto.png"))); // NOI18N
        jLabel1.setMinimumSize(new java.awt.Dimension(1057, 340));
        jLabel1.setPreferredSize(new java.awt.Dimension(1057, 350));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(140, 4, 760, 77);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/FUNDO AMARELO.jpg"))); // NOI18N
        getContentPane().add(jLabel11);
        jLabel11.setBounds(0, -331, 820, 430);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/RS.png"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(250, 10, 640, 530);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/RS.png"))); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(320, 340, 570, 530);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/RS.png"))); // NOI18N
        getContentPane().add(jLabel9);
        jLabel9.setBounds(-20, 450, 570, 530);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/RS.png"))); // NOI18N
        getContentPane().add(jLabel10);
        jLabel10.setBounds(0, 0, 570, 530);

        acessoUser.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        acessoUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        acessoUser.setText("ADMIN");
        getContentPane().add(acessoUser);
        acessoUser.setBounds(520, 220, 70, 60);

        mostrarNivel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        mostrarNivel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mostrarNivel.setText("5");
        getContentPane().add(mostrarNivel);
        mostrarNivel.setBounds(520, 130, 50, 70);

        setSize(new java.awt.Dimension(761, 605));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void campoHoraInicialKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoHoraInicialKeyPressed
        
    }//GEN-LAST:event_campoHoraInicialKeyPressed

    private void campoObsKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoObsKeyPressed
        
    }//GEN-LAST:event_campoObsKeyPressed

    private void editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarActionPerformed
        if(acesso.equals("OF")||nivel==5){
            consultar();
        }
        else{
            JOptionPane.showMessageDialog(null, "VOCÊ NÃO TEM ACESSO A ESSE MÓDULO!");
        }
    }//GEN-LAST:event_editarActionPerformed

    private void editarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_editarKeyPressed
        if(evt.getKeyCode() == evt.VK_ENTER){
            if(acesso.equals("OF")||nivel==5){
                consultar();
            }
            else{
                JOptionPane.showMessageDialog(null, "VOCÊ NÃO TEM ACESSO A ESSE MÓDULO!");
            }
        }
    }//GEN-LAST:event_editarKeyPressed

    private void campoDataKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoDataKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoDataKeyPressed

    private void campoHoraFinalKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoHoraFinalKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoHoraFinalKeyPressed

    private void campoOSKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoOSKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoOSKeyPressed

    private void campoServicoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoServicoKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoServicoKeyPressed

    private void campoTipoDaOsKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoTipoDaOsKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoTipoDaOsKeyPressed

    private void campoDuracaoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoDuracaoKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoDuracaoKeyPressed

    private void campoMecanicoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoMecanicoKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoMecanicoKeyPressed

    private void apagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apagarActionPerformed
        if(acesso.equals("OF")||nivel==5){
            remover();
        }
        else{
            JOptionPane.showMessageDialog(null, "VOCÊ NÃO TEM ACESSO A ESSE MÓDULO!");
        }
    }//GEN-LAST:event_apagarActionPerformed

    private void apagarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_apagarKeyPressed
        if(evt.getKeyCode() == evt.VK_ENTER){
            if(acesso.equals("OF")||nivel==5){
                remover();
            }
            else{
                JOptionPane.showMessageDialog(null, "VOCÊ NÃO TEM ACESSO A ESSE MÓDULO!");
            }
        }
    }//GEN-LAST:event_apagarKeyPressed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        nivel=Integer.parseInt(mostrarNivel.getText());
        acesso = acessoUser.getText();
        historico();
        campoObs.setWrapStyleWord(true);
        historico.setWrapStyleWord(true);
    }//GEN-LAST:event_formWindowActivated

    private void historicoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_historicoKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_historicoKeyPressed

    private void novoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novoActionPerformed
        RegistroExecucoes registro = new RegistroExecucoes();
        registro.setVisible(true);
        registro.mostrarNivel.setText(mostrarNivel.getText());
        registro.acessoUser.setText(acessoUser.getText());
        this.dispose();
    }//GEN-LAST:event_novoActionPerformed

    private void novoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_novoKeyPressed
        if(evt.getKeyCode() == evt.VK_ENTER){
            RegistroExecucoes registro = new RegistroExecucoes();
            registro.setVisible(true);
            registro.mostrarNivel.setText(mostrarNivel.getText());
            registro.acessoUser.setText(acessoUser.getText());
            this.dispose();
        }
    }//GEN-LAST:event_novoKeyPressed

    private void pesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesquisarActionPerformed
        CaminhoDasExecucoes localiza= new CaminhoDasExecucoes();
        localiza.setVisible(true);
        localiza.mostrarNivel.setText(mostrarNivel.getText());
        localiza.acessoUser.setText(acessoUser.getText());
        this.dispose();
    }//GEN-LAST:event_pesquisarActionPerformed

    private void pesquisarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pesquisarKeyPressed
        if(evt.getKeyCode() == evt.VK_ENTER){
            CaminhoDasExecucoes localiza= new CaminhoDasExecucoes();
            localiza.setVisible(true);
            localiza.mostrarNivel.setText(mostrarNivel.getText());
            localiza.acessoUser.setText(acessoUser.getText());
            this.dispose();
        }
    }//GEN-LAST:event_pesquisarKeyPressed

    private void aparelhoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_aparelhoKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_aparelhoKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExecucoesDosMecanicos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExecucoesDosMecanicos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExecucoesDosMecanicos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExecucoesDosMecanicos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ExecucoesDosMecanicos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel acessoUser;
    private javax.swing.JButton apagar;
    public static javax.swing.JTextField aparelho;
    public static javax.swing.JTextField campoData;
    public static javax.swing.JTextField campoDuracao;
    public static javax.swing.JTextField campoHoraFinal;
    public static javax.swing.JTextField campoHoraInicial;
    public static javax.swing.JTextField campoMecanico;
    public static javax.swing.JTextField campoOS;
    public static javax.swing.JTextArea campoObs;
    public static javax.swing.JTextField campoServico;
    public static javax.swing.JTextField campoTipoDaOs;
    private javax.swing.JButton editar;
    public static javax.swing.JTextArea historico;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public static javax.swing.JLabel mostrarNivel;
    private javax.swing.JButton novo;
    private javax.swing.JButton pesquisar;
    // End of variables declaration//GEN-END:variables
}
