/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mklivre;
import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;
import javax.swing.JOptionPane;
import java.sql.*;
import controle.ModuloConexao;
import java.io.File;
import javax.swing.JFileChooser;
/**
 *
 * @author willi
 */
public class FazerBackup extends javax.swing.JFrame {
    Connection conexao = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    /**
     * Creates new form FazerBackup
     */
    public FazerBackup() {
        initComponents();
        URL caminhoIcone = getClass().getResource("/mklivre/icone/icone2.png");
        Image iconeTitulo = Toolkit.getDefaultToolkit().getImage(caminhoIcone);
        this.setIconImage(iconeTitulo);
        conexao = ModuloConexao.conector();
        JCF_Salvar_Backup.setVisible(false);
    }
    private void backup(){
        JCF_Salvar_Backup.setVisible(true);
        try {
            String arquivo = null;
            JCF_Salvar_Backup.setVisible(true);
            int result = JCF_Salvar_Backup.showSaveDialog(null);
            if(result == JFileChooser.APPROVE_OPTION){
            arquivo = JCF_Salvar_Backup.getSelectedFile().toString().concat(".sql");
            File file = new File(arquivo); 
            if(file.exists()){
                Object[] options = { "Sim", "Não" };
                int opcao = JOptionPane.showOptionDialog(null,"ESTE ARQUIVO JÁ EXISTE. QUER SOBREESCREVER ESTE ARQUIVO?", "ATENÇÃO!!!",
                JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null,options, options[0]);
                if (opcao == JOptionPane.YES_OPTION) {                
                    Runtime bck = Runtime.getRuntime();   
                    bck.exec("C:/xampp/mysql/bin/mysqldump.exe -v -v -v --host=192.168.1.63 --user=madri --password=madrimarcelo --port=3306 --protocol=tcp --force --allow-keywords --compress  --add-drop-table --default-character-set=latin1 --hex-blob  --result-file="+arquivo+" --databases dbprometheus");  
                    JOptionPane.showMessageDialog(null, "BACKUP REALIZADO COM SUCESSO", "Tudo OK!", 1);
                    this.dispose();
                }
            }
            else{
                    Runtime bck = Runtime.getRuntime();   
                    bck.exec("C:/xampp/mysql/bin/mysqldump.exe -v -v -v --host=192.168.1.63 --user=madri --password=madrimarcelo --port=3306 --protocol=tcp --force --allow-keywords --compress  --add-drop-table --default-character-set=latin1 --hex-blob  --result-file="+arquivo+" --databases dbprometheus");  
                    JOptionPane.showMessageDialog(null, "BACKUP REALIZADO COM SUCESSO!", "Tudo OK!", 1); 
                    this.dispose();
                }
            }
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(null, e, "ERRO!", 2);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botApagarItem = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        JCF_Salvar_Backup = new javax.swing.JFileChooser();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        mostrarNivel = new javax.swing.JLabel();
        acessoUser = new javax.swing.JLabel();
        mostrarNivel1 = new javax.swing.JLabel();
        acessoUser1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("BACKUP");
        setResizable(false);
        getContentPane().setLayout(null);

        botApagarItem.setBackground(new java.awt.Color(0, 0, 0));
        botApagarItem.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        botApagarItem.setForeground(new java.awt.Color(255, 255, 255));
        botApagarItem.setText("FAZER BACKUP");
        botApagarItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botApagarItemActionPerformed(evt);
            }
        });
        botApagarItem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                botApagarItemKeyPressed(evt);
            }
        });
        getContentPane().add(botApagarItem);
        botApagarItem.setBounds(200, 120, 170, 40);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 21)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("BACKUP DO BANCO DE DADOS");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(100, 10, 500, 60);

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Sem título.png"))); // NOI18N
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 0, 150, 80);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundo preto.png"))); // NOI18N
        jLabel1.setMinimumSize(new java.awt.Dimension(1057, 340));
        jLabel1.setPreferredSize(new java.awt.Dimension(1057, 350));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 4, 1170, 77);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/FUNDO AMARELO.jpg"))); // NOI18N
        getContentPane().add(jLabel11);
        jLabel11.setBounds(0, -331, 750, 430);

        JCF_Salvar_Backup.setDialogType(javax.swing.JFileChooser.SAVE_DIALOG);
        JCF_Salvar_Backup.setDialogTitle("");
        getContentPane().add(JCF_Salvar_Backup);
        JCF_Salvar_Backup.setBounds(0, 90, 730, 326);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/RS.png"))); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(240, 30, 570, 530);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/RS.png"))); // NOI18N
        getContentPane().add(jLabel10);
        jLabel10.setBounds(-10, 0, 390, 400);

        mostrarNivel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        mostrarNivel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mostrarNivel.setText("5");
        getContentPane().add(mostrarNivel);
        mostrarNivel.setBounds(520, 130, 50, 70);

        acessoUser.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        acessoUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        acessoUser.setText("ADMIN");
        getContentPane().add(acessoUser);
        acessoUser.setBounds(520, 220, 70, 60);

        mostrarNivel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        mostrarNivel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mostrarNivel1.setText("5");
        getContentPane().add(mostrarNivel1);
        mostrarNivel1.setBounds(520, 130, 50, 70);

        acessoUser1.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        acessoUser1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        acessoUser1.setText("ADMIN");
        getContentPane().add(acessoUser1);
        acessoUser1.setBounds(520, 220, 70, 60);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/RS.png"))); // NOI18N
        getContentPane().add(jLabel9);
        jLabel9.setBounds(-40, 40, 570, 530);

        setSize(new java.awt.Dimension(578, 228));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botApagarItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botApagarItemActionPerformed
        backup();
    }//GEN-LAST:event_botApagarItemActionPerformed

    private void botApagarItemKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_botApagarItemKeyPressed
        if(evt.getKeyCode() == evt.VK_ENTER){
            backup();
        }
    }//GEN-LAST:event_botApagarItemKeyPressed

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        JJ n = new JJ();
        n.setVisible(true);
    }//GEN-LAST:event_jLabel6MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FazerBackup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FazerBackup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FazerBackup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FazerBackup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FazerBackup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFileChooser JCF_Salvar_Backup;
    public static javax.swing.JLabel acessoUser;
    public static javax.swing.JLabel acessoUser1;
    private javax.swing.JButton botApagarItem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public static javax.swing.JLabel mostrarNivel;
    public static javax.swing.JLabel mostrarNivel1;
    // End of variables declaration//GEN-END:variables
}
