/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mklivre;

import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;
import javax.swing.JOptionPane;
import java.sql.*;
import controle.ModuloConexao;
import net.proteanit.sql.DbUtils;
/**
 *
 * @author willi
 */
public class ItensPausados extends javax.swing.JFrame {
    Connection conexao = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    /**
     * Creates new form ItensPausados
     */
    public ItensPausados() {
        initComponents();
        URL caminhoIcone = getClass().getResource("/mklivre/icone/icone2.png");
        Image iconeTitulo = Toolkit.getDefaultToolkit().getImage(caminhoIcone);
        this.setIconImage(iconeTitulo);
        conexao = ModuloConexao.conector();
    }
    public void setar(){
        int setar=tabelaDePecas.getSelectedRow();
        TodosOsItensCadastrados todos = new TodosOsItensCadastrados();
        todos.setVisible(true);
        todos.codigoCadastrado.setText(tabelaDePecas.getModel().getValueAt(setar,0).toString());
        todos.nomePeca.setText(tabelaDePecas.getModel().getValueAt(setar,1).toString());
        todos.marcaCadastrada.setText(tabelaDePecas.getModel().getValueAt(setar,2).toString());
        todos.quantCadastrada.setText(tabelaDePecas.getModel().getValueAt(setar,3).toString());
        todos.mostrarNivel.setText(mostrarNivel.getText());
        todos.acessoUser.setText(acessoUser.getText());
        todos.vindoDoEspera.setText("1");
    }
    int mudar=0;
    private void pesquisar(){
        String sql = "select CÓDIGO,NOME,MARCA,QUANTIDADE from tb_pecas_ml2 where PAUSADO=?";
        try {
            pst = conexao.prepareStatement(sql);
            pst.setString(1, "SIM");
            rs=pst.executeQuery();
            tabelaDePecas.setModel(DbUtils.resultSetToTableModel(rs));
            mudar=1;
            campoMecanicos.removeAllItems();
            campoMecanicos.addItem("TODOS");
            pupolaJComboBox();
            mudar=0;
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }
    }
    private void pesquisarMarca(){
        String sql = "select CÓDIGO,NOME,LOCALIZAÇÃO,MARCA,QUANTIDADE,QUANTIDADE_RECOMENDADA from tb_pecas_ml2 where MARCA =?";
        try {
            pst = conexao.prepareStatement(sql);
            pst.setString(1,campoMecanicos.getSelectedItem().toString());
            rs=pst.executeQuery();
            tabelaDePecas.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }
    }
    public void pupolaJComboBox(){
        String sql ="select * from tb_pecas_ml2 where PAUSADO=?";
        try {
            pst = conexao.prepareStatement(sql);
            pst.setString(1, "SIM");
            rs=pst.executeQuery();
            while(rs.next()){
                campoMecanicos.addItem(rs.getString("MARCA"));
            }
            combobox();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }
    }
    public void combobox(){
        int quant=campoMecanicos.getItemCount();
        int valida=0;  
        String aux[]=new String[quant];
        for(int x=0;x<quant;x++){
            aux[x]=null;
        }
        int comp=1;
        while(quant>comp){
            for(int x=0;x<quant;x++){
                if(campoMecanicos.getItemAt(comp).equals(aux[x])){
                    valida=1;
                    break;
                }
            }
            if(valida==0){
                for(int x=0;x<quant;x++){
                    if(aux[x]==null){
                       aux[x]=campoMecanicos.getItemAt(comp);
                        break;
                    }
                }
            }
            valida=0;
            comp++;
        }
        mudar=1;
        campoMecanicos.removeAllItems();
        campoMecanicos.addItem("TODOS");
        for (int x=0;x<quant;x++){
            if(aux[x]!=null){
                campoMecanicos.addItem(aux[x]);
            }
        }
        mudar=0;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        campoMecanicos = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        botaoEntrarIniciall = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaDePecas = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        acessoUser = new javax.swing.JLabel();
        mostrarNivel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("ITENS PAUSADOS");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(null);

        campoMecanicos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TODOS" }));
        campoMecanicos.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                campoMecanicosItemStateChanged(evt);
            }
        });
        campoMecanicos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                campoMecanicosKeyPressed(evt);
            }
        });
        getContentPane().add(campoMecanicos);
        campoMecanicos.setBounds(10, 490, 160, 40);

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Sem título.png"))); // NOI18N
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 0, 150, 80);

        botaoEntrarIniciall.setBackground(new java.awt.Color(0, 0, 0));
        botaoEntrarIniciall.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        botaoEntrarIniciall.setForeground(new java.awt.Color(255, 255, 255));
        botaoEntrarIniciall.setText("MOSTRAR");
        botaoEntrarIniciall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoEntrarIniciallActionPerformed(evt);
            }
        });
        botaoEntrarIniciall.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                botaoEntrarIniciallKeyPressed(evt);
            }
        });
        getContentPane().add(botaoEntrarIniciall);
        botaoEntrarIniciall.setBounds(190, 490, 160, 40);

        tabelaDePecas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NOME", "CÓDIGO", "CAIXA", "LOCALIZAÇÃO", "MARCA", "QUANTIDADE"
            }
        ));
        jScrollPane2.setViewportView(tabelaDePecas);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(-5, 85, 760, 395);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 21)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("ITENS PAUSADOS");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(250, 10, 340, 60);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundo preto.png"))); // NOI18N
        jLabel1.setMinimumSize(new java.awt.Dimension(1057, 340));
        jLabel1.setPreferredSize(new java.awt.Dimension(1057, 350));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 4, 750, 77);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/FUNDO AMARELO.jpg"))); // NOI18N
        getContentPane().add(jLabel11);
        jLabel11.setBounds(0, -331, 760, 430);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/RS.png"))); // NOI18N
        getContentPane().add(jLabel10);
        jLabel10.setBounds(240, 20, 570, 550);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/RS.png"))); // NOI18N
        getContentPane().add(jLabel12);
        jLabel12.setBounds(-10, 40, 570, 530);

        acessoUser.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        acessoUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        acessoUser.setText("ADMIN");
        getContentPane().add(acessoUser);
        acessoUser.setBounds(520, 220, 70, 60);

        mostrarNivel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        mostrarNivel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mostrarNivel.setText("5");
        getContentPane().add(mostrarNivel);
        mostrarNivel.setBounds(520, 130, 50, 70);

        setSize(new java.awt.Dimension(745, 569));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    private void botaoEntrarIniciallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoEntrarIniciallActionPerformed
        setar();
    }//GEN-LAST:event_botaoEntrarIniciallActionPerformed

    private void botaoEntrarIniciallKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_botaoEntrarIniciallKeyPressed
        if(evt.getKeyCode() == evt.VK_ENTER){
            setar();
        }
    }//GEN-LAST:event_botaoEntrarIniciallKeyPressed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        if(mudar==0){
            if(campoMecanicos.getSelectedItem().toString().equals("TODOS")){
                pesquisar();
            }
            else{
                pesquisarMarca();
            }
        }
    }//GEN-LAST:event_formWindowActivated

    private void campoMecanicosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_campoMecanicosItemStateChanged
        if(mudar==0){
            if(campoMecanicos.getSelectedItem().toString().equals("TODOS")){
                pesquisar();
            }
            else{
                pesquisarMarca();
            }
        }
    }//GEN-LAST:event_campoMecanicosItemStateChanged

    private void campoMecanicosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoMecanicosKeyPressed
        if(evt.getKeyCode() == evt.VK_ENTER){
            if(mudar==0){
                if(campoMecanicos.getSelectedItem().toString().equals("TODOS")){
                    pesquisar();
                }
                else{
                    pesquisarMarca();
                }
            }
        }
    }//GEN-LAST:event_campoMecanicosKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ItensPausados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ItensPausados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ItensPausados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ItensPausados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ItensPausados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel acessoUser;
    private javax.swing.JButton botaoEntrarIniciall;
    private javax.swing.JComboBox<String> campoMecanicos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane2;
    public static javax.swing.JLabel mostrarNivel;
    private javax.swing.JTable tabelaDePecas;
    // End of variables declaration//GEN-END:variables
}
