/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mklivre;

import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;
import javax.swing.JOptionPane;
import java.sql.*;
import controle.ModuloConexao;
/**
 *
 * @author willi
 */
public class LocalizarCadastro2 extends javax.swing.JFrame {
    Connection conexao = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    /**
     * Creates new form LocalizarCadastro2
     */
    public LocalizarCadastro2() {
        initComponents();
        URL caminhoIcone = getClass().getResource("/mklivre/icone/icone2.png");
        Image iconeTitulo = Toolkit.getDefaultToolkit().getImage(caminhoIcone);
        this.setIconImage(iconeTitulo);
        conexao = ModuloConexao.conector();
    }
    
    private void consultar2(){
        String sqlnome = "select * from tbusuarios2 where NOME=?";
        try {
            pst = conexao.prepareStatement(sqlnome);
            pst.setString(1,nomePeca.getText());
            rs = pst.executeQuery();
            if (rs.next()) {
                EditarUsuario usuario = new EditarUsuario();
                usuario.setVisible(true);
                usuario.cadastroNome.setText(rs.getString(1));
                String sexo=rs.getString(5);
                if(sexo.equals("MASCULINO")){
                    usuario.sexoMascu.setSelected(true);
                }
                else{
                    usuario.sexoFemi.setSelected(true);
                }
                String acesso = rs.getString(4);
                if(acesso.equals("AT")){
                    usuario.localAtendimento.setSelected(true);
                }
                if(acesso.equals("ML")){
                    usuario.localML.setSelected(true);
                }
                if(acesso.equals("ES")){
                    usuario.localEs.setSelected(true);
                }
                if(acesso.equals("OF")){
                    usuario.localOficina.setSelected(true);
                }
                String nivel = rs.getString(3);
                if(nivel.equals("1")){
                    usuario.nivelUm.setSelected(true);
                }
                else if(nivel.equals("2")){
                    usuario.nivelDois.setSelected(true);
                }
                else if(nivel.equals("3")){
                    usuario.nivelTres.setSelected(true);
                }
                else if(nivel.equals("4")){
                    usuario.nivelQuatro.setSelected(true);
                }
                else if(nivel.equals("5")){
                    usuario.nivelCinco.setSelected(true);
                }
                this.dispose();
            }
            else{
                JOptionPane.showMessageDialog(null,"USUÁRIO NÃO ENCONTRADO NO BANCO DE DADOS!");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nomePeca = new javax.swing.JTextField();
        botaoEntrarIniciall3 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        acessoUser = new javax.swing.JLabel();
        mostrarNivel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("LOCALIZAR USUÁRIO");
        setResizable(false);
        getContentPane().setLayout(null);

        nomePeca.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nomePeca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nomePecaKeyPressed(evt);
            }
        });
        getContentPane().add(nomePeca);
        nomePeca.setBounds(30, 130, 240, 30);

        botaoEntrarIniciall3.setBackground(new java.awt.Color(0, 0, 0));
        botaoEntrarIniciall3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        botaoEntrarIniciall3.setForeground(new java.awt.Color(255, 255, 255));
        botaoEntrarIniciall3.setText("LOCALIZAR");
        botaoEntrarIniciall3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoEntrarIniciall3ActionPerformed(evt);
            }
        });
        botaoEntrarIniciall3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                botaoEntrarIniciall3KeyPressed(evt);
            }
        });
        getContentPane().add(botaoEntrarIniciall3);
        botaoEntrarIniciall3.setBounds(30, 200, 240, 40);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 21)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("LOCALIZAR CADASTRO");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(150, 10, 250, 60);

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("NOME");
        getContentPane().add(jLabel19);
        jLabel19.setBounds(30, 100, 70, 17);

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Sem título.png"))); // NOI18N
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 0, 150, 80);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundo preto.png"))); // NOI18N
        jLabel1.setMinimumSize(new java.awt.Dimension(1057, 340));
        jLabel1.setPreferredSize(new java.awt.Dimension(1057, 350));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 4, 450, 77);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/FUNDO AMARELO.jpg"))); // NOI18N
        getContentPane().add(jLabel11);
        jLabel11.setBounds(0, -331, 460, 430);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/RS.png"))); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(280, 50, 570, 530);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/RS.png"))); // NOI18N
        getContentPane().add(jLabel10);
        jLabel10.setBounds(-10, 0, 390, 400);

        acessoUser.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        acessoUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        acessoUser.setText("ADMIN");
        getContentPane().add(acessoUser);
        acessoUser.setBounds(520, 220, 70, 60);

        mostrarNivel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        mostrarNivel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mostrarNivel.setText("5");
        getContentPane().add(mostrarNivel);
        mostrarNivel.setBounds(520, 130, 50, 70);

        setSize(new java.awt.Dimension(422, 290));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void nomePecaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nomePecaKeyPressed
        if(evt.getKeyCode() == evt.VK_ENTER){
            if(nomePeca.getText().equals("")){
                JOptionPane.showMessageDialog(null,"DIGITE UM NOME");
            }
            else{
                consultar2();
            }
        }
    }//GEN-LAST:event_nomePecaKeyPressed

    private void botaoEntrarIniciall3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoEntrarIniciall3ActionPerformed
        if(nomePeca.getText().equals("")){
            JOptionPane.showMessageDialog(null,"DIGITE UM NOME");
        }
        else{
            consultar2();
        }
    }//GEN-LAST:event_botaoEntrarIniciall3ActionPerformed

    private void botaoEntrarIniciall3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_botaoEntrarIniciall3KeyPressed
        if(evt.getKeyCode() == evt.VK_ENTER){
            if(nomePeca.getText().equals("")){
                JOptionPane.showMessageDialog(null,"DIGITE UM NOME");
            }
            else{
                consultar2();
            }
        }
    }//GEN-LAST:event_botaoEntrarIniciall3KeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LocalizarCadastro2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LocalizarCadastro2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LocalizarCadastro2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LocalizarCadastro2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LocalizarCadastro2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel acessoUser;
    private javax.swing.JButton botaoEntrarIniciall3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    public static javax.swing.JLabel mostrarNivel;
    private javax.swing.JTextField nomePeca;
    // End of variables declaration//GEN-END:variables
}
