/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mklivre;

import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;
import javax.swing.JOptionPane;

/**
 *
 * @author willi
 */
public class MecanicoCadastrado extends javax.swing.JFrame {

    /**
     * Creates new form MecanicoCadastrado
     */
    public MecanicoCadastrado() {
        initComponents();
        URL caminhoIcone = getClass().getResource("/mklivre/icone/icone2.png");
        Image iconeTitulo = Toolkit.getDefaultToolkit().getImage(caminhoIcone);
        this.setIconImage(iconeTitulo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel19 = new javax.swing.JLabel();
        cadastroNome = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        salvarMecanico = new javax.swing.JButton();
        statusAtivo = new javax.swing.JRadioButton();
        statusInativo = new javax.swing.JRadioButton();
        jLabel23 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        acessoUser = new javax.swing.JLabel();
        mostrarNivel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("MECÂNICO CADASTRADO");
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("NOME");
        getContentPane().add(jLabel19);
        jLabel19.setBounds(40, 100, 100, 21);

        cadastroNome.setEditable(false);
        cadastroNome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cadastroNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cadastroNomeKeyPressed(evt);
            }
        });
        getContentPane().add(cadastroNome);
        cadastroNome.setBounds(40, 130, 200, 30);

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Sem título.png"))); // NOI18N
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel6);
        jLabel6.setBounds(-4, 0, 150, 80);

        salvarMecanico.setBackground(new java.awt.Color(0, 0, 0));
        salvarMecanico.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        salvarMecanico.setForeground(new java.awt.Color(255, 255, 255));
        salvarMecanico.setText("EDITAR");
        salvarMecanico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarMecanicoActionPerformed(evt);
            }
        });
        salvarMecanico.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                salvarMecanicoKeyPressed(evt);
            }
        });
        getContentPane().add(salvarMecanico);
        salvarMecanico.setBounds(270, 240, 110, 40);

        statusAtivo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        statusAtivo.setForeground(new java.awt.Color(255, 255, 255));
        statusAtivo.setText("ATIVO");
        statusAtivo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                statusAtivoKeyPressed(evt);
            }
        });
        getContentPane().add(statusAtivo);
        statusAtivo.setBounds(40, 210, 200, 25);

        statusInativo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        statusInativo.setForeground(new java.awt.Color(255, 255, 255));
        statusInativo.setText("INATIVO");
        statusInativo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                statusInativoKeyPressed(evt);
            }
        });
        getContentPane().add(statusInativo);
        statusInativo.setBounds(40, 250, 200, 25);

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("STATUS");
        getContentPane().add(jLabel23);
        jLabel23.setBounds(40, 180, 180, 21);

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/faixa-cinza-5.png"))); // NOI18N
        getContentPane().add(jLabel28);
        jLabel28.setBounds(210, 570, 50, 120);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 21)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("MECÂNICO CADASTRADO");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(110, 10, 330, 60);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundo preto.png"))); // NOI18N
        jLabel12.setMinimumSize(new java.awt.Dimension(1057, 340));
        jLabel12.setPreferredSize(new java.awt.Dimension(1057, 350));
        getContentPane().add(jLabel12);
        jLabel12.setBounds(-80, 4, 760, 77);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundo preto.png"))); // NOI18N
        jLabel1.setMinimumSize(new java.awt.Dimension(1057, 340));
        jLabel1.setPreferredSize(new java.awt.Dimension(1057, 350));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(140, 4, 760, 77);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/FUNDO AMARELO.jpg"))); // NOI18N
        getContentPane().add(jLabel11);
        jLabel11.setBounds(0, -331, 760, 430);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/RS.png"))); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(320, 340, 570, 530);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/RS.png"))); // NOI18N
        getContentPane().add(jLabel9);
        jLabel9.setBounds(-20, 450, 570, 530);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/RS.png"))); // NOI18N
        getContentPane().add(jLabel10);
        jLabel10.setBounds(0, 0, 570, 530);

        acessoUser.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        acessoUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        acessoUser.setText("ADMIN");
        getContentPane().add(acessoUser);
        acessoUser.setBounds(520, 220, 70, 60);

        mostrarNivel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        mostrarNivel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mostrarNivel.setText("5");
        getContentPane().add(mostrarNivel);
        mostrarNivel.setBounds(520, 130, 50, 70);

        setSize(new java.awt.Dimension(435, 356));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cadastroNomeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cadastroNomeKeyPressed
        if(evt.getKeyCode() == evt.VK_ENTER){
            statusAtivo.requestFocus();
        }
    }//GEN-LAST:event_cadastroNomeKeyPressed

    private void salvarMecanicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarMecanicoActionPerformed
        if(statusAtivo.isSelected()||statusInativo.isSelected()){
            if(cadastroNome.getText().equals("")){
                JOptionPane.showMessageDialog(null, "POR FAVOR PREENCHA TODOS OS CAMPOS");
            }
            else{
                EditarMecanico editar = new EditarMecanico();
                editar.setVisible(true);
                editar.cadastroNome.setText(cadastroNome.getText());
                if(statusAtivo.isSelected()){
                    editar.statusAtivo.setSelected(true);
                }
                else if(statusInativo.isSelected()){
                    editar.statusInativo.setSelected(true);
                }
                this.dispose();
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "POR FAVOR PREENCHA TODOS OS CAMPOS");
        }
    }//GEN-LAST:event_salvarMecanicoActionPerformed

    private void salvarMecanicoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_salvarMecanicoKeyPressed
        if(evt.getKeyCode() == evt.VK_ENTER){
            if(cadastroNome.getText().equals("")){
                JOptionPane.showMessageDialog(null, "POR FAVOR PREENCHA TODOS OS CAMPOS");
            }
            else{
                JOptionPane.showMessageDialog(null,"MECÂNICO EDITADO COM SUCESSO");
            }
        }
    }//GEN-LAST:event_salvarMecanicoKeyPressed

    private void statusAtivoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_statusAtivoKeyPressed
        if(evt.getKeyCode() == evt.VK_ENTER){
            statusInativo.requestFocus();
        }
    }//GEN-LAST:event_statusAtivoKeyPressed

    private void statusInativoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_statusInativoKeyPressed
        if(evt.getKeyCode() == evt.VK_ENTER){
            if(cadastroNome.getText().equals("")){
                JOptionPane.showMessageDialog(null, "POR FAVOR PREENCHA TODOS OS CAMPOS");
            }
            else{
                JOptionPane.showMessageDialog(null,"MECÂNICO EDITADO COM SUCESSO");
            }
        }
    }//GEN-LAST:event_statusInativoKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MecanicoCadastrado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MecanicoCadastrado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MecanicoCadastrado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MecanicoCadastrado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MecanicoCadastrado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel acessoUser;
    public static javax.swing.JTextField cadastroNome;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public static javax.swing.JLabel mostrarNivel;
    private javax.swing.JButton salvarMecanico;
    public static javax.swing.JRadioButton statusAtivo;
    public static javax.swing.JRadioButton statusInativo;
    // End of variables declaration//GEN-END:variables
}
