/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mklivre;

import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;
import javax.swing.JOptionPane;
import java.sql.*;
import controle.ModuloConexao;
/**
 *
 * @author willi
 */
public class OficinaSystem extends javax.swing.JFrame {
    Connection conexao = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    /**
     * Creates new form OficinaSystem
     */
    public OficinaSystem() {
        initComponents();
        URL caminhoIcone = getClass().getResource("/mklivre/icone/icone2.png");
        Image iconeTitulo = Toolkit.getDefaultToolkit().getImage(caminhoIcone);
        this.setIconImage(iconeTitulo);
        conexao = ModuloConexao.conector();
    }
    int nivel;
    String acesso="admin",nome;
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        varTres2 = new javax.swing.JLabel();
        editarMecanicos = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        apagarItens = new javax.swing.JButton();
        cadastroItem = new javax.swing.JButton();
        localizarItens = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        acessoUser = new javax.swing.JLabel();
        mostrarNivel = new javax.swing.JLabel();

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("EDITAR MECÂNICOS");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("OFICINA");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("APAGAR EXECUÇÕES");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel5);
        jLabel5.setBounds(80, 280, 230, 22);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("OFICINA");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(110, 30, 240, 22);

        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Sem título.png"))); // NOI18N
        jLabel15.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel15);
        jLabel15.setBounds(-10, 0, 150, 80);

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("REGISTRAR EXECUÇÕES");
        jLabel17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel17MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel17);
        jLabel17.setBounds(80, 140, 230, 22);

        varTres2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/faixa-cinza-5.png"))); // NOI18N
        getContentPane().add(varTres2);
        varTres2.setBounds(90, 280, 80, 20);

        editarMecanicos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/oficina.png"))); // NOI18N
        editarMecanicos.setMaximumSize(new java.awt.Dimension(32, 32));
        editarMecanicos.setMinimumSize(new java.awt.Dimension(32, 32));
        editarMecanicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarMecanicosActionPerformed(evt);
            }
        });
        editarMecanicos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                editarMecanicosKeyPressed(evt);
            }
        });
        getContentPane().add(editarMecanicos);
        editarMecanicos.setBounds(10, 330, 60, 58);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("MECÂNICOS");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel8);
        jLabel8.setBounds(80, 350, 200, 22);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("VERIFICAR EXECUÇÕES");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel6);
        jLabel6.setBounds(80, 210, 230, 22);

        apagarItens.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/APAGAR ARQUIVO.png"))); // NOI18N
        apagarItens.setMaximumSize(new java.awt.Dimension(32, 32));
        apagarItens.setMinimumSize(new java.awt.Dimension(32, 32));
        apagarItens.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apagarItensActionPerformed(evt);
            }
        });
        apagarItens.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                apagarItensKeyPressed(evt);
            }
        });
        getContentPane().add(apagarItens);
        apagarItens.setBounds(10, 260, 60, 58);

        cadastroItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/NOVO ARQUIVO.png"))); // NOI18N
        cadastroItem.setMaximumSize(new java.awt.Dimension(32, 32));
        cadastroItem.setMinimumSize(new java.awt.Dimension(32, 32));
        cadastroItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastroItemActionPerformed(evt);
            }
        });
        cadastroItem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cadastroItemKeyPressed(evt);
            }
        });
        getContentPane().add(cadastroItem);
        cadastroItem.setBounds(10, 120, 60, 58);

        localizarItens.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/LOCALIZAR ARQUIVO.png"))); // NOI18N
        localizarItens.setMaximumSize(new java.awt.Dimension(32, 32));
        localizarItens.setMinimumSize(new java.awt.Dimension(32, 32));
        localizarItens.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                localizarItensActionPerformed(evt);
            }
        });
        localizarItens.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                localizarItensKeyPressed(evt);
            }
        });
        getContentPane().add(localizarItens);
        localizarItens.setBounds(10, 190, 60, 58);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundo preto.png"))); // NOI18N
        jLabel3.setMinimumSize(new java.awt.Dimension(1057, 340));
        jLabel3.setPreferredSize(new java.awt.Dimension(1057, 350));
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 4, 450, 77);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/FUNDO AMARELO.jpg"))); // NOI18N
        getContentPane().add(jLabel11);
        jLabel11.setBounds(0, -331, 460, 430);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/RS.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, -190, 450, 790);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/RS.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(-20, 220, 420, 790);

        acessoUser.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        acessoUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        acessoUser.setText("ADMIN");
        getContentPane().add(acessoUser);
        acessoUser.setBounds(520, 220, 70, 60);

        mostrarNivel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        mostrarNivel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mostrarNivel.setText("5");
        getContentPane().add(mostrarNivel);
        mostrarNivel.setBounds(520, 130, 50, 70);

        setBounds(175, 150, 360, 465);
    }// </editor-fold>//GEN-END:initComponents

    private void cadastroItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastroItemActionPerformed
        RegistroExecucoes registro = new RegistroExecucoes();
        registro.setVisible(true);
        registro.mostrarNivel.setText(mostrarNivel.getText());
        registro.acessoUser.setText(acessoUser.getText());
    }//GEN-LAST:event_cadastroItemActionPerformed

    private void cadastroItemKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cadastroItemKeyPressed
        if(evt.getKeyCode() == evt.VK_ENTER){
            RegistroExecucoes registro = new RegistroExecucoes();
            registro.setVisible(true);
            registro.mostrarNivel.setText(mostrarNivel.getText());
            registro.acessoUser.setText(acessoUser.getText());
        }
    }//GEN-LAST:event_cadastroItemKeyPressed

    private void localizarItensActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_localizarItensActionPerformed
        CaminhoDasExecucoes localiza= new CaminhoDasExecucoes();
        localiza.setVisible(true);
        localiza.mostrarNivel.setText(mostrarNivel.getText());
        localiza.acessoUser.setText(acessoUser.getText());
    }//GEN-LAST:event_localizarItensActionPerformed

    private void localizarItensKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_localizarItensKeyPressed
        if(evt.getKeyCode() == evt.VK_ENTER){
            CaminhoDasExecucoes localiza= new CaminhoDasExecucoes();
            localiza.setVisible(true);
            localiza.mostrarNivel.setText(mostrarNivel.getText());
            localiza.acessoUser.setText(acessoUser.getText());
        }
    }//GEN-LAST:event_localizarItensKeyPressed

    private void editarMecanicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarMecanicosActionPerformed
        if(acesso.equals("OF")||nivel==5){
            AddEditRemoveMecanico opc = new AddEditRemoveMecanico();
            opc.setVisible(true);
            opc.mostrarNivel.setText(mostrarNivel.getText());
            opc.acessoUser.setText(acessoUser.getText());
        }
        else{
            JOptionPane.showMessageDialog(null, "VOCÊ NÃO TEM ACESSO A ESSE MÓDULO!");
        }
    }//GEN-LAST:event_editarMecanicosActionPerformed

    private void editarMecanicosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_editarMecanicosKeyPressed
        if(evt.getKeyCode() == evt.VK_ENTER){
            if(acesso.equals("OF")||nivel==5){
                AddEditRemoveMecanico opc = new AddEditRemoveMecanico();
                opc.setVisible(true);
                opc.mostrarNivel.setText(mostrarNivel.getText());
                opc.acessoUser.setText(acessoUser.getText());
            }
            else{
                JOptionPane.showMessageDialog(null, "VOCÊ NÃO TEM ACESSO A ESSE MÓDULO!");
            }
        }
    }//GEN-LAST:event_editarMecanicosKeyPressed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        nivel=Integer.parseInt(mostrarNivel.getText());
        acesso = acessoUser.getText();
    }//GEN-LAST:event_formWindowActivated

    private void apagarItensActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apagarItensActionPerformed
        if(acesso.equals("OF")||nivel==5){
            ApagarExecucoes apagar = new ApagarExecucoes();
            apagar.setVisible(true);
            apagar.mostrarNivel.setText(mostrarNivel.getText());
            apagar.acessoUser.setText(acessoUser.getText());
        }
        else{
            JOptionPane.showMessageDialog(null, "VOCÊ NÃO TEM ACESSO A ESSE MÓDULO!");
        }
    }//GEN-LAST:event_apagarItensActionPerformed

    private void apagarItensKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_apagarItensKeyPressed
        if(evt.getKeyCode() == evt.VK_ENTER){
            if(acesso.equals("OF")||nivel==5){
                ApagarExecucoes apagar = new ApagarExecucoes();
                apagar.setVisible(true);
                apagar.mostrarNivel.setText(mostrarNivel.getText());
                apagar.acessoUser.setText(acessoUser.getText());
            }
            else{
                JOptionPane.showMessageDialog(null, "VOCÊ NÃO TEM ACESSO A ESSE MÓDULO!");
            }
        }
    }//GEN-LAST:event_apagarItensKeyPressed

    private void jLabel17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MouseClicked
        RegistroExecucoes registro = new RegistroExecucoes();
        registro.setVisible(true);
        registro.mostrarNivel.setText(mostrarNivel.getText());
        registro.acessoUser.setText(acessoUser.getText());
    }//GEN-LAST:event_jLabel17MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        CaminhoDasExecucoes localiza= new CaminhoDasExecucoes();
        localiza.setVisible(true);
        localiza.mostrarNivel.setText(mostrarNivel.getText());
        localiza.acessoUser.setText(acessoUser.getText());
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        if(acesso.equals("OF")||nivel==5){
            ApagarExecucoes apagar = new ApagarExecucoes();
            apagar.setVisible(true);
            apagar.mostrarNivel.setText(mostrarNivel.getText());
            apagar.acessoUser.setText(acessoUser.getText());
        }
        else{
            JOptionPane.showMessageDialog(null, "VOCÊ NÃO TEM ACESSO A ESSE MÓDULO!");
        }
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        if(acesso.equals("OF")||nivel==5){
            AddEditRemoveMecanico opc = new AddEditRemoveMecanico();
            opc.setVisible(true);
            opc.mostrarNivel.setText(mostrarNivel.getText());
            opc.acessoUser.setText(acessoUser.getText());
        }
        else{
            JOptionPane.showMessageDialog(null, "VOCÊ NÃO TEM ACESSO A ESSE MÓDULO!");
        }
    }//GEN-LAST:event_jLabel8MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OficinaSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OficinaSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OficinaSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OficinaSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OficinaSystem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel acessoUser;
    private javax.swing.JButton apagarItens;
    private javax.swing.JButton cadastroItem;
    private javax.swing.JButton editarMecanicos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton localizarItens;
    public static javax.swing.JLabel mostrarNivel;
    public javax.swing.JLabel varTres2;
    // End of variables declaration//GEN-END:variables
}
