/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mklivre;

import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;
import javax.swing.JOptionPane;
import java.sql.*;
import controle.ModuloConexao;
import java.awt.Frame;
/**
 *
 * @author willi
 */
public class SegundaTela extends javax.swing.JFrame {
    Connection conexao = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    public SegundaTela() {
        initComponents();
        userHomem.setVisible(false);
        userMulher.setVisible(false);
        URL caminhoIcone = getClass().getResource("/mklivre/icone/icone2.png");
        Image iconeTitulo = Toolkit.getDefaultToolkit().getImage(caminhoIcone);
        this.setIconImage(iconeTitulo);
        varUm1.setVisible(false);
        varDois1.setVisible(false);
        varTres1.setVisible(false);
        varQuatro1.setVisible(false);
        varCinco1.setVisible(false);
        varSeis1.setVisible(false);
        varUm2.setVisible(false);
        varDois2.setVisible(false);
        varTres2.setVisible(false);
        varQuatro2.setVisible(false);
        varCinco2.setVisible(false);
        varSeis2.setVisible(false);
        varUm3.setVisible(false);
        varDois3.setVisible(false);
        varTres3.setVisible(false);
        varQuatro3.setVisible(false);
        varCinco3.setVisible(false);
        varSeis3.setVisible(false);
        varUm4.setVisible(false);
        varDois4.setVisible(false);
        varTres4.setVisible(false);
        varQuatro4.setVisible(false);
        varCinco4.setVisible(false);
        varSeis4.setVisible(false);
        varOficina1.setVisible(false);
        varOficina2.setVisible(false);
        varOficina3.setVisible(false);
        varOficina4.setVisible(false);
        conexao = ModuloConexao.conector();
    }
    int nivel;
    String acesso="admin",nome;
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        opcoesDoMenu = new javax.swing.ButtonGroup();
        varOficina4 = new javax.swing.JLabel();
        varOficina3 = new javax.swing.JLabel();
        varOficina2 = new javax.swing.JLabel();
        varOficina1 = new javax.swing.JLabel();
        acessoUser = new javax.swing.JLabel();
        userProgramador = new javax.swing.JLabel();
        userHomem = new javax.swing.JLabel();
        userMulher = new javax.swing.JLabel();
        varSeis4 = new javax.swing.JLabel();
        varSeis3 = new javax.swing.JLabel();
        varSeis2 = new javax.swing.JLabel();
        varSeis1 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        varCinco1 = new javax.swing.JLabel();
        varCinco4 = new javax.swing.JLabel();
        varQuatro4 = new javax.swing.JLabel();
        varCinco2 = new javax.swing.JLabel();
        varQuatro1 = new javax.swing.JLabel();
        varCinco3 = new javax.swing.JLabel();
        varQuatro3 = new javax.swing.JLabel();
        varQuatro2 = new javax.swing.JLabel();
        varTres2 = new javax.swing.JLabel();
        varTres4 = new javax.swing.JLabel();
        varTres3 = new javax.swing.JLabel();
        varTres1 = new javax.swing.JLabel();
        varDois2 = new javax.swing.JLabel();
        varDois3 = new javax.swing.JLabel();
        varDois4 = new javax.swing.JLabel();
        varDois1 = new javax.swing.JLabel();
        varUm4 = new javax.swing.JLabel();
        varUm3 = new javax.swing.JLabel();
        varUm1 = new javax.swing.JLabel();
        varUm2 = new javax.swing.JLabel();
        botaoConfiguracoes = new javax.swing.JButton();
        botaoOficina = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        nomeUser = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        mostrarNivel = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        botaoRequisicao = new javax.swing.JButton();
        cadastroItem = new javax.swing.JButton();
        localizarItens = new javax.swing.JButton();
        editarItens = new javax.swing.JButton();
        apagarItens = new javax.swing.JButton();
        cadastroUsers = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("OnePie SYSTEM");
        setResizable(false);
        setSize(new java.awt.Dimension(546, 435));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(null);

        varOficina4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/faixa-cinza-5.png"))); // NOI18N
        getContentPane().add(varOficina4);
        varOficina4.setBounds(90, 590, 80, 20);

        varOficina3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/faixa-cinza-5.png"))); // NOI18N
        getContentPane().add(varOficina3);
        varOficina3.setBounds(90, 590, 80, 20);

        varOficina2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/faixa-cinza-5.png"))); // NOI18N
        getContentPane().add(varOficina2);
        varOficina2.setBounds(10, 570, 60, 60);

        varOficina1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/faixa-cinza-5.png"))); // NOI18N
        getContentPane().add(varOficina1);
        varOficina1.setBounds(10, 570, 60, 60);

        acessoUser.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        acessoUser.setForeground(new java.awt.Color(255, 255, 255));
        acessoUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        acessoUser.setText("ES");
        getContentPane().add(acessoUser);
        acessoUser.setBounds(290, 40, 70, 60);

        userProgramador.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        userProgramador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/USER PROGRAMMER.png"))); // NOI18N
        userProgramador.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        userProgramador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userProgramadorMouseClicked(evt);
            }
        });
        getContentPane().add(userProgramador);
        userProgramador.setBounds(150, 20, 40, 50);

        userHomem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        userHomem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/USER MAN.png"))); // NOI18N
        userHomem.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        userHomem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userHomemMouseClicked(evt);
            }
        });
        getContentPane().add(userHomem);
        userHomem.setBounds(150, 20, 40, 50);

        userMulher.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        userMulher.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/USER FEMALE.png"))); // NOI18N
        userMulher.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        userMulher.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userMulherMouseClicked(evt);
            }
        });
        getContentPane().add(userMulher);
        userMulher.setBounds(150, 20, 40, 50);

        varSeis4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/faixa-cinza-5.png"))); // NOI18N
        getContentPane().add(varSeis4);
        varSeis4.setBounds(90, 660, 160, 20);

        varSeis3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/faixa-cinza-5.png"))); // NOI18N
        getContentPane().add(varSeis3);
        varSeis3.setBounds(90, 660, 160, 20);

        varSeis2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/faixa-cinza-5.png"))); // NOI18N
        getContentPane().add(varSeis2);
        varSeis2.setBounds(10, 640, 60, 60);

        varSeis1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/faixa-cinza-5.png"))); // NOI18N
        getContentPane().add(varSeis1);
        varSeis1.setBounds(10, 640, 60, 60);

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel19.setText("MERCADO LIVRE");
        jLabel19.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel19MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel19);
        jLabel19.setBounds(90, 650, 260, 30);

        varCinco1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/faixa-cinza-5.png"))); // NOI18N
        getContentPane().add(varCinco1);
        varCinco1.setBounds(90, 510, 100, 30);

        varCinco4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/faixa-cinza-5.png"))); // NOI18N
        getContentPane().add(varCinco4);
        varCinco4.setBounds(10, 500, 60, 60);

        varQuatro4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/faixa-cinza-5.png"))); // NOI18N
        getContentPane().add(varQuatro4);
        varQuatro4.setBounds(90, 442, 120, 30);

        varCinco2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/faixa-cinza-5.png"))); // NOI18N
        getContentPane().add(varCinco2);
        varCinco2.setBounds(10, 500, 60, 60);

        varQuatro1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/faixa-cinza-5.png"))); // NOI18N
        getContentPane().add(varQuatro1);
        varQuatro1.setBounds(10, 430, 60, 60);

        varCinco3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/faixa-cinza-5.png"))); // NOI18N
        getContentPane().add(varCinco3);
        varCinco3.setBounds(90, 510, 100, 30);

        varQuatro3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/faixa-cinza-5.png"))); // NOI18N
        getContentPane().add(varQuatro3);
        varQuatro3.setBounds(90, 442, 120, 30);

        varQuatro2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/faixa-cinza-5.png"))); // NOI18N
        getContentPane().add(varQuatro2);
        varQuatro2.setBounds(10, 430, 60, 60);

        varTres2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/faixa-cinza-5.png"))); // NOI18N
        getContentPane().add(varTres2);
        varTres2.setBounds(90, 380, 80, 20);

        varTres4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/faixa-cinza-5.png"))); // NOI18N
        getContentPane().add(varTres4);
        varTres4.setBounds(90, 380, 80, 20);

        varTres3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/faixa-cinza-5.png"))); // NOI18N
        getContentPane().add(varTres3);
        varTres3.setBounds(10, 360, 60, 60);

        varTres1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/faixa-cinza-5.png"))); // NOI18N
        getContentPane().add(varTres1);
        varTres1.setBounds(10, 360, 60, 60);

        varDois2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/faixa-cinza-5.png"))); // NOI18N
        getContentPane().add(varDois2);
        varDois2.setBounds(90, 310, 70, 20);

        varDois3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/faixa-cinza-5.png"))); // NOI18N
        getContentPane().add(varDois3);
        varDois3.setBounds(10, 290, 60, 60);

        varDois4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/faixa-cinza-5.png"))); // NOI18N
        getContentPane().add(varDois4);
        varDois4.setBounds(90, 310, 70, 20);

        varDois1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/faixa-cinza-5.png"))); // NOI18N
        getContentPane().add(varDois1);
        varDois1.setBounds(10, 290, 60, 60);

        varUm4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/faixa-cinza-5.png"))); // NOI18N
        getContentPane().add(varUm4);
        varUm4.setBounds(90, 170, 110, 20);

        varUm3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/faixa-cinza-5.png"))); // NOI18N
        getContentPane().add(varUm3);
        varUm3.setBounds(90, 170, 110, 20);

        varUm1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/faixa-cinza-5.png"))); // NOI18N
        getContentPane().add(varUm1);
        varUm1.setBounds(10, 150, 60, 60);

        varUm2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/faixa-cinza-5.png"))); // NOI18N
        getContentPane().add(varUm2);
        varUm2.setBounds(10, 150, 60, 60);

        botaoConfiguracoes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/MERCADO LIVEW.png"))); // NOI18N
        botaoConfiguracoes.setMaximumSize(new java.awt.Dimension(32, 32));
        botaoConfiguracoes.setMinimumSize(new java.awt.Dimension(32, 32));
        botaoConfiguracoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoConfiguracoesActionPerformed(evt);
            }
        });
        botaoConfiguracoes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                botaoConfiguracoesKeyPressed(evt);
            }
        });
        getContentPane().add(botaoConfiguracoes);
        botaoConfiguracoes.setBounds(10, 640, 60, 58);

        botaoOficina.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/oficina2.png"))); // NOI18N
        botaoOficina.setMaximumSize(new java.awt.Dimension(32, 32));
        botaoOficina.setMinimumSize(new java.awt.Dimension(32, 32));
        botaoOficina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoOficinaActionPerformed(evt);
            }
        });
        botaoOficina.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                botaoOficinaKeyPressed(evt);
            }
        });
        getContentPane().add(botaoOficina);
        botaoOficina.setBounds(10, 570, 60, 58);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("OFICINA");
        jLabel4.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel4);
        jLabel4.setBounds(90, 580, 260, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("LOCALIZAR");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel5);
        jLabel5.setBounds(90, 240, 120, 22);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("MENU INICIAL");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(30, 100, 290, 40);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("CADASTRAR");
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel16MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel16);
        jLabel16.setBounds(90, 170, 120, 22);

        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Sem título.png"))); // NOI18N
        jLabel15.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel15);
        jLabel15.setBounds(-10, 0, 150, 80);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel13.setText("USUÁRIOS");
        jLabel13.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel13);
        jLabel13.setBounds(90, 510, 260, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("EDITAR");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel8);
        jLabel8.setBounds(90, 310, 80, 22);

        nomeUser.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        nomeUser.setForeground(new java.awt.Color(255, 255, 255));
        nomeUser.setText("WILLIAM");
        getContentPane().add(nomeUser);
        nomeUser.setBounds(200, 20, 140, 50);

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText(" NÍVEL");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(300, 0, 50, 50);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("APAGAR");
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel9);
        jLabel9.setBounds(90, 380, 80, 20);

        mostrarNivel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        mostrarNivel.setForeground(new java.awt.Color(255, 255, 255));
        mostrarNivel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mostrarNivel.setText("5");
        getContentPane().add(mostrarNivel);
        mostrarNivel.setBounds(300, 10, 50, 70);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("REQUISIÇÃO");
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel12);
        jLabel12.setBounds(90, 450, 260, 22);

        botaoRequisicao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/REQUISIÇÃO.png"))); // NOI18N
        botaoRequisicao.setMaximumSize(new java.awt.Dimension(32, 32));
        botaoRequisicao.setMinimumSize(new java.awt.Dimension(32, 32));
        botaoRequisicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoRequisicaoActionPerformed(evt);
            }
        });
        botaoRequisicao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                botaoRequisicaoKeyPressed(evt);
            }
        });
        getContentPane().add(botaoRequisicao);
        botaoRequisicao.setBounds(10, 430, 60, 58);

        cadastroItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/NOVO ARQUIVO.png"))); // NOI18N
        cadastroItem.setMaximumSize(new java.awt.Dimension(32, 32));
        cadastroItem.setMinimumSize(new java.awt.Dimension(32, 32));
        cadastroItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastroItemActionPerformed(evt);
            }
        });
        cadastroItem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cadastroItemKeyPressed(evt);
            }
        });
        getContentPane().add(cadastroItem);
        cadastroItem.setBounds(10, 150, 60, 58);

        localizarItens.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/LOCALIZAR ARQUIVO.png"))); // NOI18N
        localizarItens.setMaximumSize(new java.awt.Dimension(32, 32));
        localizarItens.setMinimumSize(new java.awt.Dimension(32, 32));
        localizarItens.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                localizarItensActionPerformed(evt);
            }
        });
        localizarItens.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                localizarItensKeyPressed(evt);
            }
        });
        getContentPane().add(localizarItens);
        localizarItens.setBounds(10, 220, 60, 58);

        editarItens.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ATUALIZAR ARQUIVO.png"))); // NOI18N
        editarItens.setMaximumSize(new java.awt.Dimension(32, 32));
        editarItens.setMinimumSize(new java.awt.Dimension(32, 32));
        editarItens.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarItensActionPerformed(evt);
            }
        });
        editarItens.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                editarItensKeyPressed(evt);
            }
        });
        getContentPane().add(editarItens);
        editarItens.setBounds(10, 290, 60, 58);

        apagarItens.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/APAGAR ARQUIVO.png"))); // NOI18N
        apagarItens.setMaximumSize(new java.awt.Dimension(32, 32));
        apagarItens.setMinimumSize(new java.awt.Dimension(32, 32));
        apagarItens.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apagarItensActionPerformed(evt);
            }
        });
        apagarItens.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                apagarItensKeyPressed(evt);
            }
        });
        getContentPane().add(apagarItens);
        apagarItens.setBounds(10, 360, 60, 58);

        cadastroUsers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/USER.png"))); // NOI18N
        cadastroUsers.setMaximumSize(new java.awt.Dimension(32, 32));
        cadastroUsers.setMinimumSize(new java.awt.Dimension(32, 32));
        cadastroUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastroUsersActionPerformed(evt);
            }
        });
        cadastroUsers.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cadastroUsersKeyPressed(evt);
            }
        });
        getContentPane().add(cadastroUsers);
        cadastroUsers.setBounds(10, 500, 60, 58);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundo preto.png"))); // NOI18N
        jLabel3.setMinimumSize(new java.awt.Dimension(1057, 340));
        jLabel3.setPreferredSize(new java.awt.Dimension(1057, 350));
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 4, 450, 77);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/FUNDO AMARELO.jpg"))); // NOI18N
        getContentPane().add(jLabel11);
        jLabel11.setBounds(0, -331, 460, 430);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/RS.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, -190, 400, 790);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/RS.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(-20, 220, 420, 790);

        setBounds(0, 0, 367, 748);
    }// </editor-fold>//GEN-END:initComponents

    private void apagarItensActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apagarItensActionPerformed
        if(nivel==1||(acesso.equals("OF")&&nivel!=5)){
            JOptionPane.showMessageDialog(null, "VOCÊ NÃO TEM ACESSO A ESSE MÓDULO!");
        }
        else if(nivel==2){
            JOptionPane.showMessageDialog(null, "VOCÊ NÃO TEM ACESSO A ESSE MÓDULO!");
        }
        else{
            CaminhoDaDeletacao apagar = new CaminhoDaDeletacao();
            apagar.setVisible(true);
            apagar.mostrarNivel.setText(mostrarNivel.getText());
            apagar.acessoUser.setText(acessoUser.getText());
        }
    }//GEN-LAST:event_apagarItensActionPerformed

    private void cadastroItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastroItemActionPerformed
        if(nivel==1||(acesso.equals("OF")&&nivel!=5)){
            JOptionPane.showMessageDialog(null, "VOCÊ NÃO TEM ACESSO A ESSE MÓDULO!");
        }
        else{
            MlOuEs mloues = new MlOuEs();
            mloues.setVisible(true); 
            mloues.mostrarNivel.setText(mostrarNivel.getText());
            mloues.acessoUser.setText(acessoUser.getText());
        }
    }//GEN-LAST:event_cadastroItemActionPerformed

    private void localizarItensActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_localizarItensActionPerformed
        LocalizarGlobalPecas localiza = new LocalizarGlobalPecas();
        localiza.setVisible(true);
        localiza.mostrarNivel.setText(mostrarNivel.getText());
        localiza.acessoUser.setText(acessoUser.getText());
    }//GEN-LAST:event_localizarItensActionPerformed

    private void editarItensActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarItensActionPerformed
        if(nivel==1||(acesso.equals("OF")&&nivel!=5)){
            JOptionPane.showMessageDialog(null, "VOCÊ NÃO TEM ACESSO A ESSE MÓDULO!");
        }
        else{
            EditarDoMlOuEs editar = new EditarDoMlOuEs();
            editar.setVisible(true);
            editar.mostrarNivel.setText(mostrarNivel.getText());
            editar.acessoUser.setText(acessoUser.getText());
        }
    }//GEN-LAST:event_editarItensActionPerformed

    private void botaoOficinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoOficinaActionPerformed
        if(nivel==5||(acesso.equals("OF")&&nivel!=5)){
            OficinaSystem oficina = new OficinaSystem();
            oficina.setVisible(true);
            oficina.mostrarNivel.setText(mostrarNivel.getText());
            oficina.acessoUser.setText(acessoUser.getText());
        }
        else{ 
            JOptionPane.showMessageDialog(null, "VOCÊ NÃO TEM ACESSO A ESSE MÓDULO!");
        }
    }//GEN-LAST:event_botaoOficinaActionPerformed

    private void botaoRequisicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoRequisicaoActionPerformed
        if(nivel==5||acesso.equals("ML")||acesso.equals("ES")){
            Requisicao requisita = new Requisicao();
            requisita.setVisible(true);
            requisita.mostrarNivel.setText(mostrarNivel.getText());
            requisita.acessoUser.setText(acessoUser.getText());
        }
        else{
            JOptionPane.showMessageDialog(null, "VOCÊ NÃO TEM ACESSO A ESSE MÓDULO!");
        }
    }//GEN-LAST:event_botaoRequisicaoActionPerformed

    private void cadastroUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastroUsersActionPerformed
        if(nivel==1||(acesso.equals("OF")&&nivel!=5)){
            JOptionPane.showMessageDialog(null, "VOCÊ NÃO TEM ACESSO A ESSE MÓDULO!");
        }
        else if(nivel==2){
            JOptionPane.showMessageDialog(null, "VOCÊ NÃO TEM ACESSO A ESSE MÓDULO!");
        }
        else if(nivel==3){
            JOptionPane.showMessageDialog(null, "VOCÊ NÃO TEM ACESSO A ESSE MÓDULO!");
        }
        else if(nivel==4){
            JOptionPane.showMessageDialog(null, "VOCÊ NÃO TEM ACESSO A ESSE MÓDULO!");
        }
        else{
            UserSystem user = new UserSystem();
            user.setVisible(true);
            user.mostrarNivel.setText(mostrarNivel.getText());
            user.acessoUser.setText(acessoUser.getText());
        }
    }//GEN-LAST:event_cadastroUsersActionPerformed

    private void cadastroItemKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cadastroItemKeyPressed
        if(evt.getKeyCode() == evt.VK_ENTER){
            if(nivel==1||(acesso.equals("OF")&&nivel!=5)){
                JOptionPane.showMessageDialog(null, "VOCÊ NÃO TEM ACESSO A ESSE MÓDULO!");
            }
            else{
                MlOuEs mloues = new MlOuEs();
                mloues.setVisible(true);
                mloues.mostrarNivel.setText(mostrarNivel.getText());
                mloues.acessoUser.setText(acessoUser.getText());
            }
        }
    }//GEN-LAST:event_cadastroItemKeyPressed

    private void localizarItensKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_localizarItensKeyPressed
        if(evt.getKeyCode() == evt.VK_ENTER){
            LocalizarGlobalPecas localiza = new LocalizarGlobalPecas();
            localiza.setVisible(true);
            localiza.mostrarNivel.setText(mostrarNivel.getText());
            localiza.acessoUser.setText(acessoUser.getText());
        }
    }//GEN-LAST:event_localizarItensKeyPressed

    private void editarItensKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_editarItensKeyPressed
        if(evt.getKeyCode() == evt.VK_ENTER){
            if(nivel==1||(acesso.equals("OF")&&nivel!=5)){
                JOptionPane.showMessageDialog(null, "VOCÊ NÃO TEM ACESSO A ESSE MÓDULO!");
            }
            else{
                EditarDoMlOuEs editar = new EditarDoMlOuEs();
                editar.setVisible(true);
                editar.mostrarNivel.setText(mostrarNivel.getText());
                editar.acessoUser.setText(acessoUser.getText());
            }
        }
    }//GEN-LAST:event_editarItensKeyPressed

    private void apagarItensKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_apagarItensKeyPressed
        if(evt.getKeyCode() == evt.VK_ENTER){
            if(nivel==1||(acesso.equals("OF")&&nivel!=5)){
                JOptionPane.showMessageDialog(null, "VOCÊ NÃO TEM ACESSO A ESSE MÓDULO!");
            }
            else if(nivel==2){
                JOptionPane.showMessageDialog(null, "VOCÊ NÃO TEM ACESSO A ESSE MÓDULO!");
            }
            else{
                CaminhoDaDeletacao apagar = new CaminhoDaDeletacao();
                apagar.setVisible(true);
                apagar.mostrarNivel.setText(mostrarNivel.getText());
                apagar.acessoUser.setText(acessoUser.getText());
            }
        }
    }//GEN-LAST:event_apagarItensKeyPressed

    private void botaoRequisicaoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_botaoRequisicaoKeyPressed
        if(evt.getKeyCode() == evt.VK_ENTER){
            if(nivel==5||acesso.equals("ML")||acesso.equals("ES")){
                Requisicao requisita = new Requisicao();
                requisita.setVisible(true);
                requisita.mostrarNivel.setText(mostrarNivel.getText());
                requisita.acessoUser.setText(acessoUser.getText());
            }
            else{
                JOptionPane.showMessageDialog(null, "VOCÊ NÃO TEM ACESSO A ESSE MÓDULO!");
            }
        }
    }//GEN-LAST:event_botaoRequisicaoKeyPressed

    private void cadastroUsersKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cadastroUsersKeyPressed
        if(evt.getKeyCode() == evt.VK_ENTER){
            if(nivel==1||(acesso.equals("OF")&&nivel!=5)){
                JOptionPane.showMessageDialog(null, "VOCÊ NÃO TEM ACESSO A ESSE MÓDULO!");
            }
            else if(nivel==2){
                JOptionPane.showMessageDialog(null, "VOCÊ NÃO TEM ACESSO A ESSE MÓDULO!");
            }
            else if(nivel==3){
                JOptionPane.showMessageDialog(null, "VOCÊ NÃO TEM ACESSO A ESSE MÓDULO!");
            }
            else if(nivel==4){
                JOptionPane.showMessageDialog(null, "VOCÊ NÃO TEM ACESSO A ESSE MÓDULO!");
            }
            else{
                UserSystem user = new UserSystem();
                user.setVisible(true);
                user.mostrarNivel.setText(mostrarNivel.getText());
                user.acessoUser.setText(acessoUser.getText());
            }
        }
    }//GEN-LAST:event_cadastroUsersKeyPressed

    private void botaoOficinaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_botaoOficinaKeyPressed
        if(evt.getKeyCode() == evt.VK_ENTER){
            if(nivel==5||(acesso.equals("OF")&&nivel!=5)){
                OficinaSystem oficina = new OficinaSystem();
                oficina.setVisible(true);
                oficina.mostrarNivel.setText(mostrarNivel.getText());
                oficina.acessoUser.setText(acessoUser.getText());
            }
            else{ 
                JOptionPane.showMessageDialog(null, "VOCÊ NÃO TEM ACESSO A ESSE MÓDULO!");
            }
        }
    }//GEN-LAST:event_botaoOficinaKeyPressed

    private void botaoConfiguracoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoConfiguracoesActionPerformed
        if(nivel==1||(acesso.equals("OF")&&nivel!=5)){
            JOptionPane.showMessageDialog(null, "VOCÊ NÃO TEM ACESSO A ESSE MÓDULO!");
        }
        else if(acesso.equals("AT")&&nivel!=5){
            JOptionPane.showMessageDialog(null, "VOCÊ NÃO TEM ACESSO A ESSE MÓDULO!\nMódulo destinado apenas aos usuários com acesso ao mercado livre!");
        }
        else{
            Configuracos conf = new Configuracos();
            conf.setVisible(true);
            conf.mostrarNivel.setText(mostrarNivel.getText());
            conf.acessoUser.setText(acessoUser.getText());
        }
    }//GEN-LAST:event_botaoConfiguracoesActionPerformed

    private void botaoConfiguracoesKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_botaoConfiguracoesKeyPressed
        if(evt.getKeyCode() == evt.VK_ENTER){
            if(nivel==1||(acesso.equals("OF")&&nivel!=5)){
                JOptionPane.showMessageDialog(null, "VOCÊ NÃO TEM ACESSO A ESSE MÓDULO!");
            }
            else if(acesso.equals("AT")&&nivel!=5){
                JOptionPane.showMessageDialog(null, "VOCÊ NÃO TEM ACESSO A ESSE MÓDULO!\nMódulo destinado apenas aos usuários com acesso ao mercado livre!");
            }
            else{
                Configuracos conf = new Configuracos();
                conf.setVisible(true);
                conf.mostrarNivel.setText(mostrarNivel.getText());
                conf.acessoUser.setText(acessoUser.getText());
            }
        }
    }//GEN-LAST:event_botaoConfiguracoesKeyPressed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        nivel=Integer.parseInt(mostrarNivel.getText());
        acesso = acessoUser.getText();
        if(acesso.equals("ES")&&nivel!=5){
            varOficina1.setVisible(true);
            varOficina2.setVisible(true);
            varOficina3.setVisible(true);
            varOficina4.setVisible(true);
        }
        if((nivel==1||acesso.equals("OF"))&&nivel!=5){
            varUm1.setVisible(true);
            varUm2.setVisible(true);
            varUm3.setVisible(true);
            varUm4.setVisible(true);
            varDois1.setVisible(true);
            varDois2.setVisible(true);
            varDois3.setVisible(true);
            varDois4.setVisible(true);
            varTres1.setVisible(true);
            varTres2.setVisible(true);
            varTres3.setVisible(true);
            varTres4.setVisible(true);
            varQuatro1.setVisible(true);
            varQuatro2.setVisible(true);
            varQuatro3.setVisible(true);
            varQuatro4.setVisible(true);
            varCinco1.setVisible(true);
            varCinco2.setVisible(true);
            varCinco3.setVisible(true);
            varCinco4.setVisible(true);
            varSeis1.setVisible(true);
            varSeis2.setVisible(true);
            varSeis3.setVisible(true);
            varSeis4.setVisible(true);
            if(acesso.equals("OF")){
                
            }
            else{
                varOficina1.setVisible(true);
                varOficina2.setVisible(true);
                varOficina3.setVisible(true);
                varOficina4.setVisible(true);
            }
        }
        else if(nivel==2){
            varTres1.setVisible(true);
            varTres2.setVisible(true);
            varTres3.setVisible(true);
            varTres4.setVisible(true);
            varCinco1.setVisible(true);
            varCinco2.setVisible(true);
            varCinco3.setVisible(true);
            varCinco4.setVisible(true);
            varOficina1.setVisible(true);
            varOficina2.setVisible(true);
            varOficina3.setVisible(true);
            varOficina4.setVisible(true);
        }
        else if(nivel==3){
            varCinco1.setVisible(true);
            varCinco2.setVisible(true);
            varCinco3.setVisible(true);
            varCinco4.setVisible(true);
            varOficina1.setVisible(true);
            varOficina2.setVisible(true);
            varOficina3.setVisible(true);
            varOficina4.setVisible(true);
        }
        else if(nivel==4){
            varCinco1.setVisible(true);
            varCinco2.setVisible(true);
            varCinco3.setVisible(true);
            varCinco4.setVisible(true);
            varOficina1.setVisible(true);
            varOficina2.setVisible(true);
            varOficina3.setVisible(true);
            varOficina4.setVisible(true);
        }
        //statusOn();
    }//GEN-LAST:event_formWindowActivated

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        LocalizarGlobalPecas localiza = new LocalizarGlobalPecas();
        localiza.setVisible(true);
        localiza.mostrarNivel.setText(mostrarNivel.getText());
        localiza.acessoUser.setText(acessoUser.getText());
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel19MouseClicked
        if(nivel==1||(acesso.equals("OF")&&nivel!=5)){
            JOptionPane.showMessageDialog(null, "VOCÊ NÃO TEM ACESSO A ESSE MÓDULO!");
        }
        else if(acesso.equals("AT")&&nivel!=5){
            JOptionPane.showMessageDialog(null, "VOCÊ NÃO TEM ACESSO A ESSE MÓDULO!\nMódulo destinado apenas aos usuários com acesso ao mercado livre!");
        }
        else{
            Configuracos conf = new Configuracos();
            conf.setVisible(true);
            conf.mostrarNivel.setText(mostrarNivel.getText());
            conf.acessoUser.setText(acessoUser.getText());
        }
    }//GEN-LAST:event_jLabel19MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        if(nivel==5||(acesso.equals("OF")&&nivel!=5)){
            OficinaSystem oficina = new OficinaSystem();
            oficina.setVisible(true);
            oficina.mostrarNivel.setText(mostrarNivel.getText());
            oficina.acessoUser.setText(acessoUser.getText());
        }
        else{ 
            JOptionPane.showMessageDialog(null, "VOCÊ NÃO TEM ACESSO A ESSE MÓDULO!");
        }
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        if(nivel==1||(acesso.equals("OF")&&nivel!=5)){
            JOptionPane.showMessageDialog(null, "VOCÊ NÃO TEM ACESSO A ESSE MÓDULO!");
        }
        else if(nivel==2){
            JOptionPane.showMessageDialog(null, "VOCÊ NÃO TEM ACESSO A ESSE MÓDULO!");
        }
        else if(nivel==3){
            JOptionPane.showMessageDialog(null, "VOCÊ NÃO TEM ACESSO A ESSE MÓDULO!");
        }
        else if(nivel==4){
            JOptionPane.showMessageDialog(null, "VOCÊ NÃO TEM ACESSO A ESSE MÓDULO!");
        }
        else{
            UserSystem user = new UserSystem();
            user.setVisible(true);
            user.mostrarNivel.setText(mostrarNivel.getText());
            user.acessoUser.setText(acessoUser.getText());
        }
    }//GEN-LAST:event_jLabel13MouseClicked

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        if(nivel==5||acesso.equals("ML")||acesso.equals("ES")){
            Requisicao requisita = new Requisicao();
            requisita.setVisible(true);
            requisita.mostrarNivel.setText(mostrarNivel.getText());
            requisita.acessoUser.setText(acessoUser.getText());
        }
        else{
            JOptionPane.showMessageDialog(null, "VOCÊ NÃO TEM ACESSO A ESSE MÓDULO!");
        }
    }//GEN-LAST:event_jLabel12MouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        if(nivel==1||(acesso.equals("OF")&&nivel!=5)){
            JOptionPane.showMessageDialog(null, "VOCÊ NÃO TEM ACESSO A ESSE MÓDULO!");
        }
        else if(nivel==2){
            JOptionPane.showMessageDialog(null, "VOCÊ NÃO TEM ACESSO A ESSE MÓDULO!");
        }
        else{
            CaminhoDaDeletacao apagar = new CaminhoDaDeletacao();
            apagar.setVisible(true);
            apagar.mostrarNivel.setText(mostrarNivel.getText());
            apagar.acessoUser.setText(acessoUser.getText());
        }
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        if(nivel==1||(acesso.equals("OF")&&nivel!=5)){
            JOptionPane.showMessageDialog(null, "VOCÊ NÃO TEM ACESSO A ESSE MÓDULO!");
        }
        else{
            EditarDoMlOuEs editar = new EditarDoMlOuEs();
            editar.setVisible(true);
            editar.mostrarNivel.setText(mostrarNivel.getText());
            editar.acessoUser.setText(acessoUser.getText());
        }
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseClicked
        if(nivel==1||(acesso.equals("OF")&&nivel!=5)){
            JOptionPane.showMessageDialog(null, "VOCÊ NÃO TEM ACESSO A ESSE MÓDULO!");
        }
        else{
            MlOuEs mloues = new MlOuEs();
            mloues.setVisible(true); 
            mloues.mostrarNivel.setText(mostrarNivel.getText());
            mloues.acessoUser.setText(acessoUser.getText());
        }
    }//GEN-LAST:event_jLabel16MouseClicked

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        status();
    }//GEN-LAST:event_formWindowClosed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        status();
    }//GEN-LAST:event_formWindowClosing

    private void userProgramadorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userProgramadorMouseClicked
        FazerBackup backup = new FazerBackup();
        backup.setVisible(true);
    }//GEN-LAST:event_userProgramadorMouseClicked

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
        if(userProgramador.isVisible()){
            int confirma = JOptionPane.showConfirmDialog(null, "DESEJA FAZER LOGOUT?","ATENÇÃO",JOptionPane.YES_NO_OPTION);
            if(confirma==JOptionPane.YES_OPTION){
                Frame[] frames = getFrames(); 
                for (int i = 0; i < frames.length; i++){ 
                    frames[i].dispose(); 
                }
                TelaInicial inicial = new TelaInicial();
                inicial.setVisible(true);
                inicial.op.setText("1");
            }
        }
    }//GEN-LAST:event_jLabel15MouseClicked

    private void userHomemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userHomemMouseClicked
        int confirma = JOptionPane.showConfirmDialog(null, "DESEJA FAZER LOGOUT?","ATENÇÃO",JOptionPane.YES_NO_OPTION);
        if(confirma==JOptionPane.YES_OPTION){
            Frame[] frames = getFrames(); 
            for (int i = 0; i < frames.length; i++){ 
                frames[i].dispose(); 
            }
            TelaInicial inicial = new TelaInicial();
            inicial.setVisible(true);
            inicial.op.setText("1");
        }
    }//GEN-LAST:event_userHomemMouseClicked

    private void userMulherMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userMulherMouseClicked
        int confirma = JOptionPane.showConfirmDialog(null, "DESEJA FAZER LOGOUT?","ATENÇÃO",JOptionPane.YES_NO_OPTION);
        if(confirma==JOptionPane.YES_OPTION){
            Frame[] frames = getFrames(); 
            for (int i = 0; i < frames.length; i++){ 
                frames[i].dispose(); 
            }
            TelaInicial inicial = new TelaInicial();
            inicial.setVisible(true);
            inicial.op.setText("1");
        }
    }//GEN-LAST:event_userMulherMouseClicked
    private void statusOn(){
        String sql = "update tbusuarios2 set status=? where NOME=?";
        try {
            pst=conexao.prepareStatement(sql);
            pst.setString(1,"ONLINE");
            pst.setString(2,nomeUser.getText());
            pst.executeUpdate();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }
    }
    private void status(){
        String sql = "update tbusuarios2 set status=? where NOME=?";
        try {
            pst=conexao.prepareStatement(sql);
            pst.setString(1,"OFFLINE");
            pst.setString(2,nomeUser.getText());
            pst.executeUpdate();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SegundaTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SegundaTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SegundaTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SegundaTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SegundaTela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel acessoUser;
    private javax.swing.JButton apagarItens;
    private javax.swing.JButton botaoConfiguracoes;
    private javax.swing.JButton botaoOficina;
    private javax.swing.JButton botaoRequisicao;
    private javax.swing.JButton cadastroItem;
    private javax.swing.JButton cadastroUsers;
    private javax.swing.JButton editarItens;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton localizarItens;
    public static javax.swing.JLabel mostrarNivel;
    public static javax.swing.JLabel nomeUser;
    private javax.swing.ButtonGroup opcoesDoMenu;
    public static javax.swing.JLabel userHomem;
    public static javax.swing.JLabel userMulher;
    public static javax.swing.JLabel userProgramador;
    public javax.swing.JLabel varCinco1;
    public javax.swing.JLabel varCinco2;
    public javax.swing.JLabel varCinco3;
    public javax.swing.JLabel varCinco4;
    public javax.swing.JLabel varDois1;
    public javax.swing.JLabel varDois2;
    public javax.swing.JLabel varDois3;
    public javax.swing.JLabel varDois4;
    public javax.swing.JLabel varOficina1;
    public javax.swing.JLabel varOficina2;
    public javax.swing.JLabel varOficina3;
    public javax.swing.JLabel varOficina4;
    public javax.swing.JLabel varQuatro1;
    public javax.swing.JLabel varQuatro2;
    public javax.swing.JLabel varQuatro3;
    public javax.swing.JLabel varQuatro4;
    public javax.swing.JLabel varSeis1;
    public javax.swing.JLabel varSeis2;
    public javax.swing.JLabel varSeis3;
    public javax.swing.JLabel varSeis4;
    public javax.swing.JLabel varTres1;
    public javax.swing.JLabel varTres2;
    public javax.swing.JLabel varTres3;
    public javax.swing.JLabel varTres4;
    public javax.swing.JLabel varUm1;
    public javax.swing.JLabel varUm2;
    public javax.swing.JLabel varUm3;
    public javax.swing.JLabel varUm4;
    // End of variables declaration//GEN-END:variables
}
