/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mklivre;

import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;
import javax.swing.JOptionPane;
import java.sql.*;
import controle.ModuloConexao;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author willi
 */
public class TudoQueTemCadastrado extends javax.swing.JFrame {
    Connection conexao = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    
    public TudoQueTemCadastrado() {
        initComponents();
        URL caminhoIcone = getClass().getResource("/mklivre/icone/icone2.png");
        Image iconeTitulo = Toolkit.getDefaultToolkit().getImage(caminhoIcone);
        this.setIconImage(iconeTitulo);
        conexao = ModuloConexao.conector();
        
    }
    int nivel,x=0;
    String acesso;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        quantItensCadastrados1 = new javax.swing.JLabel();
        quantItensCadastrados = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        localDasPecas = new javax.swing.JComboBox<>();
        botaoEditar = new javax.swing.JButton();
        campoMecanicos = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaDePecas = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        mostrarNivel = new javax.swing.JLabel();
        acessoUser = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        filtro = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("ITENS CADASTRADOS");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        getContentPane().setLayout(null);

        quantItensCadastrados1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        quantItensCadastrados1.setForeground(new java.awt.Color(255, 255, 255));
        quantItensCadastrados1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        quantItensCadastrados1.setText("ITENS");
        getContentPane().add(quantItensCadastrados1);
        quantItensCadastrados1.setBounds(390, 60, 50, 16);

        quantItensCadastrados.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        quantItensCadastrados.setForeground(new java.awt.Color(255, 255, 255));
        quantItensCadastrados.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        quantItensCadastrados.setText("0");
        getContentPane().add(quantItensCadastrados);
        quantItensCadastrados.setBounds(290, 60, 100, 16);

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Sem título.png"))); // NOI18N
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 0, 150, 80);

        localDasPecas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ESTOQUE", "MERCADO LIVRE" }));
        localDasPecas.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                localDasPecasItemStateChanged(evt);
            }
        });
        localDasPecas.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                localDasPecasCaretPositionChanged(evt);
            }
        });
        localDasPecas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                localDasPecasKeyPressed(evt);
            }
        });
        getContentPane().add(localDasPecas);
        localDasPecas.setBounds(10, 490, 130, 40);

        botaoEditar.setBackground(new java.awt.Color(0, 0, 0));
        botaoEditar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        botaoEditar.setForeground(new java.awt.Color(255, 255, 255));
        botaoEditar.setText("MOSTRAR");
        botaoEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoEditarActionPerformed(evt);
            }
        });
        botaoEditar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                botaoEditarKeyPressed(evt);
            }
        });
        getContentPane().add(botaoEditar);
        botaoEditar.setBounds(180, 490, 160, 40);

        campoMecanicos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TODOS" }));
        campoMecanicos.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                campoMecanicosItemStateChanged(evt);
            }
        });
        campoMecanicos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                campoMecanicosKeyPressed(evt);
            }
        });
        getContentPane().add(campoMecanicos);
        campoMecanicos.setBounds(550, 490, 160, 40);

        tabelaDePecas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NOME", "CÓDIGO", "CAIXA", "LOCALIZAÇÃO", "MARCA", "QUANTIDADE"
            }
        ));
        jScrollPane2.setViewportView(tabelaDePecas);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(-5, 85, 750, 395);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 21)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("ITENS CADASTRADOS");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(230, 10, 340, 60);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundo preto.png"))); // NOI18N
        jLabel1.setMinimumSize(new java.awt.Dimension(1057, 340));
        jLabel1.setPreferredSize(new java.awt.Dimension(1057, 350));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 4, 750, 77);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/FUNDO AMARELO.jpg"))); // NOI18N
        getContentPane().add(jLabel11);
        jLabel11.setBounds(0, -331, 760, 430);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/RS.png"))); // NOI18N
        getContentPane().add(jLabel10);
        jLabel10.setBounds(240, 20, 570, 550);

        mostrarNivel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        mostrarNivel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mostrarNivel.setText("5");
        getContentPane().add(mostrarNivel);
        mostrarNivel.setBounds(520, 130, 50, 70);

        acessoUser.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        acessoUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        acessoUser.setText("ADMIN");
        getContentPane().add(acessoUser);
        acessoUser.setBounds(520, 220, 70, 60);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/RS.png"))); // NOI18N
        getContentPane().add(jLabel12);
        jLabel12.setBounds(-10, 40, 570, 530);

        filtro.setText("0");
        getContentPane().add(filtro);
        filtro.setBounds(540, 240, 6, 15);

        setSize(new java.awt.Dimension(743, 576));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    int mudar=0;
    public void comboboxES(){
        int quant=campoMecanicos.getItemCount();
        int valida=0;  
        String aux[]=new String[quant];
        for(int x=0;x<quant;x++){
            aux[x]=null;
        }
        int comp=1;
        while(quant>comp){
            for(int x=0;x<quant;x++){
                if(campoMecanicos.getItemAt(comp).equals(aux[x])){
                    valida=1;
                    break;
                }
            }
            if(valida==0){
                for(int x=0;x<quant;x++){
                    if(aux[x]==null){
                       aux[x]=campoMecanicos.getItemAt(comp);
                        break;
                    }
                }
            }
            valida=0;
            comp++;
        }
        mudar=1;
        campoMecanicos.removeAllItems();
        campoMecanicos.addItem("TODOS");
        for (int x=0;x<quant;x++){
            if(aux[x]!=null){
                campoMecanicos.addItem(aux[x]);
            }
        }
        mudar=0;
    }
    public void comboboxML(){
        int quant=campoMecanicos.getItemCount();
        int valida=0;//1=NÃO E 2=SIM    
        String aux[]=new String[quant];
        for(int x=0;x<quant;x++){
            aux[x]=null;
        }
        int comp=1;
        while(quant>comp){
            for(int x=0;x<quant;x++){
                if(campoMecanicos.getItemAt(comp).equals(aux[x])){
                    valida=1;
                    break;
                }
            }
            if(valida==0){
                for(int x=0;x<quant;x++){
                    if(aux[x]==null){
                       aux[x]=campoMecanicos.getItemAt(comp);
                        break;
                    }
                }
            }
            valida=0;
            comp++;
        }
        mudar=1;
        campoMecanicos.removeAllItems();
        campoMecanicos.addItem("TODOS");
        for (int x=0;x<quant;x++){
            if(aux[x]!=null){
                campoMecanicos.addItem(aux[x]);
            }
        }
        mudar=0;
    }
    public void pupolaJComboBoxM(){
        String sql ="select * from tb_pecas_ml2";
        try {
            pst = conexao.prepareStatement(sql);
            rs=pst.executeQuery();
            while(rs.next()){
                campoMecanicos.addItem(rs.getString("MARCA"));
            }
            comboboxML();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }
    }
    public void pupolaJComboBoxE(){
        String sql ="select * from tb_pecas_es2";
        try {
            pst = conexao.prepareStatement(sql);
            rs=pst.executeQuery();
            while(rs.next()){
                campoMecanicos.addItem(rs.getString("MARCA"));
            }
            comboboxES();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }
    }
    public void setarES(){
        int setar=tabelaDePecas.getSelectedRow();
        TodosOsItensCadastrados execu = new TodosOsItensCadastrados();
        execu.setVisible(true);
        execu.codigoCadastrado.setText(tabelaDePecas.getModel().getValueAt(setar,0).toString());
        execu.nomePeca.setText(tabelaDePecas.getModel().getValueAt(setar,1).toString());
        execu.caixaLocalizada.setText(tabelaDePecas.getModel().getValueAt(setar,2).toString());
        execu.localizacaoCadastrada.setText(tabelaDePecas.getModel().getValueAt(setar,3).toString());
        execu.marcaCadastrada.setText(tabelaDePecas.getModel().getValueAt(setar,4).toString());
        execu.quantCadastrada.setText(tabelaDePecas.getModel().getValueAt(setar,5).toString());
        execu.mostrarNivel.setText(mostrarNivel.getText());
        execu.acessoUser.setText(acessoUser.getText());
        if(acessoUser.getText().equals("ES")){
            
        }
        else{
            execu.vindoDoEspera.setText("2");
        }
    }
    public void setarML(){
        int setar=tabelaDePecas.getSelectedRow();
        TodosOsItensCadastrados execu = new TodosOsItensCadastrados();
        execu.setVisible(true);
        execu.codigoCadastrado.setText(tabelaDePecas.getModel().getValueAt(setar,0).toString());
        execu.nomePeca.setText(tabelaDePecas.getModel().getValueAt(setar,1).toString());
        execu.localizacaoCadastrada.setText(tabelaDePecas.getModel().getValueAt(setar,2).toString());
        execu.marcaCadastrada.setText(tabelaDePecas.getModel().getValueAt(setar,3).toString());
        execu.quantCadastrada.setText(tabelaDePecas.getModel().getValueAt(setar,4).toString());
        execu.mostrarNivel.setText(mostrarNivel.getText());
        execu.acessoUser.setText(acessoUser.getText());
        if(acessoUser.getText().equals("ML")){
            
        }
        else{
            execu.vindoDoEspera.setText("1");
        }
    }
    private void pesquisarE(){
        String sql = "select CÓDIGO,NOME,CAIXA,LOCALIZAÇÃO,MARCA,QUANTIDADE from tb_pecas_es2";
        try {
            pst = conexao.prepareStatement(sql);
            rs=pst.executeQuery();
            tabelaDePecas.setModel(DbUtils.resultSetToTableModel(rs));
            mudar=1;
            campoMecanicos.removeAllItems();
            campoMecanicos.addItem("TODOS");
            pupolaJComboBoxE();
            mudar=0;
            contE();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }
    }
    private void contE(){
        String sql = "select * from tb_pecas_es2";
        try {
            pst = conexao.prepareStatement(sql);
            rs=pst.executeQuery();
            int xx=0;
            while(rs.next()){
                xx++;
            }
            quantItensCadastrados.setText(Integer.toString(xx));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }
    }
    private void pesquisarM(){
        String sql = "select CÓDIGO,NOME,LOCALIZAÇÃO,MARCA,QUANTIDADE,QUANTIDADE_RECOMENDADA from tb_pecas_ml2";
        try {
            pst = conexao.prepareStatement(sql);
            rs=pst.executeQuery();
            tabelaDePecas.setModel(DbUtils.resultSetToTableModel(rs));
            mudar=1;
            campoMecanicos.removeAllItems();
            campoMecanicos.addItem("TODOS");
            pupolaJComboBoxM();
            mudar=0;
            contM();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }
    }
    private void contM(){
        String sql = "select * from tb_pecas_ml2";
        try {
            pst = conexao.prepareStatement(sql);
            rs=pst.executeQuery();
            int xx=0;
            while(rs.next()){
                xx++;
            }
            quantItensCadastrados.setText(Integer.toString(xx));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }
    }
    private void pesquisarMarcaE(){
        String sql = "select CÓDIGO,NOME,CAIXA,LOCALIZAÇÃO,MARCA,QUANTIDADE from tb_pecas_es2 where MARCA =?";
        try {
            pst = conexao.prepareStatement(sql);
            pst.setString(1,campoMecanicos.getSelectedItem().toString());
            rs=pst.executeQuery();
            tabelaDePecas.setModel(DbUtils.resultSetToTableModel(rs));
            contME();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }
    }
    private void contME(){
        String sql = "select * from tb_pecas_es2 tb_pecas_es2 where MARCA =?";
        try {
            pst = conexao.prepareStatement(sql);
            pst.setString(1,campoMecanicos.getSelectedItem().toString());
            rs=pst.executeQuery();
            int xx=0;
            while(rs.next()){
                xx++;
            }
            quantItensCadastrados.setText(Integer.toString(xx));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }
    }
    private void pesquisarMarcaM(){
        String sql = "select CÓDIGO,NOME,LOCALIZAÇÃO,MARCA,QUANTIDADE,QUANTIDADE_RECOMENDADA from tb_pecas_ml2 where MARCA =?";
        try {
            pst = conexao.prepareStatement(sql);
            pst.setString(1,campoMecanicos.getSelectedItem().toString());
            rs=pst.executeQuery();
            tabelaDePecas.setModel(DbUtils.resultSetToTableModel(rs));
            contMM();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }
    }
    private void contMM(){
        String sql = "select * from tb_pecas_ml2 where MARCA =?";
        try {
            pst = conexao.prepareStatement(sql);
            pst.setString(1,campoMecanicos.getSelectedItem().toString());
            rs=pst.executeQuery();
            int xx=0;
            while(rs.next()){
                xx++;
            }
            quantItensCadastrados.setText(Integer.toString(xx));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }
    }
    private void botaoEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoEditarActionPerformed
        if(localDasPecas.getSelectedItem().toString().equals("ESTOQUE")){
            setarES();
        }
        else if(localDasPecas.getSelectedItem().toString().equals("MERCADO LIVRE")){
            setarML();
        }
    }//GEN-LAST:event_botaoEditarActionPerformed

    private void botaoEditarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_botaoEditarKeyPressed
        if(evt.getKeyCode() == evt.VK_ENTER){
            if(localDasPecas.getSelectedItem().toString().equals("ESTOQUE")){
                setarES();
            }
            else if(localDasPecas.getSelectedItem().toString().equals("MERCADO LIVRE")){
                setarML();
            }
        }
    }//GEN-LAST:event_botaoEditarKeyPressed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        nivel= Integer.parseInt(mostrarNivel.getText());
        acesso = acessoUser.getText();
        if(acesso.equals("ES")&&x==0){
            x++;
            localDasPecas.setSelectedItem("ESTOQUE");
        }
        else if(acesso.equals("ML")&&x==0){
            x++;
            localDasPecas.setSelectedItem("MERCADO LIVRE");
        }
        if(localDasPecas.getSelectedItem().toString().equals("ESTOQUE")&&filtro.getText().equals("0")){
            pesquisarE();
        }
        else if(localDasPecas.getSelectedItem().toString().equals("MERCADO LIVRE")&&filtro.getText().equals("0")){
            pesquisarM();
        }
        
    }//GEN-LAST:event_formWindowActivated

    private void localDasPecasItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_localDasPecasItemStateChanged
        if(localDasPecas.getSelectedItem().toString().equals("ESTOQUE")){
            pesquisarE();
        }
        else if(localDasPecas.getSelectedItem().toString().equals("MERCADO LIVRE")){
            
            pesquisarM();
        }
    }//GEN-LAST:event_localDasPecasItemStateChanged

    private void localDasPecasCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_localDasPecasCaretPositionChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_localDasPecasCaretPositionChanged

    private void localDasPecasKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_localDasPecasKeyPressed
        if(evt.getKeyCode() == evt.VK_ENTER){
            if(localDasPecas.getSelectedItem().toString().equals("ESTOQUE")){
                pesquisarE();
            }
            else if(localDasPecas.getSelectedItem().toString().equals("MERCADO LIVRE")){

                pesquisarM();
            }
        }
    }//GEN-LAST:event_localDasPecasKeyPressed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed

    private void campoMecanicosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoMecanicosKeyPressed
        if(evt.getKeyCode() == evt.VK_ENTER){
            if(mudar==0){
                if(campoMecanicos.getSelectedItem().toString().equals("TODOS")){
                    if(localDasPecas.getSelectedItem().toString().equals("ESTOQUE")&&filtro.getText().equals("0")){
                        pesquisarE();
                    }
                    else if(localDasPecas.getSelectedItem().toString().equals("MERCADO LIVRE")&&filtro.getText().equals("0")){
                        pesquisarM();
                    }
                }
                else{
                    if(localDasPecas.getSelectedItem().toString().equals("ESTOQUE")){
                        pesquisarMarcaE();
                    }
                    else if(localDasPecas.getSelectedItem().toString().equals("MERCADO LIVRE")){

                        pesquisarMarcaM();
                    }
                }
            }
        }
    }//GEN-LAST:event_campoMecanicosKeyPressed

    private void campoMecanicosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_campoMecanicosItemStateChanged
        if(mudar==0){
            if(campoMecanicos.getSelectedItem().toString().equals("TODOS")){
                if(localDasPecas.getSelectedItem().toString().equals("ESTOQUE")&&filtro.getText().equals("0")){
                    pesquisarE();
                }
                else if(localDasPecas.getSelectedItem().toString().equals("MERCADO LIVRE")&&filtro.getText().equals("0")){
                    pesquisarM();
                }
            }
            else{
                if(localDasPecas.getSelectedItem().toString().equals("ESTOQUE")){
                    pesquisarMarcaE();
                }
                else if(localDasPecas.getSelectedItem().toString().equals("MERCADO LIVRE")){

                    pesquisarMarcaM();
                }
            }
        }
    }//GEN-LAST:event_campoMecanicosItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TudoQueTemCadastrado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TudoQueTemCadastrado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TudoQueTemCadastrado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TudoQueTemCadastrado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TudoQueTemCadastrado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel acessoUser;
    private javax.swing.JButton botaoEditar;
    private javax.swing.JComboBox<String> campoMecanicos;
    public static javax.swing.JLabel filtro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox<String> localDasPecas;
    public static javax.swing.JLabel mostrarNivel;
    private javax.swing.JLabel quantItensCadastrados;
    private javax.swing.JLabel quantItensCadastrados1;
    public static javax.swing.JTable tabelaDePecas;
    // End of variables declaration//GEN-END:variables
}
