/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mklivre;

import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;
import javax.swing.JOptionPane;
import java.sql.*;
import controle.ModuloConexao;
/**
 *
 * @author willi
 */
public class UserCadastrado extends javax.swing.JFrame {
    Connection conexao = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    
    /**
     * Creates new form UserCadastrado
     */
    public UserCadastrado() {
        initComponents();
        URL caminhoIcone = getClass().getResource("/mklivre/icone/icone2.png");
        Image iconeTitulo = Toolkit.getDefaultToolkit().getImage(caminhoIcone);
        this.setIconImage(iconeTitulo);
        conexao = ModuloConexao.conector();
    }

    private void remover(){
        int confirma = JOptionPane.showConfirmDialog(null, "TEM CERTEZA QUE DESEJA APAGAR ESSE USUÁRIO?","ATENÇÃO",JOptionPane.YES_NO_OPTION);
        if(confirma==JOptionPane.YES_OPTION){
            String sql = "delete from tbusuarios2 where NOME = ?";
            try {
                pst=conexao.prepareStatement(sql);
                pst.setString(1, cadastroNome.getText());
                int apagado = pst.executeUpdate();
                if(apagado>0){
                    JOptionPane.showMessageDialog(null,"USUÁRIO REMOVIDO COM SUCESSO");
                    this.dispose();
                }
                else{
                    JOptionPane.showMessageDialog(null,"USUÁRIO NÃO EXISTE NO BANCO DE DADOS");
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoSexo = new javax.swing.ButtonGroup();
        grupoNivel = new javax.swing.ButtonGroup();
        botaoEntrarIniciall1 = new javax.swing.JButton();
        jLabel29 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        cadastroNome = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        botaoEntrarIniciall = new javax.swing.JButton();
        botaoEntrarIniciall3 = new javax.swing.JButton();
        sexoMascu = new javax.swing.JCheckBox();
        sexoFemi = new javax.swing.JCheckBox();
        jLabel23 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        localAtendimento = new javax.swing.JCheckBox();
        localEs = new javax.swing.JCheckBox();
        jLabel14 = new javax.swing.JLabel();
        nivelUm = new javax.swing.JCheckBox();
        nivelTres = new javax.swing.JCheckBox();
        localOficina = new javax.swing.JCheckBox();
        localML = new javax.swing.JCheckBox();
        nivelQuatro = new javax.swing.JCheckBox();
        nivelCinco = new javax.swing.JCheckBox();
        nivelDois = new javax.swing.JCheckBox();
        jLabel12 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        mostrarNivel = new javax.swing.JLabel();
        acessoUser = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("USUÁRIO CADASTRADO");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(null);

        botaoEntrarIniciall1.setBackground(new java.awt.Color(0, 0, 0));
        botaoEntrarIniciall1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        botaoEntrarIniciall1.setForeground(new java.awt.Color(255, 255, 255));
        botaoEntrarIniciall1.setText("ADICIONAR");
        botaoEntrarIniciall1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoEntrarIniciall1ActionPerformed(evt);
            }
        });
        botaoEntrarIniciall1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                botaoEntrarIniciall1KeyPressed(evt);
            }
        });
        getContentPane().add(botaoEntrarIniciall1);
        botaoEntrarIniciall1.setBounds(30, 380, 150, 40);

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("SEXO");
        getContentPane().add(jLabel29);
        jLabel29.setBounds(320, 350, 70, 21);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ACESSO PERMITIDO");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 180, 180, 21);

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("NOME");
        getContentPane().add(jLabel19);
        jLabel19.setBounds(30, 100, 100, 21);

        cadastroNome.setEditable(false);
        cadastroNome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cadastroNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cadastroNomeKeyPressed(evt);
            }
        });
        getContentPane().add(cadastroNome);
        cadastroNome.setBounds(30, 130, 200, 30);

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Sem título.png"))); // NOI18N
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel6);
        jLabel6.setBounds(-4, 0, 150, 80);

        botaoEntrarIniciall.setBackground(new java.awt.Color(0, 0, 0));
        botaoEntrarIniciall.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        botaoEntrarIniciall.setForeground(new java.awt.Color(255, 255, 255));
        botaoEntrarIniciall.setText("EDITAR");
        botaoEntrarIniciall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoEntrarIniciallActionPerformed(evt);
            }
        });
        botaoEntrarIniciall.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                botaoEntrarIniciallKeyPressed(evt);
            }
        });
        getContentPane().add(botaoEntrarIniciall);
        botaoEntrarIniciall.setBounds(30, 430, 150, 40);

        botaoEntrarIniciall3.setBackground(new java.awt.Color(0, 0, 0));
        botaoEntrarIniciall3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        botaoEntrarIniciall3.setForeground(new java.awt.Color(255, 255, 255));
        botaoEntrarIniciall3.setText("APAGAR");
        botaoEntrarIniciall3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoEntrarIniciall3ActionPerformed(evt);
            }
        });
        botaoEntrarIniciall3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                botaoEntrarIniciall3KeyPressed(evt);
            }
        });
        getContentPane().add(botaoEntrarIniciall3);
        botaoEntrarIniciall3.setBounds(30, 480, 150, 40);

        grupoSexo.add(sexoMascu);
        sexoMascu.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        sexoMascu.setForeground(new java.awt.Color(255, 255, 255));
        sexoMascu.setText("MASCULINO");
        sexoMascu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                sexoMascuKeyPressed(evt);
            }
        });
        getContentPane().add(sexoMascu);
        sexoMascu.setBounds(320, 380, 130, 25);

        grupoSexo.add(sexoFemi);
        sexoFemi.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        sexoFemi.setForeground(new java.awt.Color(255, 255, 255));
        sexoFemi.setText("FEMININO");
        sexoFemi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                sexoFemiKeyPressed(evt);
            }
        });
        getContentPane().add(sexoFemi);
        sexoFemi.setBounds(320, 420, 130, 25);

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("NÍVEL DE ACESSO");
        getContentPane().add(jLabel23);
        jLabel23.setBounds(320, 100, 180, 21);

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/faixa-cinza-5.png"))); // NOI18N
        getContentPane().add(jLabel28);
        jLabel28.setBounds(210, 570, 50, 120);

        localAtendimento.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        localAtendimento.setForeground(new java.awt.Color(255, 255, 255));
        localAtendimento.setText("ATENDIMENTO");
        localAtendimento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                localAtendimentoKeyPressed(evt);
            }
        });
        getContentPane().add(localAtendimento);
        localAtendimento.setBounds(30, 210, 240, 23);

        localEs.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        localEs.setForeground(new java.awt.Color(255, 255, 255));
        localEs.setText("ESTOQUE");
        localEs.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                localEsKeyPressed(evt);
            }
        });
        getContentPane().add(localEs);
        localEs.setBounds(30, 250, 240, 23);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 21)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("USUÁRIO");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(170, 10, 320, 60);

        grupoNivel.add(nivelUm);
        nivelUm.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        nivelUm.setForeground(new java.awt.Color(255, 255, 255));
        nivelUm.setText("NÍVEL 1");
        nivelUm.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nivelUmKeyPressed(evt);
            }
        });
        getContentPane().add(nivelUm);
        nivelUm.setBounds(320, 130, 180, 23);

        grupoNivel.add(nivelTres);
        nivelTres.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        nivelTres.setForeground(new java.awt.Color(255, 255, 255));
        nivelTres.setText("NÍVEL 3");
        nivelTres.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nivelTresKeyPressed(evt);
            }
        });
        getContentPane().add(nivelTres);
        nivelTres.setBounds(320, 210, 180, 23);

        localOficina.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        localOficina.setForeground(new java.awt.Color(255, 255, 255));
        localOficina.setText("OFICINA");
        localOficina.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                localOficinaKeyPressed(evt);
            }
        });
        getContentPane().add(localOficina);
        localOficina.setBounds(30, 330, 240, 25);

        localML.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        localML.setForeground(new java.awt.Color(255, 255, 255));
        localML.setText("MERCADO LIVRE");
        localML.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                localMLKeyPressed(evt);
            }
        });
        getContentPane().add(localML);
        localML.setBounds(30, 290, 240, 23);

        grupoNivel.add(nivelQuatro);
        nivelQuatro.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        nivelQuatro.setForeground(new java.awt.Color(255, 255, 255));
        nivelQuatro.setText("NÍVEL 4");
        nivelQuatro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nivelQuatroKeyPressed(evt);
            }
        });
        getContentPane().add(nivelQuatro);
        nivelQuatro.setBounds(320, 250, 180, 23);

        grupoNivel.add(nivelCinco);
        nivelCinco.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        nivelCinco.setForeground(new java.awt.Color(255, 255, 255));
        nivelCinco.setText("NÍVEL 5");
        nivelCinco.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nivelCincoKeyPressed(evt);
            }
        });
        getContentPane().add(nivelCinco);
        nivelCinco.setBounds(320, 290, 180, 23);

        grupoNivel.add(nivelDois);
        nivelDois.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        nivelDois.setForeground(new java.awt.Color(255, 255, 255));
        nivelDois.setText("NÍVEL 2");
        nivelDois.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nivelDoisKeyPressed(evt);
            }
        });
        getContentPane().add(nivelDois);
        nivelDois.setBounds(320, 170, 180, 23);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundo preto.png"))); // NOI18N
        jLabel12.setMinimumSize(new java.awt.Dimension(1057, 340));
        jLabel12.setPreferredSize(new java.awt.Dimension(1057, 350));
        getContentPane().add(jLabel12);
        jLabel12.setBounds(-80, 4, 760, 77);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundo preto.png"))); // NOI18N
        jLabel1.setMinimumSize(new java.awt.Dimension(1057, 340));
        jLabel1.setPreferredSize(new java.awt.Dimension(1057, 350));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(140, 4, 760, 77);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/FUNDO AMARELO.jpg"))); // NOI18N
        getContentPane().add(jLabel11);
        jLabel11.setBounds(0, -331, 760, 430);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/RS.png"))); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(320, 340, 570, 530);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/RS.png"))); // NOI18N
        getContentPane().add(jLabel9);
        jLabel9.setBounds(-20, 450, 570, 530);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/RS.png"))); // NOI18N
        getContentPane().add(jLabel10);
        jLabel10.setBounds(0, 0, 570, 530);

        mostrarNivel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        mostrarNivel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mostrarNivel.setText("5");
        getContentPane().add(mostrarNivel);
        mostrarNivel.setBounds(520, 130, 50, 70);

        acessoUser.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        acessoUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        acessoUser.setText("ADMIN");
        getContentPane().add(acessoUser);
        acessoUser.setBounds(520, 220, 70, 60);

        setSize(new java.awt.Dimension(542, 567));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botaoEntrarIniciallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoEntrarIniciallActionPerformed
        EditarUsuario editar = new EditarUsuario();
        editar.setVisible(true);
        editar.cadastroNome.setText(cadastroNome.getText());
        editar.mostrarNivel.setText(mostrarNivel.getText());
        editar.acessoUser.setText(acessoUser.getText());
        if(sexoMascu.isSelected()){
            editar.sexoMascu.setSelected(true);
        }
        else if(sexoFemi.isSelected()){
            editar.sexoFemi.setSelected(true);
        }
        if(localAtendimento.isSelected()){
            editar.localAtendimento.setSelected(true);
        }
        if(localEs.isSelected()){
            editar.localEs.setSelected(true);
        }
        if(localML.isSelected()){
            editar.localML.setSelected(true);
        }
        if(localOficina.isSelected()){
            editar.localOficina.setSelected(true);
        }
        if(nivelUm.isSelected()){
            editar.nivelUm.setSelected(true);
        }
        else if(nivelDois.isSelected()){
            editar.nivelDois.setSelected(true);
        }
        else if(nivelTres.isSelected()){
            editar.nivelTres.setSelected(true);
        }
        else if(nivelQuatro.isSelected()){
            editar.nivelQuatro.setSelected(true);
        }
        else if(nivelCinco.isSelected()){
            editar.nivelCinco.setSelected(true);
        }
        this.dispose();
    }//GEN-LAST:event_botaoEntrarIniciallActionPerformed

    private void botaoEntrarIniciall3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoEntrarIniciall3ActionPerformed
        remover();
    }//GEN-LAST:event_botaoEntrarIniciall3ActionPerformed

    private void cadastroNomeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cadastroNomeKeyPressed
        if(evt.getKeyCode() == evt.VK_ENTER){
            localAtendimento.requestFocus();
        }
    }//GEN-LAST:event_cadastroNomeKeyPressed

    private void botaoEntrarIniciallKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_botaoEntrarIniciallKeyPressed
        if(evt.getKeyCode() == evt.VK_ENTER){
            EditarUsuario editar = new EditarUsuario();
            editar.setVisible(true);
            editar.cadastroNome.setText(cadastroNome.getText());
            editar.mostrarNivel.setText(mostrarNivel.getText());
            editar.acessoUser.setText(acessoUser.getText());
            if(sexoMascu.isSelected()){
                editar.sexoMascu.setSelected(true);
            }
            else if(sexoFemi.isSelected()){
                editar.sexoFemi.setSelected(true);
            }
            if(localAtendimento.isSelected()){
                editar.localAtendimento.setSelected(true);
            }
            if(localEs.isSelected()){
                editar.localEs.setSelected(true);
            }
            if(localML.isSelected()){
                editar.localML.setSelected(true);
            }
            if(localOficina.isSelected()){
                editar.localOficina.setSelected(true);
            }
            if(nivelUm.isSelected()){
                editar.nivelUm.setSelected(true);
            }
            else if(nivelDois.isSelected()){
                editar.nivelDois.setSelected(true);
            }
            else if(nivelTres.isSelected()){
                editar.nivelTres.setSelected(true);
            }
            else if(nivelQuatro.isSelected()){
                editar.nivelQuatro.setSelected(true);
            }
            else if(nivelCinco.isSelected()){
                editar.nivelCinco.setSelected(true);
            }
            this.dispose();
        }
    }//GEN-LAST:event_botaoEntrarIniciallKeyPressed

    private void botaoEntrarIniciall3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_botaoEntrarIniciall3KeyPressed
        if(evt.getKeyCode() == evt.VK_ENTER){
            remover();
        }
    }//GEN-LAST:event_botaoEntrarIniciall3KeyPressed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        
    }//GEN-LAST:event_formWindowActivated

    private void localAtendimentoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_localAtendimentoKeyPressed
        if(evt.getKeyCode() == evt.VK_ENTER){
            localEs.requestFocus();
        }
    }//GEN-LAST:event_localAtendimentoKeyPressed

    private void localEsKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_localEsKeyPressed
        if(evt.getKeyCode() == evt.VK_ENTER){
            localML.requestFocus();
        }
    }//GEN-LAST:event_localEsKeyPressed

    private void localMLKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_localMLKeyPressed
        if(evt.getKeyCode() == evt.VK_ENTER){
            localOficina.requestFocus();
        }
    }//GEN-LAST:event_localMLKeyPressed

    private void localOficinaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_localOficinaKeyPressed
        if(evt.getKeyCode() == evt.VK_ENTER){
            nivelUm.requestFocus();
        }
    }//GEN-LAST:event_localOficinaKeyPressed

    private void nivelUmKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nivelUmKeyPressed
        if(evt.getKeyCode() == evt.VK_ENTER){
            nivelDois.requestFocus();
        }
    }//GEN-LAST:event_nivelUmKeyPressed

    private void nivelDoisKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nivelDoisKeyPressed
        if(evt.getKeyCode() == evt.VK_ENTER){
            nivelTres.requestFocus();
        }
    }//GEN-LAST:event_nivelDoisKeyPressed

    private void nivelTresKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nivelTresKeyPressed
        if(evt.getKeyCode() == evt.VK_ENTER){
            nivelQuatro.requestFocus();
        }
    }//GEN-LAST:event_nivelTresKeyPressed

    private void nivelQuatroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nivelQuatroKeyPressed
        if(evt.getKeyCode() == evt.VK_ENTER){
            nivelCinco.requestFocus();
        }
    }//GEN-LAST:event_nivelQuatroKeyPressed

    private void nivelCincoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nivelCincoKeyPressed
        if(evt.getKeyCode() == evt.VK_ENTER){
            sexoMascu.requestFocus();
        }
    }//GEN-LAST:event_nivelCincoKeyPressed

    private void sexoMascuKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sexoMascuKeyPressed
        if(evt.getKeyCode() == evt.VK_ENTER){
            sexoFemi.requestFocus();
        }
    }//GEN-LAST:event_sexoMascuKeyPressed

    private void sexoFemiKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sexoFemiKeyPressed
        if(evt.getKeyCode() == evt.VK_ENTER){
            EditarUsuario editar = new EditarUsuario();
            editar.setVisible(true);
            editar.cadastroNome.setText(cadastroNome.getText());
            editar.mostrarNivel.setText(mostrarNivel.getText());
            editar.acessoUser.setText(acessoUser.getText());
            if(sexoMascu.isSelected()){
                editar.sexoMascu.setSelected(true);
            }
            else if(sexoFemi.isSelected()){
                editar.sexoFemi.setSelected(true);
            }
            if(localAtendimento.isSelected()){
                editar.localAtendimento.setSelected(true);
            }
            if(localEs.isSelected()){
                editar.localEs.setSelected(true);
            }
            if(localML.isSelected()){
                editar.localML.setSelected(true);
            }
            if(localOficina.isSelected()){
                editar.localOficina.setSelected(true);
            }
            if(nivelUm.isSelected()){
                editar.nivelUm.setSelected(true);
            }
            else if(nivelDois.isSelected()){
                editar.nivelDois.setSelected(true);
            }
            else if(nivelTres.isSelected()){
                editar.nivelTres.setSelected(true);
            }
            else if(nivelQuatro.isSelected()){
                editar.nivelQuatro.setSelected(true);
            }
            else if(nivelCinco.isSelected()){
                editar.nivelCinco.setSelected(true);
            }
            this.dispose();
        }
    }//GEN-LAST:event_sexoFemiKeyPressed

    private void botaoEntrarIniciall1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoEntrarIniciall1ActionPerformed
        NovoUser novo = new NovoUser();
        novo.setVisible(true);
        novo.mostrarNivel.setText(mostrarNivel.getText());
        novo.acessoUser.setText(acessoUser.getText());
        this.dispose();
    }//GEN-LAST:event_botaoEntrarIniciall1ActionPerformed

    private void botaoEntrarIniciall1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_botaoEntrarIniciall1KeyPressed
        if(evt.getKeyCode() == evt.VK_ENTER){
            NovoUser novo = new NovoUser();
            novo.setVisible(true);
            novo.mostrarNivel.setText(mostrarNivel.getText());
            novo.acessoUser.setText(acessoUser.getText());
            this.dispose();
        }
    }//GEN-LAST:event_botaoEntrarIniciall1KeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserCadastrado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserCadastrado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserCadastrado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserCadastrado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserCadastrado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel acessoUser;
    private javax.swing.JButton botaoEntrarIniciall;
    private javax.swing.JButton botaoEntrarIniciall1;
    private javax.swing.JButton botaoEntrarIniciall3;
    public static javax.swing.JTextField cadastroNome;
    private javax.swing.ButtonGroup grupoNivel;
    private javax.swing.ButtonGroup grupoSexo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public static javax.swing.JCheckBox localAtendimento;
    public static javax.swing.JCheckBox localEs;
    public static javax.swing.JCheckBox localML;
    public static javax.swing.JCheckBox localOficina;
    public static javax.swing.JLabel mostrarNivel;
    public static javax.swing.JCheckBox nivelCinco;
    public static javax.swing.JCheckBox nivelDois;
    public static javax.swing.JCheckBox nivelQuatro;
    public static javax.swing.JCheckBox nivelTres;
    public static javax.swing.JCheckBox nivelUm;
    public static javax.swing.JCheckBox sexoFemi;
    public static javax.swing.JCheckBox sexoMascu;
    // End of variables declaration//GEN-END:variables
}
