/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mklivre;
import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;
import javax.swing.JOptionPane;
import java.sql.*;
/**
 *
 * @author willi
 */
public class Vendas extends javax.swing.JFrame {
    Connection conexao = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    /**
     * Creates new form Lucro
     */
    public Vendas() {
        initComponents();
        URL caminhoIcone = getClass().getResource("/mklivre/icone/icone2.png");
        Image iconeTitulo = Toolkit.getDefaultToolkit().getImage(caminhoIcone);
        this.setIconImage(iconeTitulo);
        botCima.setVisible(false);
        botMaisVendido.setVisible(false);
        botCancelados.setVisible(false);
        botRendaMensal.setVisible(false);
        maisVendidos.setVisible(false);
        vendasCanceladas.setVisible(false);
        rendimentoAnual.setVisible(false);      
        botMeta.setVisible(false);
        meta.setVisible(false);
        varUm1.setVisible(false);
        varUm2.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        varUm1 = new javax.swing.JLabel();
        varUm2 = new javax.swing.JLabel();
        botCancela = new javax.swing.JButton();
        cancela1 = new javax.swing.JLabel();
        consulta1 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        venda1 = new javax.swing.JLabel();
        botEdita = new javax.swing.JButton();
        botConsulta = new javax.swing.JButton();
        botVenda = new javax.swing.JButton();
        botRenda = new javax.swing.JButton();
        edita1 = new javax.swing.JLabel();
        renda1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        mensal1 = new javax.swing.JLabel();
        botCima = new javax.swing.JButton();
        botBaixo = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        botMeta = new javax.swing.JButton();
        meta = new javax.swing.JLabel();
        botRendaMensal = new javax.swing.JButton();
        botCancelados = new javax.swing.JButton();
        botMaisVendido = new javax.swing.JButton();
        maisVendidos = new javax.swing.JLabel();
        vendasCanceladas = new javax.swing.JLabel();
        rendimentoAnual = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        acessoUser = new javax.swing.JLabel();
        mostrarNivel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("VENDAS DO MERCADO LIVRE");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(null);

        varUm1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/faixa-cinza-5.png"))); // NOI18N
        getContentPane().add(varUm1);
        varUm1.setBounds(130, 470, 60, 60);

        varUm2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/faixa-cinza-5.png"))); // NOI18N
        getContentPane().add(varUm2);
        varUm2.setBounds(130, 470, 60, 60);

        botCancela.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/venda cancelada.png"))); // NOI18N
        botCancela.setMaximumSize(new java.awt.Dimension(32, 32));
        botCancela.setMinimumSize(new java.awt.Dimension(32, 32));
        botCancela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botCancelaActionPerformed(evt);
            }
        });
        botCancela.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                botCancelaKeyPressed(evt);
            }
        });
        getContentPane().add(botCancela);
        botCancela.setBounds(10, 330, 60, 58);

        cancela1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cancela1.setForeground(new java.awt.Color(255, 255, 255));
        cancela1.setText("CANCELAR VENDA");
        cancela1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancela1MouseClicked(evt);
            }
        });
        getContentPane().add(cancela1);
        cancela1.setBounds(80, 350, 230, 22);

        consulta1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        consulta1.setForeground(new java.awt.Color(255, 255, 255));
        consulta1.setText("CONSULTAR VENDAS");
        consulta1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                consulta1MouseClicked(evt);
            }
        });
        getContentPane().add(consulta1);
        consulta1.setBounds(80, 210, 310, 22);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("VENDAS");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(120, 30, 230, 22);

        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Sem título.png"))); // NOI18N
        jLabel15.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel15);
        jLabel15.setBounds(-10, 0, 150, 80);

        venda1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        venda1.setForeground(new java.awt.Color(255, 255, 255));
        venda1.setText("NOVA VENDA");
        venda1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                venda1MouseClicked(evt);
            }
        });
        getContentPane().add(venda1);
        venda1.setBounds(80, 140, 170, 22);

        botEdita.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/editar venda.png"))); // NOI18N
        botEdita.setMaximumSize(new java.awt.Dimension(32, 32));
        botEdita.setMinimumSize(new java.awt.Dimension(32, 32));
        botEdita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botEditaActionPerformed(evt);
            }
        });
        botEdita.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                botEditaKeyPressed(evt);
            }
        });
        getContentPane().add(botEdita);
        botEdita.setBounds(10, 260, 60, 58);

        botConsulta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/consulta venda.png"))); // NOI18N
        botConsulta.setMaximumSize(new java.awt.Dimension(32, 32));
        botConsulta.setMinimumSize(new java.awt.Dimension(32, 32));
        botConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botConsultaActionPerformed(evt);
            }
        });
        botConsulta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                botConsultaKeyPressed(evt);
            }
        });
        getContentPane().add(botConsulta);
        botConsulta.setBounds(10, 190, 60, 58);

        botVenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/nova venda.png"))); // NOI18N
        botVenda.setMaximumSize(new java.awt.Dimension(32, 32));
        botVenda.setMinimumSize(new java.awt.Dimension(32, 32));
        botVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botVendaActionPerformed(evt);
            }
        });
        botVenda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                botVendaKeyPressed(evt);
            }
        });
        getContentPane().add(botVenda);
        botVenda.setBounds(10, 120, 60, 58);

        botRenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/renda.png"))); // NOI18N
        botRenda.setMaximumSize(new java.awt.Dimension(32, 32));
        botRenda.setMinimumSize(new java.awt.Dimension(32, 32));
        botRenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botRendaActionPerformed(evt);
            }
        });
        botRenda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                botRendaKeyPressed(evt);
            }
        });
        getContentPane().add(botRenda);
        botRenda.setBounds(10, 400, 60, 58);

        edita1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        edita1.setForeground(new java.awt.Color(255, 255, 255));
        edita1.setText("EDITAR VENDAS");
        edita1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                edita1MouseClicked(evt);
            }
        });
        getContentPane().add(edita1);
        edita1.setBounds(80, 280, 230, 22);

        renda1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        renda1.setForeground(new java.awt.Color(255, 255, 255));
        renda1.setText("CONSULTAR RENDA");
        renda1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                renda1MouseClicked(evt);
            }
        });
        getContentPane().add(renda1);
        renda1.setBounds(80, 410, 320, 22);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundo preto.png"))); // NOI18N
        jLabel3.setMinimumSize(new java.awt.Dimension(1057, 340));
        jLabel3.setPreferredSize(new java.awt.Dimension(1057, 350));
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 4, 450, 77);

        mensal1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        mensal1.setForeground(new java.awt.Color(255, 255, 255));
        mensal1.setText("MENSAL");
        mensal1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mensal1MouseClicked(evt);
            }
        });
        getContentPane().add(mensal1);
        mensal1.setBounds(80, 430, 320, 22);

        botCima.setBackground(new java.awt.Color(0, 0, 0));
        botCima.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        botCima.setForeground(new java.awt.Color(255, 255, 255));
        botCima.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cima.png"))); // NOI18N
        botCima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botCimaActionPerformed(evt);
            }
        });
        botCima.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                botCimaKeyPressed(evt);
            }
        });
        getContentPane().add(botCima);
        botCima.setBounds(140, 110, 60, 60);

        botBaixo.setBackground(new java.awt.Color(0, 0, 0));
        botBaixo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        botBaixo.setForeground(new java.awt.Color(255, 255, 255));
        botBaixo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/baixo.png"))); // NOI18N
        botBaixo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botBaixoActionPerformed(evt);
            }
        });
        botBaixo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                botBaixoKeyPressed(evt);
            }
        });
        getContentPane().add(botBaixo);
        botBaixo.setBounds(130, 470, 60, 60);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/FUNDO AMARELO.jpg"))); // NOI18N
        getContentPane().add(jLabel11);
        jLabel11.setBounds(0, -331, 460, 430);

        botMeta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/META.png"))); // NOI18N
        botMeta.setMaximumSize(new java.awt.Dimension(32, 32));
        botMeta.setMinimumSize(new java.awt.Dimension(32, 32));
        botMeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botMetaActionPerformed(evt);
            }
        });
        botMeta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                botMetaKeyPressed(evt);
            }
        });
        getContentPane().add(botMeta);
        botMeta.setBounds(10, 430, 60, 58);

        meta.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        meta.setForeground(new java.awt.Color(255, 0, 0));
        meta.setText("META DE VENDAS");
        meta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                metaMouseClicked(evt);
            }
        });
        getContentPane().add(meta);
        meta.setBounds(80, 450, 230, 22);

        botRendaMensal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/rendimento.png"))); // NOI18N
        botRendaMensal.setMaximumSize(new java.awt.Dimension(32, 32));
        botRendaMensal.setMinimumSize(new java.awt.Dimension(32, 32));
        botRendaMensal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botRendaMensalActionPerformed(evt);
            }
        });
        botRendaMensal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                botRendaMensalKeyPressed(evt);
            }
        });
        getContentPane().add(botRendaMensal);
        botRendaMensal.setBounds(10, 360, 60, 58);

        botCancelados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cancel.png"))); // NOI18N
        botCancelados.setMaximumSize(new java.awt.Dimension(32, 32));
        botCancelados.setMinimumSize(new java.awt.Dimension(32, 32));
        botCancelados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botCanceladosActionPerformed(evt);
            }
        });
        botCancelados.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                botCanceladosKeyPressed(evt);
            }
        });
        getContentPane().add(botCancelados);
        botCancelados.setBounds(10, 290, 60, 58);

        botMaisVendido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/mais 2.png"))); // NOI18N
        botMaisVendido.setMaximumSize(new java.awt.Dimension(32, 32));
        botMaisVendido.setMinimumSize(new java.awt.Dimension(32, 32));
        botMaisVendido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botMaisVendidoActionPerformed(evt);
            }
        });
        botMaisVendido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                botMaisVendidoKeyPressed(evt);
            }
        });
        getContentPane().add(botMaisVendido);
        botMaisVendido.setBounds(10, 220, 60, 58);

        maisVendidos.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        maisVendidos.setForeground(new java.awt.Color(255, 0, 0));
        maisVendidos.setText("MAIS VENDIDOS");
        maisVendidos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                maisVendidosMouseClicked(evt);
            }
        });
        getContentPane().add(maisVendidos);
        maisVendidos.setBounds(80, 240, 170, 22);

        vendasCanceladas.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        vendasCanceladas.setForeground(new java.awt.Color(255, 0, 0));
        vendasCanceladas.setText("VENDAS CANCELADAS");
        vendasCanceladas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                vendasCanceladasMouseClicked(evt);
            }
        });
        getContentPane().add(vendasCanceladas);
        vendasCanceladas.setBounds(80, 310, 310, 22);

        rendimentoAnual.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rendimentoAnual.setForeground(new java.awt.Color(255, 0, 0));
        rendimentoAnual.setText("RENDIMENTO ANUAL");
        rendimentoAnual.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rendimentoAnualMouseClicked(evt);
            }
        });
        getContentPane().add(rendimentoAnual);
        rendimentoAnual.setBounds(80, 380, 230, 22);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/RS.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, -190, 450, 790);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/RS.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(-20, 220, 420, 790);

        acessoUser.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        acessoUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        acessoUser.setText("ADMIN");
        getContentPane().add(acessoUser);
        acessoUser.setBounds(520, 220, 70, 60);

        mostrarNivel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        mostrarNivel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mostrarNivel.setText("5");
        getContentPane().add(mostrarNivel);
        mostrarNivel.setBounds(520, 130, 50, 70);

        setBounds(300, 100, 355, 571);
    }// </editor-fold>//GEN-END:initComponents

    private void consulta1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_consulta1MouseClicked
        LocalizarVendas pausados = new LocalizarVendas();
        pausados.setVisible(true);
        pausados.mostrarNivel.setText(mostrarNivel.getText());
        pausados.acessoUser.setText(acessoUser.getText());
    }//GEN-LAST:event_consulta1MouseClicked

    private void venda1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_venda1MouseClicked
        NovaVenda tudo = new NovaVenda();
        tudo.setVisible(true);
        tudo.mostrarNivel.setText(mostrarNivel.getText());
        tudo.acessoUser.setText(acessoUser.getText());
    }//GEN-LAST:event_venda1MouseClicked

    private void botEditaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botEditaActionPerformed
        LocalizarEdicaoVenda mais = new LocalizarEdicaoVenda();
        mais.setVisible(true);
        mais.mostrarNivel.setText(mostrarNivel.getText());
        mais.acessoUser.setText(acessoUser.getText());
    }//GEN-LAST:event_botEditaActionPerformed

    private void botEditaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_botEditaKeyPressed
        if(evt.getKeyCode() == evt.VK_ENTER){
            LocalizarEdicaoVenda mais = new LocalizarEdicaoVenda();
            mais.setVisible(true);
            mais.mostrarNivel.setText(mostrarNivel.getText());
            mais.acessoUser.setText(acessoUser.getText());
        }
    }//GEN-LAST:event_botEditaKeyPressed

    private void botConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botConsultaActionPerformed
        LocalizarVendas pausados = new LocalizarVendas();
        pausados.setVisible(true);
        pausados.mostrarNivel.setText(mostrarNivel.getText());
        pausados.acessoUser.setText(acessoUser.getText());
    }//GEN-LAST:event_botConsultaActionPerformed

    private void botConsultaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_botConsultaKeyPressed
        if(evt.getKeyCode() == evt.VK_ENTER){
            LocalizarVendas pausados = new LocalizarVendas();
            pausados.setVisible(true);
            pausados.mostrarNivel.setText(mostrarNivel.getText());
            pausados.acessoUser.setText(acessoUser.getText());
        }
    }//GEN-LAST:event_botConsultaKeyPressed

    private void botVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botVendaActionPerformed
        NovaVenda tudo = new NovaVenda();
        tudo.setVisible(true);
        tudo.mostrarNivel.setText(mostrarNivel.getText());
        tudo.acessoUser.setText(acessoUser.getText());
    }//GEN-LAST:event_botVendaActionPerformed

    private void botVendaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_botVendaKeyPressed
        if(evt.getKeyCode() == evt.VK_ENTER){
            NovaVenda tudo = new NovaVenda();
            tudo.setVisible(true);
            tudo.mostrarNivel.setText(mostrarNivel.getText());
            tudo.acessoUser.setText(acessoUser.getText());
        }
    }//GEN-LAST:event_botVendaKeyPressed

    private void botRendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botRendaActionPerformed
        JOptionPane.showMessageDialog(null,"MÓDULO EM CONSTRUÇÃO"); 
        /*RendaMensal caminho = new RendaMensal();
        caminho.setVisible(true);
        caminho.mostrarNivel.setText(mostrarNivel.getText());
        caminho.acessoUser.setText(acessoUser.getText());*/
    }//GEN-LAST:event_botRendaActionPerformed

    private void botRendaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_botRendaKeyPressed
        if(evt.getKeyCode() == evt.VK_ENTER){
            JOptionPane.showMessageDialog(null,"MÓDULO EM CONSTRUÇÃO"); 
            /*RendaMensal caminho = new RendaMensal();
            caminho.setVisible(true);
            caminho.mostrarNivel.setText(mostrarNivel.getText());
            caminho.acessoUser.setText(acessoUser.getText());*/
        }
    }//GEN-LAST:event_botRendaKeyPressed

    private void edita1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_edita1MouseClicked
        LocalizarEdicaoVenda mais = new LocalizarEdicaoVenda();
        mais.setVisible(true);
        mais.mostrarNivel.setText(mostrarNivel.getText());
        mais.acessoUser.setText(acessoUser.getText());
    }//GEN-LAST:event_edita1MouseClicked

    private void renda1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_renda1MouseClicked
        JOptionPane.showMessageDialog(null,"MÓDULO EM CONSTRUÇÃO"); 
        /*RendaMensal caminho = new RendaMensal();
        caminho.setVisible(true);
        caminho.mostrarNivel.setText(mostrarNivel.getText());
        caminho.acessoUser.setText(acessoUser.getText());*/
    }//GEN-LAST:event_renda1MouseClicked

    private void mensal1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mensal1MouseClicked
        JOptionPane.showMessageDialog(null,"MÓDULO EM CONSTRUÇÃO"); 
        /*RendaMensal caminho = new RendaMensal();
        caminho.setVisible(true);
        caminho.mostrarNivel.setText(mostrarNivel.getText());
        caminho.acessoUser.setText(acessoUser.getText());*/
    }//GEN-LAST:event_mensal1MouseClicked

    private void botCancelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botCancelaActionPerformed
        CancelarVenda cancela = new CancelarVenda();
        cancela.setVisible(true);
        cancela.mostrarNivel.setText(mostrarNivel.getText());
        cancela.acessoUser.setText(acessoUser.getText());
    }//GEN-LAST:event_botCancelaActionPerformed

    private void botCancelaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_botCancelaKeyPressed
        if(evt.getKeyCode() == evt.VK_ENTER){
            CancelarVenda cancela = new CancelarVenda();
            cancela.setVisible(true);
            cancela.mostrarNivel.setText(mostrarNivel.getText());
            cancela.acessoUser.setText(acessoUser.getText());
        }
    }//GEN-LAST:event_botCancelaKeyPressed

    private void cancela1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancela1MouseClicked
        CancelarVenda cancela = new CancelarVenda();
        cancela.setVisible(true);
        cancela.mostrarNivel.setText(mostrarNivel.getText());
        cancela.acessoUser.setText(acessoUser.getText());
    }//GEN-LAST:event_cancela1MouseClicked

    private void botBaixoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botBaixoActionPerformed
        if(Integer.parseInt(mostrarNivel.getText())<5){
            JOptionPane.showMessageDialog(null,"VOCÊ NÃO TEM ACESSO A SEGUNDA PARTE DO MÓDULO DE VENDAS!");
        }
        else{
            //JOptionPane.showMessageDialog(null,"MÓDULO EM CONSTRUÇÃO"); 
            botVenda.setVisible(false);
            venda1.setVisible(false);
            botConsulta.setVisible(false);
            consulta1.setVisible(false);      
            botEdita.setVisible(false);        
            edita1.setVisible(false);        
            botCancela.setVisible(false);        
            cancela1.setVisible(false);
            botRenda.setVisible(false);        
            renda1.setVisible(false);
            mensal1.setVisible(false);
            botBaixo.setVisible(false);
            botCima.setVisible(true);
            botMaisVendido.setVisible(true);
            botCancelados.setVisible(true);
            botRendaMensal.setVisible(true);
            maisVendidos.setVisible(true);
            vendasCanceladas.setVisible(true);
            rendimentoAnual.setVisible(true);   
            botMeta.setVisible(true);
            meta.setVisible(true);
        }
    }//GEN-LAST:event_botBaixoActionPerformed

    private void botBaixoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_botBaixoKeyPressed
        if(evt.getKeyCode() == evt.VK_ENTER){
            if(Integer.parseInt(mostrarNivel.getText())<5){
                JOptionPane.showMessageDialog(null,"VOCÊ NÃO TEM ACESSO A SEGUNDA PARTE DO MÓDULO DE VENDAS!");
            }
            else{
                JOptionPane.showMessageDialog(null,"MÓDULO EM CONSTRUÇÃO"); 
                /*botVenda.setVisible(false);
                venda1.setVisible(false);
                botConsulta.setVisible(false);
                consulta1.setVisible(false);      
                botEdita.setVisible(false);        
                edita1.setVisible(false);        
                botCancela.setVisible(false);        
                cancela1.setVisible(false);
                botRenda.setVisible(false);        
                renda1.setVisible(false);
                mensal1.setVisible(false);
                botBaixo.setVisible(false);
                botCima.setVisible(true);
                botMaisVendido.setVisible(true);
                botCancelados.setVisible(true);
                botRendaMensal.setVisible(true);
                maisVendidos.setVisible(true);
                vendasCanceladas.setVisible(true);
                rendimentoAnual.setVisible(true);   
                botMeta.setVisible(true);
                meta.setVisible(true);*/
            }
        }
    }//GEN-LAST:event_botBaixoKeyPressed

    private void botCimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botCimaActionPerformed
        botVenda.setVisible(true);
        venda1.setVisible(true);
        botConsulta.setVisible(true);
        consulta1.setVisible(true);      
        botEdita.setVisible(true);        
        edita1.setVisible(true);        
        botCancela.setVisible(true);        
        cancela1.setVisible(true);
        botRenda.setVisible(true);        
        renda1.setVisible(true);
        mensal1.setVisible(true);
        botBaixo.setVisible(true);
        botCima.setVisible(false);
        botMaisVendido.setVisible(false);
        botCancelados.setVisible(false);
        botRendaMensal.setVisible(false);
        maisVendidos.setVisible(false);
        vendasCanceladas.setVisible(false);
        rendimentoAnual.setVisible(false);   
        botMeta.setVisible(false);
        meta.setVisible(false);
    }//GEN-LAST:event_botCimaActionPerformed

    private void botCimaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_botCimaKeyPressed
        if(evt.getKeyCode() == evt.VK_ENTER){
            botVenda.setVisible(true);
            venda1.setVisible(true);
            botConsulta.setVisible(true);
            consulta1.setVisible(true);      
            botEdita.setVisible(true);        
            edita1.setVisible(true);        
            botCancela.setVisible(true);        
            cancela1.setVisible(true);
            botRenda.setVisible(true);        
            renda1.setVisible(true);
            mensal1.setVisible(true);
            botBaixo.setVisible(true);
            botCima.setVisible(false);
            botMaisVendido.setVisible(false);
            botCancelados.setVisible(false);
            botRendaMensal.setVisible(false);
            maisVendidos.setVisible(false);
            vendasCanceladas.setVisible(false);
            rendimentoAnual.setVisible(false);   
            botMeta.setVisible(false);
            meta.setVisible(false);
        }
    }//GEN-LAST:event_botCimaKeyPressed

    private void botRendaMensalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botRendaMensalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botRendaMensalActionPerformed

    private void botRendaMensalKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_botRendaMensalKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_botRendaMensalKeyPressed

    private void botCanceladosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botCanceladosActionPerformed
        VendasCanceladas canceladas = new VendasCanceladas();
        canceladas.setVisible(true);
        canceladas.mostrarNivel.setText(mostrarNivel.getText());
        canceladas.acessoUser.setText(acessoUser.getText());
        
    }//GEN-LAST:event_botCanceladosActionPerformed

    private void botCanceladosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_botCanceladosKeyPressed
        if(evt.getKeyCode() == evt.VK_ENTER){
            VendasCanceladas canceladas = new VendasCanceladas();
            canceladas.setVisible(true);
            canceladas.mostrarNivel.setText(mostrarNivel.getText());
            canceladas.acessoUser.setText(acessoUser.getText());
        }
    }//GEN-LAST:event_botCanceladosKeyPressed

    private void botMaisVendidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botMaisVendidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botMaisVendidoActionPerformed

    private void botMaisVendidoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_botMaisVendidoKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_botMaisVendidoKeyPressed

    private void maisVendidosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_maisVendidosMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_maisVendidosMouseClicked

    private void vendasCanceladasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vendasCanceladasMouseClicked
        VendasCanceladas canceladas = new VendasCanceladas();
        canceladas.setVisible(true);
        canceladas.mostrarNivel.setText(mostrarNivel.getText());
        canceladas.acessoUser.setText(acessoUser.getText());
    }//GEN-LAST:event_vendasCanceladasMouseClicked

    private void rendimentoAnualMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rendimentoAnualMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_rendimentoAnualMouseClicked

    private void botMetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botMetaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botMetaActionPerformed

    private void botMetaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_botMetaKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_botMetaKeyPressed

    private void metaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_metaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_metaMouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        if(Integer.parseInt(mostrarNivel.getText())<5){
            varUm1.setVisible(true);
            varUm2.setVisible(true);
        }
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vendas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel acessoUser;
    private javax.swing.JButton botBaixo;
    private javax.swing.JButton botCancela;
    private javax.swing.JButton botCancelados;
    private javax.swing.JButton botCima;
    private javax.swing.JButton botConsulta;
    private javax.swing.JButton botEdita;
    private javax.swing.JButton botMaisVendido;
    private javax.swing.JButton botMeta;
    private javax.swing.JButton botRenda;
    private javax.swing.JButton botRendaMensal;
    private javax.swing.JButton botVenda;
    private javax.swing.JLabel cancela1;
    private javax.swing.JLabel consulta1;
    private javax.swing.JLabel edita1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel maisVendidos;
    private javax.swing.JLabel mensal1;
    private javax.swing.JLabel meta;
    public static javax.swing.JLabel mostrarNivel;
    private javax.swing.JLabel renda1;
    private javax.swing.JLabel rendimentoAnual;
    public javax.swing.JLabel varUm1;
    public javax.swing.JLabel varUm2;
    private javax.swing.JLabel venda1;
    private javax.swing.JLabel vendasCanceladas;
    // End of variables declaration//GEN-END:variables
}
